// DatoYa 2.0 — UI de seguridad de cuenta, recuperación, verificaciones y legales.
(() => {
  const e = value => String(value ?? '').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const statusPill=(ok,yes,no)=>`<span class="pill" style="${ok?'background:#dcfce7;color:#166534':'background:#fff7ed;color:#9a3412'}">${ok?yes:no}</span>`;

  routes.login = async function(){
    view.innerHTML=`<div class="card" style="max-width:440px;margin:20px auto"><h2>Ingresar a DatoYa</h2><form onsubmit="doLogin(event)"><div class="field"><label>Correo electrónico</label><input name="email" type="email" autocomplete="email" required></div><div class="field"><label>Contraseña</label><input name="password" type="password" autocomplete="current-password" required></div><button class="btn btn-primary btn-block">Ingresar</button></form><div style="text-align:center;margin-top:12px"><a href="#/recuperar">¿Olvidaste tu contraseña?</a></div></div>`;
  };

  routes.registro = async function(){
    const {comunas}=await api('/comunas');
    view.innerHTML=`<div class="card" style="max-width:560px;margin:20px auto"><h2>Crear cuenta</h2><p class="small muted">Tus datos de contacto no se muestran públicamente.</p><form onsubmit="registerDatoYaSecure(event)"><div class="field"><label>Nombre</label><input name="name" autocomplete="name" required></div><div class="field"><label>Correo</label><input name="email" type="email" autocomplete="email" required></div><div class="field"><label>Celular</label><input name="phone" type="tel" inputmode="tel" placeholder="+56912345678" autocomplete="tel"></div><div class="field"><label>Contraseña</label><input name="password" type="password" minlength="8" autocomplete="new-password" required><div class="small muted">Mínimo 8 caracteres.</div></div><div class="field"><label>Comuna</label><select name="comuna_id">${comunas.map(c=>`<option value="${c.id}">${e(c.name)}</option>`).join('')}</select></div><div class="field"><label>Tipo de cuenta</label><select name="role"><option value="cliente">Necesito servicios</option><option value="trabajador">Ofrezco servicios</option></select></div><label class="small" style="display:block;margin:12px 0"><input type="checkbox" name="terms" required> Acepto los <a href="#/terminos">Términos de Uso</a> y la <a href="#/privacidad">Política de Privacidad</a>.</label><label class="small" style="display:block;margin:12px 0"><input type="checkbox" name="location"> Autorizo el uso de ubicación cuando yo active funciones que la necesiten. Puedo revocar el permiso desde mi dispositivo.</label><button class="btn btn-primary btn-block">Crear cuenta</button></form></div>`;
  };

  window.registerDatoYaSecure=async function(ev){
    ev.preventDefault(); const f=ev.target;
    try{
      const created=await api('/auth/register',{method:'POST',body:{name:f.name.value,email:f.email.value,password:f.password.value,phone:f.phone.value||null,comuna_id:+f.comuna_id.value,role:f.role.value,accept_terms:!!f.terms.checked,accept_privacy:!!f.terms.checked}});
      await refreshMe();
      location.hash='#/seguridad'; route();
      toast(created.verification_email_sent?'Cuenta creada. Te enviamos un correo para verificarla.':'Cuenta creada. Desde Seguridad puedes enviar la verificación de correo.',created.verification_email_sent?'ok':'info');
    }catch(err){ toast(err.message,'err'); }
  };

  routes.recuperar=async function(){
    const cfg=await api('/auth/security-config').catch(()=>({}));
    view.innerHTML=`<div class="card" style="max-width:460px;margin:20px auto"><a href="#/login">← Volver</a><h2>Recuperar contraseña</h2><p>Escribe el correo de tu cuenta. Por seguridad, DatoYa no confirma si una dirección está registrada.</p>${!cfg.email_delivery_configured&&!cfg.test_mode?'<div class="lock-note">📧 El proveedor de correo todavía no está conectado en esta beta. La función ya está preparada, pero los correos reales no se enviarán hasta configurar el proveedor.</div>':''}<form onsubmit="requestDatoYaPasswordReset(event)"><div class="field"><label>Correo electrónico</label><input name="email" type="email" autocomplete="email" required></div><button class="btn btn-primary btn-block">Enviar instrucciones</button></form><div id="reset-result" style="margin-top:12px"></div></div>`;
  };
  window.requestDatoYaPasswordReset=async function(ev){
    ev.preventDefault(); const box=document.getElementById('reset-result');
    try{const r=await api('/auth/forgot-password',{method:'POST',body:{email:ev.target.email.value}}); box.innerHTML=`<div class="lock-note">${e(r.message)}</div>${r.test_token?`<a class="btn btn-outline btn-block" href="#/restablecer/${encodeURIComponent(r.test_token)}">Abrir enlace de prueba</a>`:''}`;}catch(err){toast(err.message,'err');}
  };

  routes.restablecer=async function(token){
    const legacyToken=new URLSearchParams((location.hash.split('?')[1]||'')).get('token')||'';
    const safe=decodeURIComponent(token||legacyToken||'');
    view.innerHTML=`<div class="card" style="max-width:460px;margin:20px auto"><h2>Nueva contraseña</h2>${safe?`<form onsubmit="completeDatoYaPasswordReset(event,'${e(safe)}')"><div class="field"><label>Nueva contraseña</label><input name="password" type="password" minlength="8" autocomplete="new-password" required></div><div class="field"><label>Repite la contraseña</label><input name="repeat" type="password" minlength="8" autocomplete="new-password" required></div><button class="btn btn-primary btn-block">Cambiar contraseña</button></form>`:'<div class="empty">El enlace de recuperación no es válido.</div>'}</div>`;
  };
  window.completeDatoYaPasswordReset=async function(ev,token){ev.preventDefault();const f=ev.target;if(f.password.value!==f.repeat.value)return toast('Las contraseñas no coinciden','err');try{const r=await api('/auth/reset-password',{method:'POST',body:{token,password:f.password.value}});toast(r.message||'Contraseña actualizada','ok');location.hash='#/login';route();}catch(err){toast(err.message,'err');}};

  routes['verificar-correo']=async function(token){
    const legacyToken=new URLSearchParams((location.hash.split('?')[1]||'')).get('token')||'';
    const safe=decodeURIComponent(token||legacyToken||'');
    view.innerHTML='<div class="card"><h2>Verificando correo…</h2></div>';
    if(!safe){view.innerHTML='<div class="empty">Enlace inválido.</div>';return;}
    try{await api('/auth/email-verification/confirm',{method:'POST',body:{token:safe}});await refreshMe();view.innerHTML='<div class="card"><h2>✅ Correo verificado</h2><p>Tu dirección de correo quedó confirmada.</p><a class="btn btn-primary" href="#/seguridad">Seguridad de la cuenta</a></div>';}catch(err){view.innerHTML=`<div class="card"><h2>No pudimos verificar el correo</h2><p>${e(err.message)}</p><a href="#/seguridad">Volver a seguridad</a></div>`;}
  };

  routes.seguridad=async function(){
    if(!ME){location.hash='#/login';return;}
    const [s,cfg]=await Promise.all([api('/auth/security-status'),api('/auth/security-config')]);
    const notif=('Notification' in window)?Notification.permission:'unsupported';
    view.innerHTML=`<h2 class="section-title">🔐 Seguridad de la cuenta</h2><div class="card"><div class="row between"><div><b>Correo</b><div class="small muted">${e(s.email)}</div></div>${statusPill(s.email_verified,'Verificado ✓','Sin verificar')}</div>${!s.email_verified?`<button class="btn btn-outline btn-block" style="margin-top:12px" onclick="requestDatoYaEmailVerification()">Enviar verificación</button>${!cfg.email_delivery_configured&&!cfg.test_mode?'<p class="small muted">El proveedor de correo real aún no está configurado.</p>':''}`:''}</div><div class="card"><div class="row between"><div><b>Celular</b><div class="small muted">${e(s.phone||'No informado')}</div></div>${statusPill(s.phone_verified,'Verificado ✓','Sin verificar')}</div><div class="field" style="margin-top:12px"><label>Actualizar celular</label><input id="security-phone" type="tel" value="${e(s.phone||'')}" placeholder="+56912345678"></div><button class="btn btn-outline btn-block" onclick="updateDatoYaPhone()">Guardar celular</button>${s.phone&&!s.phone_verified?`<button class="btn btn-primary btn-block" style="margin-top:8px" onclick="requestDatoYaPhoneCode()">Enviar código SMS</button><div id="phone-code-box"></div>`:''}${!cfg.sms_delivery_configured&&!cfg.test_mode?'<p class="small muted">El proveedor de SMS real aún no está configurado.</p>':''}</div><div class="card"><div class="row between"><div><b>Términos y privacidad</b><div class="small muted">Versiones vigentes de la beta</div></div>${statusPill(s.terms_current&&s.privacy_current,'Aceptados ✓','Revisar')}</div><div style="margin-top:10px"><a href="#/terminos">Términos</a> · <a href="#/privacidad">Privacidad</a></div>${!(s.terms_current&&s.privacy_current)?'<button class="btn btn-outline btn-block" style="margin-top:10px" onclick="acceptDatoYaCurrentLegal()">Aceptar versiones actuales</button>':''}</div><div class="card"><div class="row between"><div><b>Avisos del navegador</b><div class="small muted">Muestra avisos mientras DatoYa está abierto o en segundo plano.</div></div><span class="pill">${e(notif)}</span></div>${notif!=='granted'&&notif!=='unsupported'?'<button class="btn btn-outline btn-block" style="margin-top:10px" onclick="enableDatoYaBrowserNotifications()">Activar avisos</button>':''}</div><div class="card"><b>Sesiones y contraseña</b><p class="small muted">Al restablecer la contraseña se cierran todas las sesiones activas.</p><a class="btn btn-outline" href="#/recuperar">Cambiar mediante recuperación</a></div>`;
  };

  window.requestDatoYaEmailVerification=async function(){try{const r=await api('/auth/email-verification/request',{method:'POST'});if(r.already_verified)return toast('Tu correo ya está verificado','ok');if(r.test_token){openModal(`<h3>Prueba de verificación</h3><p>En producción este enlace llega por correo.</p><a class="btn btn-primary btn-block" href="#/verificar-correo/${encodeURIComponent(r.test_token)}" onclick="closeModal()">Verificar ahora</a>`);}else toast('Revisa tu correo para verificar la cuenta','ok');}catch(err){toast(err.message,'err');}};
  window.updateDatoYaPhone=async function(){try{await api('/auth/contact',{method:'PUT',body:{phone:document.getElementById('security-phone').value}});await refreshMe();routes.seguridad();toast('Celular actualizado','ok');}catch(err){toast(err.message,'err');}};
  window.requestDatoYaPhoneCode=async function(){try{const r=await api('/auth/phone-verification/request',{method:'POST'});const box=document.getElementById('phone-code-box');box.innerHTML=`<div class="field" style="margin-top:10px"><label>Código de 6 dígitos</label><input id="security-code" inputmode="numeric" maxlength="6" placeholder="000000"></div><button class="btn btn-green btn-block" onclick="confirmDatoYaPhoneCode()">Confirmar código</button>${r.test_code?`<p class="small muted">Código TEST: <b>${e(r.test_code)}</b></p>`:''}`;}catch(err){toast(err.message,'err');}};
  window.confirmDatoYaPhoneCode=async function(){try{await api('/auth/phone-verification/confirm',{method:'POST',body:{code:document.getElementById('security-code').value}});routes.seguridad();toast('Celular verificado','ok');}catch(err){toast(err.message,'err');}};
  window.acceptDatoYaCurrentLegal=async function(){try{await api('/legal/consent',{method:'POST',body:{accept_terms:true,accept_privacy:true,location_consent:false}});let back=null;try{back=sessionStorage.getItem('datoya_legal_return');sessionStorage.removeItem('datoya_legal_return');}catch(_){}toast('Términos y privacidad actualizados','ok');if(back&&back!=='#/seguridad'){location.hash=back;}else routes.seguridad();}catch(err){toast(err.message,'err');}};

  routes.terminos=async function(){
    const v=await api('/legal/versions').catch(()=>({terms_version:'beta'}));
    view.innerHTML=`<div class="card" style="max-width:760px;margin:0 auto"><h2>Términos de Uso de DatoYa</h2><p class="small muted">Versión ${e(v.terms_version)} · Borrador para beta cerrada. Debe revisarse jurídicamente antes del lanzamiento público.</p><h3>1. Qué hace DatoYa</h3><p>DatoYa conecta clientes con profesionales independientes. DatoYa no ejecuta directamente los trabajos publicados por los profesionales.</p><h3>2. Cuentas y uso responsable</h3><p>Cada persona debe entregar información verdadera, cuidar sus credenciales y usar la plataforma de forma lícita. DatoYa puede suspender cuentas por fraude, abuso o incumplimientos graves.</p><h3>3. Cotizaciones y trabajos</h3><p>Precio, alcance, materiales, fechas y condiciones del trabajo deben quedar claros antes de aceptar una cotización. Los cambios importantes deben registrarse dentro de DatoYa.</p><h3>4. Pago Protegido</h3><p>Durante la beta los flujos de pago pueden operar en modo TEST. Cuando Mercado Pago real sea habilitado, la pantalla de pago mostrará claramente el monto, comisión y estado. DatoYa no afirmará mantener dinero en escrow si el producto de pagos contratado no lo permite.</p><h3>5. Problemas y disputas</h3><p>El cliente puede informar un problema antes de aprobar un trabajo. DatoYa podrá revisar mensajes, estados y evidencias vinculadas al trabajo para gestionar la disputa.</p><h3>6. Reseñas y seguridad</h3><p>Las reseñas deben corresponder a experiencias reales. No se permite publicar datos sensibles de otras personas, amenazas, suplantaciones o contenido fraudulento.</p><h3>7. Cambios</h3><p>Si estos términos cambian de forma importante, DatoYa solicitará aceptar una nueva versión.</p><p><a href="#/privacidad">Ver Política de Privacidad →</a></p></div>`;
  };

  routes.privacidad=async function(){
    const v=await api('/legal/versions').catch(()=>({privacy_version:'beta'}));
    view.innerHTML=`<div class="card" style="max-width:760px;margin:0 auto"><h2>Política de Privacidad de DatoYa</h2><p class="small muted">Versión ${e(v.privacy_version)} · Borrador para beta cerrada. Debe revisarse jurídicamente antes del lanzamiento público.</p><h3>Datos que usamos</h3><p>Cuenta y contacto, comuna, perfil profesional, solicitudes, cotizaciones, mensajes, estados de trabajos, reseñas, reportes y datos técnicos necesarios para seguridad.</p><h3>Ubicación</h3><p>La ubicación se solicita solo en funciones que la necesitan. La información mostrada al cliente debe ser aproximada; la ubicación exacta se restringe a los flujos operativos autorizados del trabajo y administración según corresponda.</p><h3>Pagos</h3><p>Los pagos reales se procesarán mediante el proveedor configurado, actualmente previsto Mercado Pago. DatoYa no debe almacenar números completos de tarjetas.</p><h3>Verificación</h3><p>Los antecedentes de identidad deben limitarse a lo necesario para validar profesionales. Antes de aceptar documentos reales se requiere almacenamiento privado, control de acceso y política de eliminación.</p><h3>Seguridad</h3><p>DatoYa usa contraseñas cifradas mediante hash, cookies de sesión HTTP-only, límites de intentos y registros de eventos de seguridad. Ningún sistema es infalible y se mantendrán medidas de monitoreo y actualización.</p><h3>Derechos y contacto</h3><p>Antes del lanzamiento público DatoYa definirá el canal oficial para solicitudes de acceso, corrección o eliminación de datos y los plazos de retención aplicables.</p><p><a href="#/terminos">Ver Términos de Uso →</a></p></div>`;
  };

  window.enableDatoYaBrowserNotifications=async function(){if(!('Notification' in window))return toast('Este navegador no admite avisos','err');const p=await Notification.requestPermission();if(p==='granted'){localStorage.setItem('datoya_browser_notifs','1');startDatoYaNotificationPolling();toast('Avisos activados','ok');routes.seguridad();}else toast('No se otorgó permiso para avisos','err');};
  window.startDatoYaNotificationPolling=function(){if(!ME||!('Notification' in window)||Notification.permission!=='granted'||window.__datoyaNotifTimer)return;window.__datoyaNotifTimer=setInterval(async()=>{try{const r=await api('/notifications');const unread=(r.notifications||[]).filter(n=>!n.read_at);const last=Number(localStorage.getItem('datoya_last_notif_id')||0);const newest=unread.find(n=>Number(n.id)>last);if(newest){localStorage.setItem('datoya_last_notif_id',String(newest.id));const n=new Notification('DatoYa',{body:newest.text||'Tienes una nueva notificación'});n.onclick=()=>{window.focus();location.hash=(newest.link&&newest.link.startsWith('#/'))?newest.link:'#/notificaciones';};}}catch(_){}},60000);};
  setTimeout(()=>{if(localStorage.getItem('datoya_browser_notifs')==='1')startDatoYaNotificationPolling();},3000);

  // Accesos legales visibles en toda la SPA.
  if(!document.getElementById('datoya-legal-footer')){
    const footer=document.createElement('footer'); footer.id='datoya-legal-footer'; footer.className='small muted'; footer.style.cssText='text-align:center;padding:24px 12px 90px'; footer.innerHTML='<a href="#/terminos">Términos</a> · <a href="#/privacidad">Privacidad</a> · <a href="#/seguridad">Seguridad</a>'; document.body.appendChild(footer);
  }
})();
