// DatoYa 2.0 — centro administrativo de disputas.
(function(){
 if(typeof routes==='undefined'||!routes.admin)return;
 const previous=routes.admin;
 const safe=v=>typeof esc==='function'?esc(v):String(v??'');
 const statusName=s=>({abierta:'Abierta',resuelta:'Resuelta'}[s]||String(s||''));
 async function renderDisputes(){
  if(!ME||ME.role!=='admin'){location.hash='#/login';return;}
  try{const {disputes=[]}=await api('/admin/job-disputes'),open=disputes.filter(d=>d.status==='abierta'),closed=disputes.filter(d=>d.status==='resuelta');view.innerHTML='<h2 class="section-title">⚖️ Disputas y revisión</h2><div class="lock-note"><b>'+open.length+' disputa(s) requieren revisión</b><br><span class="small muted">Revisa el motivo y la bitácora del trabajo antes de resolver. Una alerta no demuestra fraude ni incumplimiento por sí sola.</span></div><div style="margin-top:14px">'+(disputes.length?disputes.map(d=>'<div class="card"><div class="row between" style="gap:10px"><div><b>'+safe(d.title||('Trabajo #'+d.job_id))+'</b><div class="small muted">Caso #'+Number(d.id)+' · '+safe(d.opened_by_name||'Usuario')+' · '+safe(typeof fmtHora==='function'?fmtHora(d.created_at):d.created_at)+'</div></div><span class="status-tag">'+safe(statusName(d.status))+'</span></div><p><b>Motivo:</b> '+safe(d.reason)+'</p>'+(d.details?'<p class="small">'+safe(d.details)+'</p>':'')+(d.resolution?'<div class="lock-note"><b>Resolución:</b> '+safe(d.resolution)+'</div>':'')+'<div class="row" style="gap:7px;flex-wrap:wrap;margin-top:10px"><button class="btn btn-outline btn-sm" onclick="openAdminDisputeTrust('+Number(d.job_id)+')">📋 Ver bitácora</button>'+(d.status==='abierta'?'<button class="btn btn-primary btn-sm" onclick="openAdminResolveDispute('+Number(d.id)+')">Resolver caso</button>':'')+'</div></div>').join(''):'<div class="empty">No hay disputas registradas.</div>')+'</div>'+(closed.length?'<div class="small muted" style="margin-top:8px">'+closed.length+' caso(s) resuelto(s) en el historial.</div>':'');}catch(e){view.innerHTML='<div class="empty">'+safe(e.message||'No se pudieron cargar las disputas')+'</div>';}
 }
 routes.admin=async function(tab='dashboard'){if(tab==='disputas')return renderDisputes();return previous.apply(this,arguments);};
 // Expone el renderer para que otros decoradores de navegación puedan volver a aplicarlo sin perder esta pantalla.
 window.renderDatoYaAdminDisputes=renderDisputes;
 window.openAdminDisputeTrust=async function(jobId){try{const t=(await api('/jobs/'+jobId+'/trust')).trust||{},h=t.history||[],e=t.evidence||[],c=t.confirmations||[];openModal('<h3>📋 Bitácora del trabajo</h3><div class="lock-note">'+(t.meeting?'✅ Encuentro verificado':'○ Encuentro no verificado')+'<br>📷 '+e.length+' evidencia(s)<br>✓ '+c.length+'/2 confirmaciones de término</div><h4>Historial</h4>'+(h.length?h.map(x=>'<div class="small" style="padding:7px 0;border-bottom:1px solid #eee"><b>'+safe(String(x.status||'').replaceAll('_',' '))+'</b> · '+safe(typeof fmtHora==='function'?fmtHora(x.created_at):x.created_at)+'</div>').join(''):'<p class="small muted">Sin movimientos.</p>')+(e.length?'<h4>Evidencias</h4>'+e.map(x=>'<button class="btn btn-outline btn-sm" style="margin:3px" onclick="showAdminDisputeEvidence('+jobId+','+Number(x.id)+')">📷 '+(x.phase==='antes'?'Antes':'Después')+'</button>').join(''):''));}catch(e){toast(e.message,'err');}};
 window.showAdminDisputeEvidence=async function(jobId,eid){try{const x=(await api('/jobs/'+jobId+'/evidence/'+eid)).evidence;openModal('<h3>📷 Evidencia</h3><img src="'+safe(x.image_data||'')+'" alt="Evidencia del trabajo" style="width:100%;border-radius:12px"><p>'+safe(x.note||'Sin nota')+'</p>');}catch(e){toast(e.message,'err');}};
 window.openAdminResolveDispute=function(id){openModal('<h3>⚖️ Resolver disputa</h3><p class="small muted">Elige el resultado solo después de revisar los antecedentes. La resolución quedará registrada.</p><div class="field"><label>Resultado</label><select id="adm-dp-outcome"><option value="reanudar">Reanudar trabajo</option><option value="cancelar">Cancelar trabajo</option><option value="finalizar">Dar trabajo por finalizado</option></select></div><div class="field"><label>Fundamento de la decisión</label><textarea id="adm-dp-resolution" rows="5" maxlength="1500" placeholder="Explica de forma neutral qué se revisó y qué se decidió"></textarea></div><button class="btn btn-primary btn-block" onclick="resolveAdminDispute('+id+')">Guardar resolución</button>');};
 window.resolveAdminDispute=async function(id){const resolution=document.getElementById('adm-dp-resolution')?.value?.trim(),outcome=document.getElementById('adm-dp-outcome')?.value;if(!resolution||resolution.length<10)return toast('Escribe un fundamento claro para la resolución','err');if(!confirm('¿Guardar esta resolución? Esta acción cambiará el estado del trabajo.'))return;try{await api('/admin/job-disputes/'+id+'/resolve',{method:'POST',body:{resolution,outcome}});closeModal();toast('Disputa resuelta y registrada','ok');route();}catch(e){toast(e.message||'No se pudo resolver','err');}};
})();