/* DatoYa — SPA mobile-first (vanilla JS) */
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], view=$('#view');
let ME=null,CATS=[],COMUNAS=[],CONFIG=null;
const fmtCLP=n=>'$'+Number(n||0).toLocaleString('es-CL');
const fmtFecha=iso=>iso?new Date(iso.replace(' ','T')+(iso.includes('Z')?'':'Z')).toLocaleDateString('es-CL',{day:'numeric',month:'short'}):'';
const fmtHora=iso=>iso?new Date(iso.replace(' ','T')+(iso.includes('Z')?'':'Z')).toLocaleString('es-CL',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}):'';
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const estrellas=(r,c)=>`<span class="stars">★</span> <b>${Number(r).toFixed(1)}</b>${c!==undefined?` <span class="muted small">(${c})</span>`:''}`;
const estadoTxt=s=>({disponible:'🟢 Disponible',ocupado:'🟡 Ocupado',no_disponible:'⚪ No disponible'}[s]||s);
const demoTag=d=>d?'<span class="demo-tag">DEMO</span>':'';
const avatar=(name,color,status)=>`<div class="avatar" style="background:${color||'#1D4ED8'}">${esc((name||'?')[0].toUpperCase())}${status?`<i class="st st-${status}"></i>`:''}</div>`;
async function api(url,opts={}){if(opts.body&&typeof opts.body!=='string')opts.body=JSON.stringify(opts.body);opts.headers={...(opts.headers||{}),'Content-Type':'application/json','Accept':'application/json'};const r=await fetch('/api'+url,opts),data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(data.error||'Error '+r.status);e.status=r.status;throw e;}return data;}
function toast(msg,type=''){const t=$('#toast');if(!t)return;t.textContent=msg;t.className=type;t.classList.remove('hidden');clearTimeout(t._to);t._to=setTimeout(()=>t.classList.add('hidden'),3200);}
function openModal(html){$('#modal-card').innerHTML=html+'<button class="btn btn-ghost btn-block" style="margin-top:14px" onclick="closeModal()">Cerrar</button>';$('#modal').classList.remove('hidden');}
function closeModal(){$('#modal').classList.add('hidden');}
$('#modal')?.addEventListener('click',e=>{if(e.target.id==='modal')closeModal();});
async function refreshMe(){try{ME=(await api('/auth/me')).user;}catch{ME=null;}renderAuthArea();}
function renderAuthArea(){const area=$('#auth-area');if(!area)return;if(!ME){area.innerHTML='<a href="#/login">Ingresar</a> <a href="#/registro" class="btn btn-primary btn-sm">Crear cuenta</a>';$('#bottomnav')?.classList.add('hidden');}else{const adminLink=ME.role==='admin'?'<a href="#/admin">Panel</a>':'';area.innerHTML=`${adminLink}<a href="#/perfil" style="font-weight:700;color:var(--azul)">${esc(ME.name.split(' ')[0])}</a><a href="#" onclick="logout();return false">Salir</a>`;$('#bottomnav')?.classList.remove('hidden');$('#msg-badge')?.classList.toggle('hidden',!ME.unread_notifications);}}
async function logout(){await api('/auth/logout',{method:'POST'});ME=null;location.hash='#/';route();}
const routes={'':renderHome,'buscar':renderSearch,'trabajador':renderWorkerProfile,'solicitar':renderNewRequest,'solicitudes':renderMyRequests,'solicitud':renderRequestDetail,'bandeja':renderWorkerFeed,'mensajes':renderChats,'chat':renderChat,'trabajos':renderJobs,'perfil':renderProfile,'login':renderLogin,'registro':renderRegister,'admin':renderAdmin,'trabaja':renderTrabaja,'notificaciones':renderNotifications,'pro':renderPro};
async function route(){const[path,...params]=location.hash.replace(/^#\//,'').split('/'),fn=routes[path]??renderHome;closeModal();window.scrollTo(0,0);$$('#bottomnav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#/'+path||(path===''&&a.dataset.nav==='inicio')));try{await fn(...params);}catch(e){if(e.status===401){location.hash='#/login';return;}view.innerHTML=`<div class="empty"><b>😕</b>${esc(e.message)}</div>`;}}
window.addEventListener('hashchange',route);
async function renderHome(){const{categories}=await api('/categories');CATS=categories;const{comunas}=await api('/comunas?region_id=16');const feat=await api('/workers?featured=1');const destacados=feat.workers.length?feat.workers:(await api('/workers')).workers.slice(0,4);view.innerHTML=`<div class="hero"><h1>Encuentra a la persona indicada<br>para tu trabajo.</h1><p>Gasfíter, electricista, pintor y más — cerca de ti, verificados y con reseñas reales.</p><form class="searchbox" onsubmit="event.preventDefault();location.hash='#/buscar?q='+encodeURIComponent(this.q.value)+'&comuna='+this.comuna.value"><input name="q" placeholder="¿Qué servicio necesitas?"><select name="comuna"><option value="">¿Dónde? — Todas las comunas</option>${comunas.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><button class="btn btn-accent">🔍 Buscar</button></form></div><h2 class="section-title">Servicios cerca de ti</h2><div class="cat-grid">${categories.slice(0,9).map(c=>`<a class="cat-item" href="#/buscar?cat=${c.id}"><span>${c.icon}</span>${esc(c.name)}</a>`).join('')}<a class="cat-item" href="#/buscar"><span>➕</span>Ver todos</a></div><h2 class="section-title">Trabajadores destacados</h2><div class="cards">${destacados.map(workerCard).join('')}</div>`;}
function workerCard(w){return `<div class="wcard"><div class="wcard-top">${avatar(w.name,w.avatar_color,w.status)}<div class="wcard-info"><h3>${esc(w.name)} ${demoTag(1)}</h3><div class="oficio">${esc(w.oficio)}</div><div class="wmeta"><span>${estrellas(w.rating_avg,w.rating_count)}</span><span>🛠️ ${w.jobs_completed} trabajos</span><span>📍 ${esc(w.comuna||'')}</span></div></div></div><div class="wcard-actions"><a class="btn btn-outline btn-sm" href="#/trabajador/${w.id}">Ver perfil</a><button class="btn btn-primary btn-sm" onclick="solicitarDirecto(${w.id})">Solicitar</button></div></div>`;}
async function renderSearch(){const q=new URLSearchParams(location.hash.split('?')[1]||''),p=new URLSearchParams();if(q.get('q'))p.set('q',q.get('q'));if(q.get('cat'))p.set('category_id',q.get('cat'));if(q.get('comuna'))p.set('comuna_id',q.get('comuna'));if(q.get('verif'))p.set('verified','1');const{workers}=await api('/workers?'+p);view.innerHTML=`<h2 class="section-title">Buscar servicios</h2><div class="card"><form onsubmit="doSearch(event)"><div class="field"><input name="q" value="${esc(q.get('q')||'')}" placeholder="¿Qué servicio necesitas?"></div><button class="btn btn-primary btn-block">🔍 Buscar</button></form></div><div class="cards">${workers.length?workers.map(workerCard).join(''):'<div class="empty">No encontramos trabajadores.</div>'}</div>`;}
function doSearch(e){e.preventDefault();const f=e.target,p=new URLSearchParams();if(f.q.value)p.set('q',f.q.value);location.hash='#/buscar?'+p;route();}
async function solicitarDirecto(workerId){if(!ME){location.hash='#/login';return;}if(ME.role!=='cliente'){toast('Inicia sesión como cliente para solicitar','err');return;}const{id}=await api('/conversations/start',{method:'POST',body:{worker_id:workerId}});location.hash='#/chat/'+id;}
async function renderWorkerProfile(id){const{worker:w}=await api('/workers/'+id);view.innerHTML=`<a href="#/buscar" class="small">← Volver</a><div class="profile-head"><div class="row">${avatar(w.name,w.avatar_color,w.status)}<div><h2>${esc(w.name)}</h2><div class="oficio">${esc(w.oficio)}</div><div class="small muted">📍 ${esc(w.comuna||'')}</div></div></div><div class="badges">${w.verified_identity?'<span class="badge-v">✓ Identidad verificada</span>':''}</div><p>${esc(w.description||'')}</p><div class="wcard-actions"><button class="btn btn-primary" onclick="solicitarDirecto(${w.id})">Solicitar servicio</button></div></div>`;}
async function renderLogin(){view.innerHTML=`<div class="card" style="max-width:440px;margin:20px auto"><h2>Ingresar a DatoYa</h2><form onsubmit="doLogin(event)"><div class="field"><label>Correo electrónico</label><input name="email" type="email" required></div><div class="field"><label>Contraseña</label><input name="password" type="password" required></div><button class="btn btn-primary btn-block">Ingresar</button></form><div class="lock-note" style="margin-top:14px"><b>Cuentas DEMO</b> (contraseña: <b>demo1234</b>):<br>Cliente: cliente@demo.cl<br>Trabajador: trabajador@demo.cl<br>Admin: admin@demo.cl</div></div>`;}
async function doLogin(e){e.preventDefault();const f=e.target;try{await api('/auth/login',{method:'POST',body:{email:f.email.value,password:f.password.value}});await refreshMe();location.hash='#/';route();toast('¡Hola de nuevo! 👋','ok');}catch(err){toast(err.message,'err');}}
async function quickLogin(email){try{await api('/auth/login',{method:'POST',body:{email,password:'demo1234'}});await refreshMe();location.hash='#/';route();}catch(e){toast(e.message,'err');}}
async function renderRegister(){const{comunas}=await api('/comunas');view.innerHTML=`<div class="card"><h2>Crear cuenta</h2><form onsubmit="doRegister(event)"><div class="field"><label>Nombre</label><input name="name" required></div><div class="field"><label>Correo</label><input name="email" type="email" required></div><div class="field"><label>Contraseña</label><input name="password" type="password" minlength="6" required></div><div class="field"><label>Comuna</label><select name="comuna_id">${comunas.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select></div><div class="field"><label>Rol</label><select name="role"><option value="cliente">Necesito servicios</option><option value="trabajador">Ofrezco servicios</option></select></div><button class="btn btn-primary btn-block">Crear cuenta</button></form></div>`;}
async function doRegister(e){e.preventDefault();const f=e.target;try{await api('/auth/register',{method:'POST',body:{name:f.name.value,email:f.email.value,password:f.password.value,comuna_id:+f.comuna_id.value,role:f.role.value}});await refreshMe();location.hash='#/';route();}catch(err){toast(err.message,'err');}}
let wiz={};
async function renderNewRequest(){if(!ME||ME.role!=='cliente'){location.hash='#/login';return;}wiz={step:1};wiz.comunas=(await api('/comunas')).comunas;if(!CATS.length)CATS=(await api('/categories')).categories;drawWizard();}
function drawWizard(){let body;if(wiz.step===1)body=`<h2>¿Qué necesitas?</h2><div class="cat-grid">${CATS.map(c=>`<button class="cat-item" onclick="wizSet('category_id',${c.id});wizSet('catName','${esc(c.name)}')"><span>${c.icon}</span>${esc(c.name)}</button>`).join('')}</div>`;else if(wiz.step===2)body=`<h2>Describe el problema</h2><div class="field"><input id="w-title" placeholder="Título"></div><div class="field"><textarea id="w-desc" rows="4" placeholder="Detalle"></textarea></div><button class="btn btn-primary btn-block" onclick="wizNext(['title','description'])">Continuar</button>`;else if(wiz.step===3)body=`<h2>¿Dónde?</h2><select id="w-comuna">${wiz.comunas.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><div class="field"><input id="w-address" placeholder="Dirección"></div><button class="btn btn-primary btn-block" onclick="wizNext(['comuna_id','address_detail'])">Continuar</button>`;else body=`<h2>Confirmar solicitud</h2><p><b>${esc(wiz.title)}</b></p><p>${esc(wiz.description)}</p><button class="btn btn-green btn-block" onclick="wizSubmit()">Publicar solicitud</button>`;view.innerHTML=`<div class="card">${body}</div>`;}
function wizSet(k,v){wiz[k]=v;if(k==='category_id'){wiz.step=2;drawWizard();}}
function wizBack(){wiz.step--;drawWizard();}
function wizNext(fields=[]){for(const f of fields){const map={comuna_id:'comuna',address_detail:'address',title:'title',description:'desc'};const el=$('#w-'+map[f]);if(el)wiz[f]=f==='comuna_id'?+el.value:el.value.trim();}if(fields.includes('title')&&!wiz.title)return toast('Escribe un título','err');wiz.step++;drawWizard();}
async function wizSubmit(){try{const r=await api('/requests',{method:'POST',body:{category_id:wiz.category_id,title:wiz.title,description:wiz.description,comuna_id:wiz.comuna_id,address_detail:wiz.address_detail}});view.innerHTML=`<div class="card"><h2>¡Solicitud publicada!</h2><p>${r.notificados||0} trabajador(es) notificados.</p><a href="#/solicitudes" class="btn btn-primary">Ver solicitudes</a></div>`;}catch(e){toast(e.message,'err');}}
async function renderMyRequests(){if(!ME){location.hash='#/login';return;}if(ME.role==='trabajador')return renderWorkerFeed();const{requests}=await api('/requests/mine');view.innerHTML=`<h2 class="section-title">Mis solicitudes</h2>${requests.map(r=>`<a class="card row between" href="#/solicitud/${r.id}"><div><b>${r.icon} ${esc(r.title)}</b><div class="small muted">${esc(r.category)} · ${esc(r.comuna||'')}</div></div><span class="status-tag">${r.status}</span></a>`).join('')||'<div class="empty">Aún no tienes solicitudes.</div>'}`;}
async function renderRequestDetail(id){const{request:r,quotes,is_owner}=await api('/requests/'+id);view.innerHTML=`<a href="#/${is_owner?'solicitudes':'bandeja'}">← Volver</a><div class="card"><h2>${r.icon} ${esc(r.title)}</h2><p>${esc(r.description)}</p><div class="small muted">${esc(r.category)} · ${esc(r.comuna||'')}</div></div><h3 class="section-title">Cotizaciones (${quotes.length})</h3>${quotes.map(q=>`<div class="quote-card"><b>${esc(q.worker_name)}</b><span>${fmtCLP(q.price)}</span><p>${esc(q.description||'')}</p>${is_owner&&q.status==='pendiente'?`<button class="btn btn-green" onclick="acceptQuote(${q.id})">Elegir</button>`:''}</div>`).join('')}`;}
async function sendQuote(e,requestId){e.preventDefault();const f=e.target;try{await api('/quotes',{method:'POST',body:{request_id:requestId,price:+f.price.value,description:f.description.value}});toast('¡Cotización enviada!','ok');route();}catch(err){toast(err.message,'err');}}
async function acceptQuote(id){if(!confirm('¿Confirmas elegir esta cotización?'))return;try{await api(`/quotes/${id}/accept`,{method:'POST'});location.hash='#/trabajos';route();}catch(e){toast(e.message,'err');}}
async function renderWorkerFeed(){const{requests}=await api('/requests/feed');view.innerHTML=`<h2 class="section-title">Solicitudes en tu zona</h2>${requests.map(r=>`<a class="card row between" href="#/solicitud/${r.id}"><div><b>${r.icon} ${esc(r.title)}</b><div class="small muted">${esc(r.category)} · ${esc(r.comuna||'')}</div></div><span class="pill">${r.quotes_count} cotiz.</span></a>`).join('')||'<div class="empty">No hay solicitudes nuevas.</div>'}`;}
async function renderChats(){if(!ME){location.hash='#/login';return;}const{conversations}=await api('/conversations');view.innerHTML=`<h2 class="section-title">Mensajes</h2><div class="chat-list">${conversations.map(c=>`<a href="#/chat/${c.id}">${avatar(c.other_name,'#1D4ED8')}<div style="flex:1;min-width:0"><div class="row between"><b>${esc(c.other_name)}</b><span class="small muted">${fmtHora(c.last_at||c.created_at)}</span></div><div class="small muted" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis">${c.title?'📋 '+esc(c.title)+' · ':''}${esc(c.last_msg||'Inicia la conversación')}</div></div>${c.unread?`<span class="badge" style="position:static">${c.unread}</span>`:''}</a>`).join('')||'<div class="empty"><b>💬</b>No tienes conversaciones aún.</div>'}</div>`;}
async function renderChat(id){if(!ME){location.hash='#/login';return;}const{messages,locked,me}=await api(`/conversations/${id}/messages`);view.innerHTML=`<a href="#/mensajes" class="small">← Mensajes</a>${locked?'<div class="lock-note" style="margin-top:10px">🔒 <b>Protección anti-estafas:</b> hasta que se acepte un trabajo, no puedes compartir teléfonos, correos ni redes sociales por el chat.</div>':''}<div class="chat-window" style="margin-top:8px"><div class="chat-msgs" id="msgs">${messages.map(m=>`<div class="msg ${m.sender_id===me?'mine':'theirs'}">${esc(m.body)}<span class="time">${fmtHora(m.created_at)} ${m.sender_id===me&&m.read_at?'· ✓✓ leído':''}</span>${m.blocked?'<span class="warn">⚠️ Se ocultó información de contacto por seguridad</span>':''}</div>`).join('')}</div><form class="chat-input" onsubmit="sendMsg(event,${id})"><input name="body" placeholder="Escribe un mensaje..." autocomplete="off" required><button class="btn btn-primary">➤</button></form></div>`;const box=$('#msgs');if(box)box.scrollTop=box.scrollHeight;}
async function sendMsg(e,id){e.preventDefault();const f=e.target,body=f.body.value.trim();if(!body)return;try{const r=await api(`/conversations/${id}/messages`,{method:'POST',body:{body}});f.body.value='';if(r.warning)toast(r.warning,'err');await renderChat(id);}catch(err){toast(err.message,'err');}}
async function renderJobs(){if(!ME){location.hash='#/login';return;}const{jobs}=await api('/jobs');view.innerHTML=`<h2 class="section-title">Trabajos</h2>${jobs.map(j=>`<div class="card"><div class="row between"><b>${esc(j.title)}</b><span class="status-tag">${j.status}</span></div><div class="small muted">👤 ${esc(j.other_name||'')} · 💰 ${fmtCLP(j.price)}</div>${ME.role==='trabajador'&&j.status==='TRABAJADOR_SELECCIONADO'?`<button class="btn btn-primary" onclick="jobStatus(${j.id},'CONFIRMADO')">✓ Confirmar</button>`:''}${ME.role==='trabajador'&&j.status==='CONFIRMADO'?`<button class="btn btn-primary" onclick="jobStatus(${j.id},'EN_PROCESO')">▶ Iniciar</button>`:''}${ME.role==='cliente'&&['CONFIRMADO','EN_PROCESO','TRABAJADOR_SELECCIONADO'].includes(j.status)?`<button class="btn btn-green" onclick="jobStatus(${j.id},'FINALIZADO')">✅ Terminar</button>`:''}</div>`).join('')||'<div class="empty">Aún no tienes trabajos.</div>`;}
async function jobStatus(id,status){if((status==='FINALIZADO'||status==='CANCELADO')&&!confirm('¿Confirmas esta acción?'))return;try{await api(`/jobs/${id}/status`,{method:'POST',body:{status}});toast('Estado actualizado','ok');route();}catch(e){toast(e.message,'err');}}
async function renderProfile(){if(!ME){location.hash='#/login';return;}view.innerHTML=`<div class="profile-head"><div class="row">${avatar(ME.name,'#1D4ED8')}<div><h2>${esc(ME.name)}</h2><div class="small muted">${esc(ME.email)} · 📍 ${esc(ME.comuna||'Sin comuna')}</div></div></div><div class="card"><a href="#/solicitudes">📋 Mis solicitudes</a><br><a href="#/trabajos">🛠️ Mis trabajos</a><br><a href="#/mensajes">💬 Mensajes</a><br><a href="#/notificaciones">🔔 Notificaciones</a></div></div>`;}
async function renderTrabaja(){view.innerHTML='<div class="hero"><h1>Consigue nuevos clientes con DatoYa.</h1><p>Crea tu perfil gratis y recibe solicitudes de tu zona.</p><a href="#/registro" class="btn btn-white">Quiero ofrecer mis servicios</a></div>';}
async function renderPro(){view.innerHTML='<div class="card"><b style="font-size:46px">⭐</b><h2>DatoYa PRO</h2><p>Destaca tu perfil y consigue más clientes.</p></div>';}
async function renderNotifications(){if(!ME){location.hash='#/login';return;}const{notifications}=await api('/notifications');view.innerHTML=`<h2 class="section-title">Notificaciones</h2>${notifications.map(n=>`<div class="notif ${n.read_at?'':'unread'}">${esc(n.text)}<div class="small muted">${fmtHora(n.created_at)}</div></div>`).join('')||'<div class="empty">No tienes notificaciones.</div>'}`;}
async function renderAdmin(tab='dashboard'){if(!ME||ME.role!=='admin'){view.innerHTML='<div class="empty"><b>🛡️</b>Acceso solo para administradores.</div>';return;}const{verifications}=await api('/admin/verifications').catch(()=>({verifications:[]}));view.innerHTML=`<h2 class="section-title">🛡️ Panel de administración</h2><div class="tabs">${[['dashboard','📊 Dashboard'],['verificaciones','✓ Verificaciones']].map(([k,t])=>`<button class="${k===tab?'on':''}" onclick="location.hash='#/admin/${k}'">${t}</button>`).join('')}</div>${tab==='verificaciones'?verifications.map(v=>`<div class="card row between"><div><b>${esc(v.name)}</b> — ${esc(v.oficio)}</div><span class="status-tag">${v.status}</span></div>`).join(''):'<div class="card">Panel de administración disponible.</div>'}`;}
async function renderAdminLegacy(){return renderAdmin();}
async function resolveVerification(id,action){try{await api(`/admin/verifications/${id}`,{method:'POST',body:{action}});toast('Verificación actualizada','ok');route();}catch(e){toast(e.message,'err');}}
(async function init(){await refreshMe();if(!location.hash)location.hash='#/';await route();})();
