// DatoYa beta privada: funciones comerciales nuevas, aisladas del marketplace legacy.
const fs=require('fs'),path=require('path');
const {db}=require('./db');
db.exec(`
CREATE TABLE IF NOT EXISTS market_search_events(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,normalized_term TEXT NOT NULL,raw_term TEXT,category_id INTEGER,comuna_id INTEGER,latitude REAL,longitude REAL,radius_km INTEGER NOT NULL DEFAULT 5,result_count INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_market_search_zone_time ON market_search_events(comuna_id,created_at);
CREATE TABLE IF NOT EXISTS market_alerts(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,normalized_term TEXT NOT NULL,raw_term TEXT NOT NULL,category_id INTEGER,comuna_id INTEGER,latitude REAL,longitude REAL,radius_km INTEGER NOT NULL DEFAULT 5,status TEXT NOT NULL DEFAULT 'active',starts_at TEXT NOT NULL DEFAULT (datetime('now')),expires_at TEXT NOT NULL,matched_at TEXT,cancelled_at TEXT,created_at TEXT NOT NULL DEFAULT (datetime('now')),updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_market_alerts_active ON market_alerts(status,expires_at,normalized_term);
CREATE TABLE IF NOT EXISTS wanted_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,title TEXT NOT NULL,normalized_term TEXT NOT NULL,category_id INTEGER,description TEXT NOT NULL,needed_at TEXT,budget INTEGER,comuna_id INTEGER,latitude REAL,longitude REAL,radius_km INTEGER NOT NULL DEFAULT 5,status TEXT NOT NULL DEFAULT 'active',expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')),updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS idx_wanted_active_zone ON wanted_requests(status,comuna_id,expires_at);
CREATE TABLE IF NOT EXISTS wanted_responses(id INTEGER PRIMARY KEY AUTOINCREMENT,request_id INTEGER NOT NULL REFERENCES wanted_requests(id) ON DELETE CASCADE,business_id INTEGER NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,responder_user_id INTEGER NOT NULL REFERENCES users(id),message TEXT NOT NULL,product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,reference_price INTEGER,availability TEXT,created_at TEXT NOT NULL DEFAULT (datetime('now')),updated_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(request_id,business_id));
CREATE TABLE IF NOT EXISTS commerce_favorites(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,target_type TEXT NOT NULL,target_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(user_id,target_type,target_id));
CREATE TABLE IF NOT EXISTS followed_businesses(user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,business_id INTEGER NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,notify_promotions INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT (datetime('now')),PRIMARY KEY(user_id,business_id));
`);
const serverPath=path.join(__dirname,'server.js');let source=fs.readFileSync(serverPath,'utf8');
if(!source.includes('DATOYA PRIVATE BETA CORE V1')){
const injection=String.raw`
// ============ DATOYA PRIVATE BETA CORE V1 ============
function __dyNorm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9ñ ]/g,' ').replace(/\s+/g,' ').trim().slice(0,100);}
function __dyOwnedBusiness(uid,id){return db.prepare('SELECT * FROM businesses WHERE id=? AND owner_user_id=?').get(Number(id),uid);}
function __dyHasImpulse(id){return !!db.prepare("SELECT id FROM business_impulse_memberships WHERE business_id=? AND status='active' AND expires_at>? LIMIT 1").get(Number(id),new Date().toISOString());}
function __dyExpire(){const now=new Date().toISOString();db.prepare("UPDATE market_alerts SET status='expired',updated_at=? WHERE status='active' AND expires_at<=?").run(now,now);db.prepare("UPDATE wanted_requests SET status='expired',updated_at=? WHERE status='active' AND expires_at<=?").run(now,now);}
function __dyAllowed(v,list,def){const n=Number(v);return list.includes(n)?n:def;}
function __dyOptionalMarketUser(req){const token=req.cookies&&req.cookies.datoya_token;if(!token)return null;const u=db.prepare("SELECT u.id,u.role,u.is_active,m.account_type FROM sessions s JOIN users u ON u.id=s.user_id LEFT JOIN market_account_types m ON m.user_id=u.id WHERE s.token=? AND s.expires_at>datetime('now')").get(token);return u&&u.is_active?u:null;}
const __dySearchDedupe=new Map();
function __dySearchVisitor(v){return String(v||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,64);}
function __dySearchDedupeKey(req,user,x,term){const visitor=__dySearchVisitor(x.visitor_id),identity=user&&user.id?'u:'+user.id:visitor?'v:'+visitor:'anon';return identity+'|'+term+'|'+(Number(x.comuna_id)||0)+'|'+(Number(x.category_id)||0);}
app.get('/api/notifications/summary',auth,(req,res)=>{const rows=db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 60').all(req.user.id);res.json({unread:rows.filter(x=>!x.read_at).length,notifications:rows});});
app.put('/api/notifications/:id/read',auth,(req,res)=>{const r=db.prepare("UPDATE notifications SET read_at=COALESCE(read_at,datetime('now')) WHERE id=? AND user_id=?").run(Number(req.params.id),req.user.id);if(!r.changes)return res.status(404).json({error:'Notificación no encontrada'});res.json({ok:true});});
app.put('/api/notifications/read-all',auth,(req,res)=>{db.prepare("UPDATE notifications SET read_at=datetime('now') WHERE user_id=? AND read_at IS NULL").run(req.user.id);res.json({ok:true});});
app.post('/api/market/search-events',(req,res)=>{const x=req.body||{},term=__dyNorm(x.term);if(term.length<2)return res.status(400).json({error:'Búsqueda demasiado corta'});const user=__dyOptionalMarketUser(req);if(user&&(user.role==='admin'||user.account_type==='admin'||user.account_type==='business'))return res.json({ok:true,ignored:true,reason:'non_customer_account'});const now=Date.now(),key=__dySearchDedupeKey(req,user,x,term),last=__dySearchDedupe.get(key)||0;if(now-last<300000)return res.json({ok:true,deduped:true});__dySearchDedupe.set(key,now);if(__dySearchDedupe.size>5000){for(const [k,t] of __dySearchDedupe){if(now-t>900000)__dySearchDedupe.delete(k);if(__dySearchDedupe.size<=3500)break;}}const comunaId=Number(x.comuna_id)||null,categoryId=Number(x.category_id)||null,resultCount=Math.max(0,Math.min(10000,Number(x.result_count)||0));db.prepare('INSERT INTO market_search_events(user_id,normalized_term,raw_term,category_id,comuna_id,latitude,longitude,radius_km,result_count) VALUES(?,?,?,?,?,?,?,?,?)').run(user&&user.id?user.id:null,term,String(x.term||'').trim().slice(0,100),categoryId,comunaId,null,null,__dyAllowed(x.radius_km,[1,3,5,10],5),resultCount);res.status(201).json({ok:true,tracked:true,scope:comunaId?'local':'unlocated'});});
app.get('/api/businesses/:id/local-pulse',auth,(req,res)=>{const b=__dyOwnedBusiness(req.user.id,req.params.id);if(!b)return res.status(404).json({error:'Negocio no encontrado'});if(!__dyHasImpulse(b.id))return res.status(403).json({error:'🔒 Incluido con DatoYa Impulso',code:'IMPULSO_PLAN_REQUIRED'});const days=__dyAllowed(req.query.days,[7,30,90],7),since=new Date(Date.now()-days*86400000).toISOString(),previous=new Date(Date.now()-days*2*86400000).toISOString(),zone=Number(b.comuna_id)||0;const total=db.prepare('SELECT COUNT(*) c FROM market_search_events WHERE comuna_id=? AND created_at>=?').get(zone,since).c,prev=db.prepare('SELECT COUNT(*) c FROM market_search_events WHERE comuna_id=? AND created_at>=? AND created_at<?').get(zone,previous,since).c,terms=db.prepare('SELECT normalized_term AS term,COUNT(*) searches,SUM(CASE WHEN result_count=0 THEN 1 ELSE 0 END) no_results FROM market_search_events WHERE comuna_id=? AND created_at>=? GROUP BY normalized_term ORDER BY searches DESC LIMIT 15').all(zone,since),categories=db.prepare('SELECT category_id,COUNT(*) searches FROM market_search_events WHERE comuna_id=? AND created_at>=? AND category_id IS NOT NULL GROUP BY category_id ORDER BY searches DESC LIMIT 10').all(zone,since);res.json({period_days:days,searches:Number(total),previous_searches:Number(prev),variation_percent:Number(prev)?Math.round((Number(total)-Number(prev))*100/Number(prev)):null,terms,categories,privacy:'Datos agregados y anónimos. No se muestran búsquedas individuales.'});});
app.get('/api/businesses/:id/opportunity-radar',auth,(req,res)=>{const b=__dyOwnedBusiness(req.user.id,req.params.id);if(!b)return res.status(404).json({error:'Negocio no encontrado'});if(!__dyHasImpulse(b.id))return res.status(403).json({error:'🔒 Incluido con DatoYa Impulso',code:'IMPULSO_PLAN_REQUIRED'});const since=new Date(Date.now()-604800000).toISOString(),signals=db.prepare('SELECT normalized_term AS term,COUNT(*) demand,SUM(CASE WHEN result_count=0 THEN 1 ELSE 0 END) unmet FROM market_search_events WHERE comuna_id=? AND created_at>=? GROUP BY normalized_term HAVING COUNT(*)>=3 ORDER BY unmet DESC,demand DESC LIMIT 12').all(Number(b.comuna_id)||0,since);if(!signals.length)return res.json({opportunities:[],message:'Aún no hay suficiente actividad para generar oportunidades.'});const opportunities=signals.map(s=>{const like='%'+s.term.replace(/[%_]/g,'')+'%',supply=db.prepare("SELECT COUNT(*) c FROM products p JOIN businesses b ON b.id=p.business_id WHERE b.comuna_id=? AND b.status='active' AND p.active=1 AND (lower(p.name) LIKE ? OR lower(COALESCE(p.description,'')) LIKE ?)").get(Number(b.comuna_id)||0,like,like).c;return {term:s.term,demand:Number(s.demand),unmet:Number(s.unmet),supply:Number(supply),zone:'Tu comuna',period_days:7,reason:Number(supply)===0?'Demanda reciente sin oferta activa':'Demanda superior a la oferta visible'};}).filter(x=>x.unmet>0||x.demand>x.supply*2);res.json({opportunities,message:opportunities.length?null:'Aún no hay suficiente actividad para generar oportunidades.'});});
app.post('/api/market/alerts',auth,requireRole('cliente'),(req,res)=>{__dyExpire();const x=req.body||{},term=__dyNorm(x.term),hours={1:24,3:72,7:168}[Number(x.days)||3];if(term.length<2||!hours)return res.status(400).json({error:'Alerta inválida'});const active=db.prepare("SELECT id FROM market_alerts WHERE user_id=? AND normalized_term=? AND status='active' LIMIT 1").get(req.user.id,term);if(active)return res.status(409).json({error:'Ya tienes una alerta activa para esta búsqueda',id:active.id});const exp=new Date(Date.now()+hours*3600000).toISOString(),r=db.prepare('INSERT INTO market_alerts(user_id,normalized_term,raw_term,category_id,comuna_id,latitude,longitude,radius_km,expires_at) VALUES(?,?,?,?,?,?,?,?,?)').run(req.user.id,term,String(x.term||'').trim().slice(0,100),Number(x.category_id)||null,Number(x.comuna_id)||null,Number.isFinite(Number(x.latitude))?Number(x.latitude):null,Number.isFinite(Number(x.longitude))?Number(x.longitude):null,__dyAllowed(x.radius_km,[1,3,5,10],5),exp);res.status(201).json({id:r.lastInsertRowid,expires_at:exp});});
app.get('/api/market/alerts',auth,requireRole('cliente'),(req,res)=>{__dyExpire();res.json({alerts:db.prepare('SELECT * FROM market_alerts WHERE user_id=? ORDER BY id DESC LIMIT 100').all(req.user.id)});});
app.delete('/api/market/alerts/:id',auth,requireRole('cliente'),(req,res)=>{const now=new Date().toISOString(),r=db.prepare("UPDATE market_alerts SET status='cancelled',cancelled_at=?,updated_at=? WHERE id=? AND user_id=? AND status='active'").run(now,now,Number(req.params.id),req.user.id);if(!r.changes)return res.status(404).json({error:'Alerta activa no encontrada'});res.json({ok:true});});
app.post('/api/wanted',auth,requireRole('cliente'),(req,res)=>{const x=req.body||{},title=String(x.title||'').trim().slice(0,100),description=String(x.description||'').trim().slice(0,1000),days=__dyAllowed(x.days,[1,3,7],3);if(title.length<3||description.length<10)return res.status(400).json({error:'Completa qué buscas y una descripción de al menos 10 caracteres'});const recent=db.prepare("SELECT COUNT(*) c FROM wanted_requests WHERE user_id=? AND created_at>=datetime('now','-1 day')").get(req.user.id).c;if(Number(recent)>=5)return res.status(429).json({error:'Alcanzaste el límite diario de solicitudes'});const exp=new Date(Date.now()+days*86400000).toISOString(),r=db.prepare('INSERT INTO wanted_requests(user_id,title,normalized_term,category_id,description,needed_at,budget,comuna_id,latitude,longitude,radius_km,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(req.user.id,title,__dyNorm(title),Number(x.category_id)||null,description,x.needed_at||null,Number(x.budget)>0?Math.round(Number(x.budget)):null,Number(x.comuna_id)||null,Number.isFinite(Number(x.latitude))?Number(x.latitude):null,Number.isFinite(Number(x.longitude))?Number(x.longitude):null,__dyAllowed(x.radius_km,[1,3,5,10],5),exp);res.status(201).json({id:r.lastInsertRowid,expires_at:exp});});
app.get('/api/wanted/mine',auth,requireRole('cliente'),(req,res)=>{__dyExpire();const requests=db.prepare('SELECT * FROM wanted_requests WHERE user_id=? ORDER BY id DESC LIMIT 100').all(req.user.id);for(const q of requests)q.responses=db.prepare('SELECT wr.*,b.name business_name,p.name product_name FROM wanted_responses wr JOIN businesses b ON b.id=wr.business_id LEFT JOIN products p ON p.id=wr.product_id WHERE wr.request_id=? ORDER BY wr.id DESC').all(q.id);res.json({requests});});
app.get('/api/businesses/:id/wanted',auth,(req,res)=>{__dyExpire();const b=__dyOwnedBusiness(req.user.id,req.params.id);if(!b)return res.status(404).json({error:'Negocio no encontrado'});res.json({requests:db.prepare("SELECT id,title,category_id,description,needed_at,budget,comuna_id,radius_km,expires_at,created_at FROM wanted_requests WHERE status='active' AND (comuna_id=? OR comuna_id IS NULL) AND expires_at>? ORDER BY id DESC LIMIT 100").all(Number(b.comuna_id)||0,new Date().toISOString())});});
app.post('/api/wanted/:id/responses',auth,(req,res)=>{const x=req.body||{},b=__dyOwnedBusiness(req.user.id,x.business_id),message=String(x.message||'').trim().slice(0,1000);if(!b)return res.status(404).json({error:'Negocio no encontrado'});if(message.length<3)return res.status(400).json({error:'Escribe una respuesta'});const q=db.prepare("SELECT * FROM wanted_requests WHERE id=? AND status='active' AND expires_at>?").get(Number(req.params.id),new Date().toISOString());if(!q)return res.status(404).json({error:'Solicitud no disponible'});const productId=Number(x.product_id)||null;if(productId&&!db.prepare('SELECT id FROM products WHERE id=? AND business_id=? AND active=1').get(productId,b.id))return res.status(400).json({error:'Producto inválido'});db.prepare("INSERT INTO wanted_responses(request_id,business_id,responder_user_id,message,product_id,reference_price,availability) VALUES(?,?,?,?,?,?,?) ON CONFLICT(request_id,business_id) DO UPDATE SET message=excluded.message,product_id=excluded.product_id,reference_price=excluded.reference_price,availability=excluded.availability,updated_at=datetime('now')").run(q.id,b.id,req.user.id,message,productId,Number(x.reference_price)>0?Math.round(Number(x.reference_price)):null,String(x.availability||'').trim().slice(0,200)||null);notify(q.user_id,'wanted_response','Un negocio respondió a tu solicitud: '+q.title,'#/lo-busco-ya/'+q.id);res.status(201).json({ok:true});});
app.put('/api/wanted/:id/status',auth,requireRole('cliente'),(req,res)=>{const status=String(req.body?.status||''),allowed=new Set(['matched','closed','cancelled']);if(!allowed.has(status))return res.status(400).json({error:'Estado inválido'});const r=db.prepare("UPDATE wanted_requests SET status=?,updated_at=datetime('now') WHERE id=? AND user_id=? AND status='active'").run(status,Number(req.params.id),req.user.id);if(!r.changes)return res.status(404).json({error:'Solicitud activa no encontrada'});res.json({ok:true});});
app.post('/api/commerce/favorites/:type/:id',auth,requireRole('cliente'),(req,res)=>{const type=String(req.params.type),id=Number(req.params.id);if(!['product','business'].includes(type)||!id)return res.status(400).json({error:'Favorito inválido'});const table=type==='product'?'products':'businesses';if(!db.prepare('SELECT id FROM '+table+' WHERE id=?').get(id))return res.status(404).json({error:'Elemento no encontrado'});const current=db.prepare('SELECT id FROM commerce_favorites WHERE user_id=? AND target_type=? AND target_id=?').get(req.user.id,type,id);if(current){db.prepare('DELETE FROM commerce_favorites WHERE id=?').run(current.id);return res.json({saved:false});}db.prepare('INSERT INTO commerce_favorites(user_id,target_type,target_id) VALUES(?,?,?)').run(req.user.id,type,id);res.json({saved:true});});
app.get('/api/commerce/favorites',auth,requireRole('cliente'),(req,res)=>res.json({favorites:db.prepare('SELECT * FROM commerce_favorites WHERE user_id=? ORDER BY id DESC').all(req.user.id)}));
app.post('/api/businesses/:id/follow',auth,requireRole('cliente'),(req,res)=>{const id=Number(req.params.id);if(!db.prepare("SELECT id FROM businesses WHERE id=? AND status='active'").get(id))return res.status(404).json({error:'Negocio no disponible'});const current=db.prepare('SELECT user_id FROM followed_businesses WHERE user_id=? AND business_id=?').get(req.user.id,id);if(current){db.prepare('DELETE FROM followed_businesses WHERE user_id=? AND business_id=?').run(req.user.id,id);return res.json({following:false});}db.prepare('INSERT INTO followed_businesses(user_id,business_id) VALUES(?,?)').run(req.user.id,id);res.json({following:true});});
app.get('/api/commerce/favorites/details',auth,requireRole('cliente'),(req,res)=>{const products=db.prepare("SELECT f.id favorite_id,p.id,p.name,p.price,p.promo_price,p.image_data,b.name business_name,b.slug business_slug FROM commerce_favorites f JOIN products p ON p.id=f.target_id JOIN businesses b ON b.id=p.business_id WHERE f.user_id=? AND f.target_type='product' AND p.active=1 AND b.status='active' ORDER BY f.id DESC").all(req.user.id),businesses=db.prepare("SELECT f.id favorite_id,b.id,b.name,b.slug,b.description FROM commerce_favorites f JOIN businesses b ON b.id=f.target_id WHERE f.user_id=? AND f.target_type='business' AND b.status='active' ORDER BY f.id DESC").all(req.user.id),following=db.prepare("SELECT b.id,b.name,b.slug,fb.notify_promotions FROM followed_businesses fb JOIN businesses b ON b.id=fb.business_id WHERE fb.user_id=? AND b.status='active' ORDER BY fb.created_at DESC").all(req.user.id);res.json({products,businesses,following});});
function __dyAlertMatches(alert,item){if(alert.comuna_id&&item.comuna_id&&Number(alert.comuna_id)!==Number(item.comuna_id))return false;if(alert.category_id&&item.category_id&&Number(alert.category_id)!==Number(item.category_id))return false;const tokens=__dyNorm(alert.normalized_term).split(' ').filter(x=>x.length>=3),hay=__dyNorm([item.name,item.description,item.business_name].join(' '));return tokens.length>0&&tokens.every(t=>hay.includes(t));}
function __dyRunAlertMatching(){__dyExpire();const alerts=db.prepare("SELECT * FROM market_alerts WHERE status='active' AND expires_at>? ORDER BY id LIMIT 300").all(new Date().toISOString()),items=db.prepare("SELECT p.id,p.name,p.description,p.category_id,b.id business_id,b.name business_name,b.slug business_slug,b.comuna_id FROM products p JOIN businesses b ON b.id=p.business_id WHERE p.active=1 AND b.status='active' ORDER BY p.updated_at DESC LIMIT 1000").all();let matched=0;for(const a of alerts){const item=items.find(p=>__dyAlertMatches(a,p));if(!item)continue;const now=new Date().toISOString(),r=db.prepare("UPDATE market_alerts SET status='matched',matched_at=?,updated_at=? WHERE id=? AND status='active'").run(now,now,a.id);if(!r.changes)continue;notify(a.user_id,'market_alert','DatoYa Alerta encontró: '+item.name+' en '+item.business_name,'#/negocio/'+encodeURIComponent(item.business_slug));matched++;}return matched;}
function __dyNotifyOnce(userId,type,text,link){if(db.prepare('SELECT id FROM notifications WHERE user_id=? AND type=? AND text=? AND COALESCE(link,\'\')=COALESCE(?,\'\') LIMIT 1').get(userId,type,text,link||null))return false;notify(userId,type,text,link);return true;}
function __dyRunBusinessSignals(){const now=new Date(),soon=new Date(now.getTime()+3*86400000).toISOString(),recent=new Date(now.getTime()-7*86400000).toISOString();let created=0;for(const p of db.prepare("SELECT p.id,p.name,p.stock,b.id business_id,b.owner_user_id FROM products p JOIN businesses b ON b.id=p.business_id WHERE p.active=1 AND p.stock_tracking=1 AND p.stock<=5 AND b.status='active'").all()){const empty=Number(p.stock)<=0,text=empty?'Producto sin stock: '+p.name:'Stock bajo ('+Number(p.stock)+'): '+p.name;created+=__dyNotifyOnce(p.owner_user_id,empty?'stock_out':'stock_low',text,'#/mi-negocio-productos/'+p.business_id)?1:0}for(const i of db.prepare("SELECT i.id,i.title,b.id business_id,b.owner_user_id FROM impulse_now i JOIN businesses b ON b.id=i.business_id WHERE i.status='sold_out'").all()){created+=__dyNotifyOnce(i.owner_user_id,'impulse_sold_out','Tu Impulso Ahora se agotó: '+i.title,'#/impulso-ahora/'+i.business_id)?1:0}for(const m of db.prepare("SELECT m.id,m.expires_at,m.status,b.id business_id,b.owner_user_id FROM business_impulse_memberships m JOIN businesses b ON b.id=m.business_id WHERE (m.status='active' AND m.expires_at>? AND m.expires_at<=?) OR (m.status='expired' AND m.expires_at>=?)").all(now.toISOString(),soon,recent)){const expired=m.status==='expired',text=expired?'Tu plan DatoYa Impulso venció.':'Tu plan DatoYa Impulso vence el '+String(m.expires_at).slice(0,10)+'.';created+=__dyNotifyOnce(m.owner_user_id,expired?'impulse_expired':'impulse_expiring',text,'#/mi-negocio-plan/'+m.business_id)?1:0}for(const o of db.prepare("SELECT o.reference,o.updated_at,b.id business_id,b.owner_user_id FROM commerce_orders o JOIN businesses b ON b.id=o.business_id WHERE o.status='cancelled' AND o.updated_at>=?").all(recent)){created+=__dyNotifyOnce(o.owner_user_id,'order_cancelled','El pedido '+o.reference+' fue cancelado.','#/mi-negocio-pedidos/'+o.business_id)?1:0}return created;}
app.post('/api/admin/private-beta/run-matching',auth,requireRole('admin'),(req,res)=>res.json({ok:true,matched:__dyRunAlertMatching()}));
app.get('/api/admin/private-beta',auth,requireRole('admin'),(req,res)=>{__dyExpire();const alerts=db.prepare("SELECT a.*,u.name user_name,u.email FROM market_alerts a JOIN users u ON u.id=a.user_id ORDER BY a.id DESC LIMIT 300").all(),wanted=db.prepare("SELECT w.*,u.name user_name,u.email,(SELECT COUNT(*) FROM wanted_responses r WHERE r.request_id=w.id) response_count FROM wanted_requests w JOIN users u ON u.id=w.user_id ORDER BY w.id DESC LIMIT 300").all();res.json({summary:{alerts:alerts.length,active_alerts:alerts.filter(x=>x.status==='active').length,matched_alerts:alerts.filter(x=>x.status==='matched').length,wanted:wanted.length,active_wanted:wanted.filter(x=>x.status==='active').length,responses:wanted.reduce((n,x)=>n+Number(x.response_count||0),0)},alerts,wanted});});
app.put('/api/admin/private-beta/wanted/:id/status',auth,requireRole('admin'),(req,res)=>{const status=String(req.body?.status||''),allowed=new Set(['closed','cancelled']);if(!allowed.has(status))return res.status(400).json({error:'Estado inválido'});const r=db.prepare("UPDATE wanted_requests SET status=?,updated_at=datetime('now') WHERE id=?").run(status,Number(req.params.id));if(!r.changes)return res.status(404).json({error:'Solicitud no encontrada'});res.json({ok:true});});
setTimeout(()=>{try{__dyRunAlertMatching();__dyRunBusinessSignals()}catch(e){console.error('[DatoYa][Beta signals]',e.message)}},15000);const __dyAlertTimer=setInterval(()=>{try{__dyRunAlertMatching();__dyRunBusinessSignals()}catch(e){console.error('[DatoYa][Beta signals]',e.message)}},300000);if(__dyAlertTimer.unref)__dyAlertTimer.unref();
// ============ FIN DATOYA PRIVATE BETA CORE V1 ============
`;
source=source.replace('// ============ CATÁLOGOS ============',injection+'\n// ============ CATÁLOGOS ============');fs.writeFileSync(serverPath,source);
}
console.log('[DatoYa] Núcleo de beta privada preparado.');
