/* DatoYa beta privada: experiencia unificada para notificaciones, demanda y matching. */
(()=>{
  if(typeof routes==='undefined'||typeof view==='undefined'||typeof api!=='function')return;
  const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const when=v=>{try{return new Date(v).toLocaleString('es-CL',{dateStyle:'short',timeStyle:'short'})}catch(_){return String(v||'')}};
  const status=s=>({active:'Activa',matched:'Encontrada',expired:'Vencida',cancelled:'Cancelada',closed:'Cerrada'})[s]||s;
  function requireClient(){if(!ME){location.hash='#/login';return false}if(ME.account_type==='business'||ME.role==='admin'){toast?.('Esta sección pertenece a clientes','err');location.hash='#/perfil';return false}return true}

  let bellRefresh=null;
  function refreshBell(){
    if(bellRefresh)return bellRefresh;
    bellRefresh=(async()=>{const existing=[...document.querySelectorAll('#dy-notification-bell')];if(!ME){existing.forEach(x=>x.remove());return}try{const d=await api('/notifications/summary');let bell=document.getElementById('dy-notification-bell');document.querySelectorAll('#dy-notification-bell').forEach((x,i)=>{if(i>0)x.remove()});if(!bell){bell=document.createElement('a');bell.id='dy-notification-bell';bell.href='#/notificaciones';bell.className='dy-notification-bell';bell.setAttribute('aria-label','Notificaciones');(document.getElementById('auth-area')||document.body).prepend(bell)}bell.innerHTML=`🔔${Number(d.unread)>0?`<b>${Math.min(99,Number(d.unread))}</b>`:''}`;bell.classList.toggle('has-unread',Number(d.unread)>0)}catch(_){}})().finally(()=>{bellRefresh=null});
    return bellRefresh;
  }
  const priorAuth=typeof renderAuthArea==='function'?renderAuthArea:null;
  if(priorAuth)renderAuthArea=function(){const r=priorAuth.apply(this,arguments);setTimeout(refreshBell,0);return r};

  routes.notificaciones=async function(){
    if(!ME){location.hash='#/login';return}const d=await api('/notifications/summary'),rows=d.notifications||[];
    view.innerHTML=`<div class="dy-beta-page"><header class="dy-beta-head"><div><span>CENTRO DATOYA</span><h1>Notificaciones</h1><p>Pedidos, soporte, alertas y novedades importantes en un solo lugar.</p></div>${d.unread?'<button id="dy-read-all" class="btn btn-outline btn-sm">Marcar todas como leídas</button>':''}</header><div class="dy-notification-list">${rows.length?rows.map(n=>`<a href="${h(n.link||'#/notificaciones')}" class="dy-notification ${n.read_at?'':'unread'}" data-notification-id="${Number(n.id)}"><span>${n.read_at?'○':'●'}</span><div><b>${h(n.text)}</b><small>${when(n.created_at)}</small></div><em>→</em></a>`).join(''):'<div class="dy-beta-empty"><span>🔔</span><h2>Todo al día</h2><p>Las novedades importantes aparecerán aquí.</p></div>'}</div></div>`;
    document.getElementById('dy-read-all')?.addEventListener('click',async()=>{await api('/notifications/read-all',{method:'PUT'});await refreshBell();routes.notificaciones()});
    document.querySelectorAll('[data-notification-id]').forEach(a=>a.addEventListener('click',()=>api('/notifications/'+a.dataset.notificationId+'/read',{method:'PUT'}).catch(()=>{})));
  };

  routes.alertas=async function(){
    if(!requireClient())return;const d=await api('/market/alerts'),items=d.alerts||[];
    view.innerHTML=`<div class="dy-beta-page"><header class="dy-beta-head"><div><span>🔔 DATOYA ALERTA</span><h1>Tú buscas. DatoYa te avisa.</h1><p>Guarda una búsqueda y recibe una notificación cuando aparezca una coincidencia útil.</p></div></header><section class="dy-beta-card"><h2>Crear alerta</h2><form id="dy-alert-form" class="dy-beta-form"><label>¿Qué estás buscando?<input name="term" required minlength="2" maxlength="100" placeholder="Ej: torta sin azúcar"></label><div class="dy-beta-grid"><label>Duración<select name="days"><option value="1">24 horas</option><option value="3" selected>3 días</option><option value="7">7 días</option></select></label><label>Radio<select name="radius_km"><option value="1">1 km</option><option value="3">3 km</option><option value="5" selected>5 km</option><option value="10">10 km</option></select></label></div><button class="btn btn-primary" type="submit">Avísame cuando aparezca</button></form></section><section class="dy-beta-card"><div class="dy-beta-title"><h2>Mis alertas</h2><span>${items.length}</span></div><div class="dy-beta-list">${items.length?items.map(x=>`<article><div><b>${h(x.raw_term)}</b><small>${status(x.status)} · vence ${when(x.expires_at)}</small></div>${x.status==='active'?`<button class="btn btn-outline btn-sm" data-cancel-alert="${Number(x.id)}">Cancelar</button>`:''}</article>`).join(''):'<div class="dy-beta-empty"><span>🔎</span><p>Aún no has guardado búsquedas.</p></div>'}</div></section></div>`;
    document.getElementById('dy-alert-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{await api('/market/alerts',{method:'POST',body:{term:f.term.value.trim(),days:Number(f.days.value),radius_km:Number(f.radius_km.value),comuna_id:Number(ME.comuna_id||0)||null}});toast?.('Alerta creada','ok');routes.alertas()}catch(err){toast?.(err.message,'err')}});
    document.querySelectorAll('[data-cancel-alert]').forEach(b=>b.addEventListener('click',async()=>{await api('/market/alerts/'+b.dataset.cancelAlert,{method:'DELETE'});routes.alertas()}));
  };

  routes['lo-busco-ya']=async function(){
    if(!requireClient())return;const d=await api('/wanted/mine'),items=d.requests||[];
    view.innerHTML=`<div class="dy-beta-page"><header class="dy-beta-head"><div><span>🙋 LO BUSCO YA</span><h1>Cuéntale a los negocios qué necesitas</h1><p>Para compras que requieren más detalle que una búsqueda normal. Tu dirección exacta nunca se publica.</p></div></header><section class="dy-beta-card"><h2>Publicar solicitud</h2><form id="dy-wanted-form" class="dy-beta-form"><label>¿Qué necesitas?<input name="title" required minlength="3" maxlength="100" placeholder="Ej: torta para 10 personas"></label><label>Descripción<textarea name="description" required minlength="10" maxlength="1000" rows="4" placeholder="Fecha, características, sabores u otros detalles útiles"></textarea></label><div class="dy-beta-grid"><label>Presupuesto opcional<input name="budget" type="number" min="0" step="1000" placeholder="$"></label><label>Duración<select name="days"><option value="1">24 horas</option><option value="3" selected>3 días</option><option value="7">7 días</option></select></label></div><button class="btn btn-primary" type="submit">Publicar en mi zona</button></form></section><section class="dy-beta-card"><div class="dy-beta-title"><h2>Mis solicitudes</h2><span>${items.length}</span></div><div class="dy-wanted-list">${items.length?items.map(x=>`<article><div class="dy-wanted-top"><div><b>${h(x.title)}</b><small>${status(x.status)} · ${when(x.created_at)}</small></div>${x.status==='active'?`<button class="btn btn-outline btn-sm" data-close-wanted="${Number(x.id)}">Cerrar</button>`:''}</div><p>${h(x.description)}</p>${x.responses?.length?`<div class="dy-responses"><strong>${x.responses.length} respuesta(s)</strong>${x.responses.map(r=>`<div><b>${h(r.business_name)}</b><p>${h(r.message)}</p>${r.reference_price?`<small>Precio referencial: $${Number(r.reference_price).toLocaleString('es-CL')}</small>`:''}</div>`).join('')}</div>`:'<small>Aún no hay respuestas.</small>'}</article>`).join(''):'<div class="dy-beta-empty"><span>🙋</span><p>No tienes solicitudes publicadas.</p></div>'}</div></section></div>`;
    document.getElementById('dy-wanted-form')?.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget;try{await api('/wanted',{method:'POST',body:{title:f.title.value.trim(),description:f.description.value.trim(),budget:Number(f.budget.value)||null,days:Number(f.days.value),radius_km:5,comuna_id:Number(ME.comuna_id||0)||null}});toast?.('Solicitud publicada','ok');routes['lo-busco-ya']()}catch(err){toast?.(err.message,'err')}});
    document.querySelectorAll('[data-close-wanted]').forEach(b=>b.addEventListener('click',async()=>{await api('/wanted/'+b.dataset.closeWanted+'/status',{method:'PUT',body:{status:'closed'}});routes['lo-busco-ya']()}));
  };

  routes['mi-negocio-pulso']=async function(id){
    if(!ME){location.hash='#/login';return}id=Number(id);try{const d=await api('/businesses/'+id+'/local-pulse?days=7');view.innerHTML=`<div class="dy-beta-page dy-business-dashboard"><a class="dy-beta-back" href="#/mi-negocio/${id}">← Panel Negocio</a><header class="dy-beta-head"><div><span>📍 PULSO LOCAL</span><h1>Qué están buscando cerca</h1><p>${h(d.privacy)}</p></div></header><div class="dy-beta-metrics"><article><b>${Number(d.searches)}</b><span>Búsquedas esta semana</span></article><article><b>${d.variation_percent==null?'—':(d.variation_percent>0?'+':'')+d.variation_percent+'%'}</b><span>Variación anterior</span></article><article><b>${(d.terms||[]).filter(x=>Number(x.no_results)>0).length}</b><span>Necesidades sin resultado</span></article></div><section class="dy-beta-card"><h2>Productos más buscados</h2><div class="dy-opportunity-list">${(d.terms||[]).length?d.terms.map(x=>`<article><div><b>${h(x.term)}</b><small>${Number(x.searches)} búsquedas · ${Number(x.no_results)} sin resultado</small></div><a class="btn btn-outline btn-sm" href="#/mi-negocio-productos/${id}">Crear producto</a></article>`).join(''):'<div class="dy-beta-empty"><p>Aún no hay suficiente actividad en tu zona.</p></div>'}</div></section></div>`}catch(err){if(err.status===403){location.hash='#/mi-negocio-plan/'+id;toast?.('Pulso Local está incluido con DatoYa Impulso','err');return}throw err}
  };
  routes['mi-negocio-radar']=async function(id){
    if(!ME){location.hash='#/login';return}id=Number(id);try{const d=await api('/businesses/'+id+'/opportunity-radar');view.innerHTML=`<div class="dy-beta-page dy-business-dashboard"><a class="dy-beta-back" href="#/mi-negocio/${id}">← Panel Negocio</a><header class="dy-beta-head"><div><span>🎯 RADAR DE OPORTUNIDADES</span><h1>Demanda que puedes convertir en ventas</h1><p>Señales reales y agregadas de los últimos 7 días.</p></div></header><div class="dy-opportunity-list">${(d.opportunities||[]).length?d.opportunities.map(x=>`<article class="dy-beta-card"><div><b>${h(x.term)}</b><small>${Number(x.demand)} búsquedas · oferta visible: ${Number(x.supply)}</small><p>${h(x.reason)}</p></div><div><a class="btn btn-primary btn-sm" href="#/mi-negocio-productos/${id}">Crear producto</a><a class="btn btn-outline btn-sm" href="#/mi-negocio-promociones/${id}">Crear promoción</a></div></article>`).join(''):`<div class="dy-beta-empty dy-beta-card"><span>🎯</span><h2>Sin oportunidades todavía</h2><p>${h(d.message||'Aún no hay suficiente actividad para generar oportunidades.')}</p></div>`}</div></div>`}catch(err){if(err.status===403){location.hash='#/mi-negocio-plan/'+id;toast?.('Radar está incluido con DatoYa Impulso','err');return}throw err}
  };

  routes.favoritos=async function(){
    if(!requireClient())return;const d=await api('/commerce/favorites/details'),products=d.products||[],businesses=d.businesses||[],following=d.following||[];
    view.innerHTML=`<div class="dy-beta-page"><header class="dy-beta-head"><div><span>❤️ MIS GUARDADOS</span><h1>Favoritos y negocios seguidos</h1><p>Vuelve rápidamente a productos y comercios que te interesan.</p></div></header><section class="dy-beta-card"><h2>Productos favoritos</h2><div class="dy-opportunity-list">${products.length?products.map(p=>`<article><div><b>${h(p.name)}</b><small>${h(p.business_name)} · $${Number(p.promo_price||p.price).toLocaleString('es-CL')}</small></div><a class="btn btn-outline btn-sm" href="#/negocio/${h(p.business_slug)}">Ver</a></article>`).join(''):'<div class="dy-beta-empty"><p>No tienes productos guardados.</p></div>'}</div></section><section class="dy-beta-card"><h2>Negocios favoritos</h2><div class="dy-opportunity-list">${businesses.length?businesses.map(b=>`<article><div><b>${h(b.name)}</b><small>${h(b.description||'')}</small></div><a class="btn btn-outline btn-sm" href="#/negocio/${h(b.slug)}">Visitar</a></article>`).join(''):'<div class="dy-beta-empty"><p>No tienes negocios favoritos.</p></div>'}</div></section><section class="dy-beta-card"><h2>Negocios seguidos</h2><div class="dy-opportunity-list">${following.length?following.map(b=>`<article><div><b>${h(b.name)}</b><small>${b.notify_promotions?'Promociones activadas':'Sin avisos'}</small></div><a class="btn btn-outline btn-sm" href="#/negocio/${h(b.slug)}">Visitar</a></article>`).join(''):'<div class="dy-beta-empty"><p>Aún no sigues negocios.</p></div>'}</div></section></div>`;
  };
  const oldProfile=routes.perfil;
  if(oldProfile)routes.perfil=async function(...args){await oldProfile.apply(this,args);if(!ME||ME.account_type==='business'||document.querySelector('.dy-beta-profile-links'))return;const box=document.createElement('section');box.className='dy-beta-profile-links card';box.innerHTML='<h3>Mis compras en DatoYa</h3><a href="#/favoritos">❤️ Favoritos y seguidos</a><a href="#/alertas">🔔 Mis alertas</a><a href="#/lo-busco-ya">🙋 Lo Busco Ya</a>';view.appendChild(box)};

  if(routes.admin){const oldAdmin=routes.admin;routes.admin=async function(tab='dashboard'){if(tab!=='alertas'&&tab!=='lo-busco-ya')return oldAdmin.apply(this,arguments);if(!ME||ME.role!=='admin')return oldAdmin.apply(this,arguments);const d=await api('/admin/private-beta');if(tab==='alertas'){view.innerHTML=`<div class="dy-beta-page"><a class="dy-beta-back" href="#/admin">← Panel Admin</a><header class="dy-beta-head"><div><span>ADMIN · DATOYA ALERTA</span><h1>Alertas de búsqueda</h1><p>${d.summary.active_alerts} activas · ${d.summary.matched_alerts} encontradas</p></div><button id="dy-run-matching" class="btn btn-primary">Ejecutar matching</button></header><div class="dy-beta-card dy-beta-list">${(d.alerts||[]).map(a=>`<article><div><b>${h(a.raw_term)}</b><small>${h(a.user_name)} · ${h(a.status)} · vence ${when(a.expires_at)}</small></div></article>`).join('')||'<div class="dy-beta-empty">Sin alertas.</div>'}</div></div>`;document.getElementById('dy-run-matching')?.addEventListener('click',async()=>{const r=await api('/admin/private-beta/run-matching',{method:'POST'});toast?.(r.matched+' coincidencia(s) nuevas','ok');routes.admin('alertas')});return}view.innerHTML=`<div class="dy-beta-page"><a class="dy-beta-back" href="#/admin">← Panel Admin</a><header class="dy-beta-head"><div><span>ADMIN · LO BUSCO YA</span><h1>Solicitudes de clientes</h1><p>${d.summary.active_wanted} activas · ${d.summary.responses} respuestas</p></div></header><div class="dy-wanted-list">${(d.wanted||[]).map(w=>`<article class="dy-beta-card"><div class="dy-wanted-top"><div><b>${h(w.title)}</b><small>${h(w.user_name)} · ${h(w.status)} · ${Number(w.response_count)} respuesta(s)</small></div>${w.status==='active'?`<button class="btn btn-outline btn-sm" data-admin-close="${Number(w.id)}">Cerrar</button>`:''}</div><p>${h(w.description)}</p></article>`).join('')||'<div class="dy-beta-empty dy-beta-card">Sin solicitudes.</div>'}</div></div>`;document.querySelectorAll('[data-admin-close]').forEach(b=>b.addEventListener('click',async()=>{await api('/admin/private-beta/wanted/'+b.dataset.adminClose+'/status',{method:'PUT',body:{status:'closed'}});routes.admin('lo-busco-ya')}));};}

  const oldSearch=routes.buscar;
  if(oldSearch)routes.buscar=async function(...args){await oldSearch.apply(this,args);if(!ME||ME.account_type==='business'||document.querySelector('.dy-search-followup'))return;const box=document.createElement('section');box.className='dy-search-followup';box.innerHTML='<div><b>¿No apareció lo que buscabas?</b><span>Guarda una alerta o cuéntale a los negocios lo que necesitas.</span></div><a class="btn btn-outline btn-sm" href="#/alertas">🔔 Crear alerta</a><a class="btn btn-primary btn-sm" href="#/lo-busco-ya">🙋 Lo Busco Ya</a>';view.appendChild(box)};
  setTimeout(refreshBell,100);setInterval(refreshBell,60000);
})();
