/* DatoYa — UI del dominio comercial real. Sin tarjetas ni negocios inventados. */
(() => {
  const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n)||0);
  const gps=()=>({lat:localStorage.getItem('datoya_lat'),lng:localStorage.getItem('datoya_lng')});
  const params=extra=>{const p=new URLSearchParams(extra||{}),g=gps();if(g.lat&&g.lng){p.set('lat',g.lat);p.set('lng',g.lng);}if(!p.has('radius'))p.set('radius','5');return p;};
  const empty=(title,text,cta=true)=>`<div class="dy-empty-filter"><h3>${esc(title)}</h3><p>${esc(text)}</p>${cta?'<button class="btn primary" onclick="location.hash=\'#/registrar-negocio\'">Registrar mi negocio</button>':''}</div>`;

  function card(b){return `<article class="dy-business-card" onclick="location.hash='#/negocio/${encodeURIComponent(b.slug)}'">
    <div class="dy-business-photo"${b.cover_url?` style="background-image:url('${esc(b.cover_url)}')"`:''}><span class="dy-open">${b.opening_status==='open'?'● Disponible':'Cerrado'}</span></div>
    <div class="dy-business-body"><h3>${esc(b.name)}</h3><div class="dy-business-meta"><span>${esc(b.category_icon||'📍')} ${esc(b.category_name||'Negocio local')}</span>${b.distance_label?`<span>•</span><span>📍 ${esc(b.distance_label)}</span>`:''}</div><div class="dy-business-category">${esc(b.sector||b.comuna_name||'Zona por confirmar')}</div><div class="dy-card-action"><span>${Number(b.pickup_enabled)?'Retiro ':''}${Number(b.delivery_enabled)?'· Despacho':''}</span><button type="button">Ver negocio →</button></div></div>
  </article>`;}

  async function realHome(){
    const [cats,data]=await Promise.all([api('/business-categories'),api('/businesses?'+params())]);
    view.innerHTML=`<div class="dy-home"><section class="dy-hero"><div class="dy-hero-copy"><div class="dy-kicker">📍 Datos reales de tu zona</div><h1>Negocios locales <span>cerca de ti</span></h1><p>Encuentra productos y emprendimientos registrados en DatoYa.</p><form class="dy-search" id="real-business-search"><label class="dy-search-field"><span class="dy-search-icon">⌕</span><input name="q" placeholder="Ej: berlines, sushi, farmacia"></label><button class="dy-search-submit">Buscar</button></form></div></section>
    <section class="dy-section"><div class="dy-section-head"><div><h2>¿Qué necesitas hoy?</h2><p>Categorías comerciales administradas desde DatoYa.</p></div></div><div class="dy-category-strip">${cats.categories.map(c=>`<button class="dy-category" data-cat="${esc(c.slug)}"><span class="dy-category-icon" style="--cat-bg:${esc(c.color)}22">${esc(c.icon)}</span><b>${esc(c.name)}</b></button>`).join('')}</div></section>
    <section class="dy-section" id="resultados-reales"><div class="dy-section-head"><div><h2>📍 Negocios cerca de ti</h2><p>Radio de búsqueda: 5 km.</p></div></div><div class="dy-card-grid" id="real-business-grid">${data.businesses.length?data.businesses.map(card).join(''):empty('Aún no hay negocios registrados cerca de tu zona.','Sé el primero en registrar un negocio o emprendimiento real.')}</div></section>
    <section class="dy-local-banner"><div><h2>❤️ Lo local también es grande</h2><p>Registra un local físico o protege la dirección de tu emprendimiento desde casa.</p></div><button onclick="location.hash='#/registrar-negocio'">Registrar mi negocio</button></section></div>`;
    async function search(query,category){const p=params({q:query||'',category:category||''}),d=await api('/businesses?'+p),grid=document.getElementById('real-business-grid');grid.innerHTML=d.businesses.length?d.businesses.map(card).join(''):empty('Sin resultados reales','No hay negocios o productos registrados que coincidan con tu búsqueda.');document.getElementById('resultados-reales')?.scrollIntoView({behavior:'smooth'});}
    document.getElementById('real-business-search').onsubmit=e=>{e.preventDefault();search(new FormData(e.currentTarget).get('q'));};
    document.querySelectorAll('[data-cat]').forEach(x=>x.onclick=()=>search('',x.dataset.cat));
  }

  async function publicBusiness(slug){
    const d=await api('/businesses/'+encodeURIComponent(slug)+'?'+params());const b=d.business;
    view.innerHTML=`<div class="container"><button class="back" onclick="history.back()">← Volver</button><section class="card" style="overflow:hidden;padding:0"><div style="height:220px;background:#eef2f6 ${b.cover_url?`url('${esc(b.cover_url)}') center/cover`:''}"></div><div style="padding:24px"><div style="display:flex;gap:16px;align-items:center"><div style="width:76px;height:76px;border-radius:20px;background:#fff ${b.logo_url?`url('${esc(b.logo_url)}') center/cover`:''};box-shadow:0 5px 20px #0002"></div><div><h1>${esc(b.name)}</h1><p>${esc(b.category_icon||'🏪')} ${esc(b.category_name||'Negocio local')} ${b.distance_label?'· 📍 '+esc(b.distance_label):''}</p><b>${esc(d.open_state.label)}${d.open_state.next_open?' · Abre a las '+esc(d.open_state.next_open):''}</b></div></div><p>${esc(b.description||'Este negocio todavía no agrega una descripción.')}</p><p>📍 ${b.address_protected?esc(b.sector||b.comuna_name||'Zona aproximada')+' · Dirección protegida':esc(b.address||b.sector||b.comuna_name||'Ubicación no publicada')}</p><p>${Number(b.pickup_enabled)?'✓ Retiro disponible ':''}${Number(b.delivery_enabled)?'✓ Despacho propio':''}</p>${b.whatsapp?`<a class="btn primary" target="_blank" rel="noopener" href="https://wa.me/${String(b.whatsapp).replace(/\D/g,'')}">WhatsApp</a>`:''}</div></section><h2>Productos</h2><div class="dy-card-grid">${d.products.length?d.products.map(p=>`<article class="card"><h3>${esc(p.name)}</h3><p>${esc(p.description||'')}</p><strong>${money(p.promo_price??p.price)}</strong>${p.promo_price!=null?` <s>${money(p.price)}</s>`:''}<p>${Number(p.stock_tracking)?'Stock: '+Number(p.stock):'Disponible'}</p></article>`).join(''):empty('Sin productos publicados','Este negocio todavía no publica productos.',false)}</div></div>`;
  }

  async function registerBusiness(){
    if(!window.ME){location.hash='#/login';return;}
    const [cats,regions]=await Promise.all([api('/business-categories'),api('/regions')]);
    view.innerHTML=`<div class="container"><button class="back" onclick="history.back()">← Volver</button><div class="card"><h1>Registrar mi negocio</h1><p>Tu avance se crea como borrador. Si vendes desde casa, tu dirección permanecerá protegida.</p><form id="business-register"><label>1. Nombre del negocio<input name="name" required minlength="2"></label><label>2. Tipo<select name="business_type"><option value="physical_store">Local físico</option><option value="home_business">Vendo desde casa</option></select></label><label>3. Categoría principal<select name="main_category_id" required>${cats.categories.map(c=>`<option value="${c.id}">${esc(c.icon)} ${esc(c.name)}</option>`).join('')}</select></label><label>4. Sector aproximado<input name="sector" placeholder="Ej: centro de Doñihue"></label><label>5. Región<select name="region_id" id="business-region">${regions.regions.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></label><label>Comuna<select name="comuna_id" id="business-comuna"></select></label><div style="display:flex;gap:10px;flex-wrap:wrap"><button class="btn" type="button" id="business-gps">📍 Usar GPS</button><span id="business-gps-state">Ubicación pendiente</span></div><label>6. WhatsApp<input name="whatsapp" inputmode="tel"></label><label><input type="checkbox" name="pickup_enabled"> 8. Permitir retiro</label><label><input type="checkbox" name="delivery_enabled"> Despacho propio</label><button class="btn primary" type="submit">Guardar borrador</button></form></div></div>`;
    const form=document.getElementById('business-register'),region=document.getElementById('business-region'),comuna=document.getElementById('business-comuna');let coords=null;
    async function loadComunas(){const d=await api('/comunas?region_id='+region.value);comuna.innerHTML=d.comunas.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');}region.onchange=loadComunas;await loadComunas();
    document.getElementById('business-gps').onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{coords={latitude:p.coords.latitude,longitude:p.coords.longitude,location_accuracy:p.coords.accuracy};document.getElementById('business-gps-state').textContent='GPS guardado para calcular distancia';},()=>toast('No pudimos obtener el GPS','err'));
    form.onsubmit=async e=>{e.preventDefault();if(!coords)return toast('Debes guardar la ubicación GPS','err');const x=Object.fromEntries(new FormData(form));x.main_category_id=Number(x.main_category_id);x.region_id=Number(x.region_id);x.comuna_id=Number(x.comuna_id);x.pickup_enabled=Boolean(x.pickup_enabled);x.delivery_enabled=Boolean(x.delivery_enabled);const created=await api('/businesses',{method:'POST',body:{name:x.name,business_type:x.business_type}});x.category_ids=[x.main_category_id];await api('/businesses/'+created.business.id,{method:'PUT',body:{...x,...coords}});toast('Borrador guardado','ok');location.hash='#/panel-negocio/'+created.business.id;};
  }

  async function businessPanel(id){
    const d=await api('/my/businesses/'+id+'/dashboard');view.innerHTML=`<div class="container"><div class="page-head"><div><h1>${esc(d.business.name)}</h1><p>Panel del negocio · ${esc(d.business.status)}</p></div>${d.business.status==='active'?`<button class="btn" onclick="location.hash='#/negocio/${esc(d.business.slug)}'">Ver como cliente</button>`:''}</div><div class="stats-grid"><div class="stat"><b>${d.metrics.visits}</b><span>Visitas</span></div><div class="stat"><b>${d.metrics.favorites}</b><span>Favoritos</span></div><div class="stat"><b>${d.metrics.whatsapp_clicks}</b><span>Clics WhatsApp</span></div><div class="stat"><b>${d.metrics.products_active}</b><span>Productos activos</span></div></div><div class="card"><h2>Administrar</h2><p>Mi negocio · Productos · Promociones · Impulso Ahora · Pedidos · Clientes · Estadísticas · Horarios · Ubicación · Fotos · Plan · Configuración</p><button id="submit-business" class="btn primary">Enviar a revisión</button></div></div>`;document.getElementById('submit-business').onclick=async()=>{await api('/businesses/'+id+'/submit',{method:'POST'});toast('Negocio enviado a revisión','ok');businessPanel(id);};
  }

  if(typeof routes!=='undefined'){
    routes['']=realHome;routes['inicio']=realHome;routes['negocio']=publicBusiness;routes['registrar-negocio']=registerBusiness;routes['panel-negocio']=businessPanel;
  }
  if(!location.hash||location.hash==='#/'||location.hash==='#') realHome();
})();
