/* DatoYa — UI comercial conectada a APIs reales. */
(() => {
  const money=n=>new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Number(n)||0);
  const gps=()=>({lat:localStorage.getItem('datoya_lat'),lng:localStorage.getItem('datoya_lng')});
  let radius=Number(localStorage.getItem('datoya_radius')||5);
  const params=extra=>{const p=new URLSearchParams(extra||{}),g=gps();if(g.lat&&g.lng){p.set('lat',g.lat);p.set('lng',g.lng);}p.set('radius',String(radius));return p;};
  const empty=(title,text,cta=false)=>`<div class="dy-empty-filter"><h3>${esc(title)}</h3><p>${esc(text)}</p>${cta?'<button class="btn primary" onclick="location.hash=\'#/registrar-negocio\'">Registrar mi negocio</button>':''}</div>`;
  const card=b=>`<article class="dy-business-card" data-business-slug="${esc(b.slug)}"><div class="dy-business-photo"${b.cover_url?` style="background-image:url('${esc(b.cover_url)}')"`:''}><span class="dy-open">${b.opening_status==='open'?'● Disponible':'Cerrado'}</span></div><div class="dy-business-body"><h3>${esc(b.name)}</h3><div class="dy-business-meta"><span>${esc(b.category_icon||'🏪')} ${esc(b.category_name||'Negocio local')}</span>${b.distance_label?`<span>📍 ${esc(b.distance_label)}</span>`:''}</div><div class="dy-business-category">${esc(b.sector||b.comuna_name||'Zona por confirmar')}</div><div class="dy-card-action"><span>${Number(b.pickup_enabled)?'Retiro ':''}${Number(b.delivery_enabled)?'· Despacho':''}</span><button type="button">Ver negocio →</button></div></div></article>`;
  const productCard=p=>`<article class="card" data-product-result><h3>${esc(p.name)}</h3><strong>${money(p.promo_price??p.price)}</strong><p>${esc(p.business_name||'')}</p>${p.distance_km!=null?`<p>📍 ${p.distance_km<1?Math.round(p.distance_km*1000)+' m':p.distance_km.toFixed(1)+' km'}</p>`:''}<button class="btn" data-open-business="${esc(p.business_slug||'')}">Ver negocio</button></article>`;

  async function realHome(){
    try{
      const [cats,data]=await Promise.all([api('/business-categories'),api('/businesses?'+params())]);
      view.innerHTML=`<div class="dy-home"><div class="dy-mobile-location"><div><span>📍 Tu ubicación</span><b data-dy-location-label>${esc(localStorage.getItem('datoya_location_label')||'Elegir ubicación')}</b></div><button data-dy-locate>Cambiar</button></div><section class="dy-hero"><div class="dy-hero-copy"><div class="dy-kicker">📍 Datos reales de tu zona</div><h1>Lo que buscas, <span>cerca de ti</span></h1><p>Negocios, productos y emprendimientos realmente registrados en DatoYa.</p><form class="dy-search" id="real-business-search"><label class="dy-search-field"><span class="dy-search-icon">⌕</span><input name="q" required minlength="2" placeholder="Ej: berlines, sushi, farmacia"></label><button class="dy-search-submit">Buscar</button></form></div></section><section class="dy-section"><div class="dy-section-head"><div><h2>¿Qué necesitas hoy?</h2><p>Categorías comerciales administradas desde la base de datos.</p></div></div><div class="dy-category-strip">${cats.categories.map(c=>`<button class="dy-category" data-cat="${esc(c.slug)}"><span class="dy-category-icon" style="--cat-bg:${esc(c.color)}22">${esc(c.icon)}</span><b>${esc(c.name)}</b></button>`).join('')}</div></section><section class="dy-section dy-live-section"><div class="dy-section-head"><div><h2>⚡ Ahora cerca de ti</h2><p>Ofertas activas por horario y stock.</p></div></div>${empty('Todavía no hay Impulsos Ahora activos cerca de ti.','Cuando un negocio publique una venta inmediata aparecerá aquí.')}</section><section class="dy-section"><div class="dy-section-head"><div><h2>🔥 Promociones cerca de ti</h2></div></div>${empty('No hay promociones activas en tu zona.','Puedes cambiar la ubicación o ampliar el radio.')}</section><section class="dy-section" id="resultados-reales"><div class="dy-section-head"><div><h2>📍 Negocios cerca de ti</h2><p>Radio seleccionado: <b id="radius-label">${radius} km</b></p></div><div>${[1,3,5,10].map(n=>`<button class="btn ${n===radius?'primary':''}" data-radius="${n}">${n} km</button>`).join(' ')}</div></div><div class="dy-card-grid" id="real-business-grid">${data.businesses.length?data.businesses.map(card).join(''):empty('Todavía no encontramos negocios registrados cerca de ti.','Prueba ampliar el radio, cambiar tu ubicación o registra el primero.',true)}</div></section><section class="dy-local-banner"><div><h2>❤️ Lo local también es grande</h2><p>Registra un local físico o un emprendimiento desde casa con dirección protegida.</p></div><button onclick="location.hash='#/registrar-negocio'">Registrar mi negocio</button></section></div>`;
      const grid=document.getElementById('real-business-grid');
      const bind=()=>{grid.querySelectorAll('[data-business-slug]').forEach(x=>x.onclick=()=>location.hash='#/negocio/'+encodeURIComponent(x.dataset.businessSlug));grid.querySelectorAll('[data-open-business]').forEach(x=>x.onclick=()=>location.hash='#/negocio/'+encodeURIComponent(x.dataset.openBusiness));};bind();
      async function businesses(category=''){const d=await api('/businesses?'+params({category}));grid.innerHTML=d.businesses.length?d.businesses.map(card).join(''):empty('Sin resultados reales','No hay negocios registrados con esos filtros.',true);bind();}
      document.querySelectorAll('[data-cat]').forEach(x=>x.onclick=()=>businesses(x.dataset.cat));
      document.querySelectorAll('[data-radius]').forEach(x=>x.onclick=()=>{radius=Number(x.dataset.radius);localStorage.setItem('datoya_radius',String(radius));realHome();});
      document.getElementById('real-business-search').onsubmit=async e=>{e.preventDefault();const q=new FormData(e.currentTarget).get('q');const d=await api('/search?'+params({q}));grid.innerHTML=d.results.length?d.results.map(x=>x.type==='product'?productCard(x):x.type==='business'?card(x):`<article class="card"><h3>${esc(x.icon||'')} ${esc(x.name)}</h3><button class="btn" data-search-category="${esc(x.slug)}">Ver categoría</button></article>`).join(''):empty('No encontramos resultados','Puedes ampliar el radio o registrar lo que falta.',true);bind();grid.querySelectorAll('[data-search-category]').forEach(x=>x.onclick=()=>businesses(x.dataset.searchCategory));document.getElementById('resultados-reales').scrollIntoView({behavior:'smooth'});};
    }catch(error){view.innerHTML=`<div class="container">${empty('No pudimos cargar los negocios',error.message)}<button class="btn" onclick="location.reload()">Reintentar</button></div>`;}
  }

  async function publicBusiness(slug){
    const d=await api('/businesses/'+encodeURIComponent(slug)+'?'+params()),b=d.business;
    view.innerHTML=`<div class="container"><button class="back" onclick="history.back()">← Volver</button><section class="card" style="overflow:hidden;padding:0"><div style="height:220px;background:#eef2f6 ${b.cover_url?`url('${esc(b.cover_url)}') center/cover`:''}"></div><div style="padding:24px"><h1>${esc(b.name)}</h1><p>${esc(b.category_icon||'🏪')} ${esc(b.category_name||'Negocio local')} ${b.distance_label?'· 📍 '+esc(b.distance_label):''}</p><b>${esc(d.open_state.label)}${d.open_state.next_open?' · Abre a las '+esc(d.open_state.next_open):''}</b><p>${esc(b.description||'Este negocio todavía no agrega una descripción.')}</p><p>📍 ${b.address_protected?esc(b.sector||b.comuna_name||'Zona aproximada')+' · Dirección protegida':esc(b.public_address||b.address||b.sector||b.comuna_name||'Ubicación no publicada')}</p><p>${Number(b.pickup_enabled)?'✓ Retiro disponible ':''}${Number(b.delivery_enabled)?'✓ Despacho propio':''}</p><div style="display:flex;gap:8px;flex-wrap:wrap">${b.whatsapp?'<button class="btn primary" id="business-whatsapp">WhatsApp</button>':''}<button class="btn" id="business-favorite">♡ Favorito</button><button class="btn" id="business-share">Compartir</button></div></div></section><h2>Productos</h2><div class="dy-card-grid">${d.products.length?d.products.map(p=>`<article class="card"><h3>${esc(p.name)}</h3><p>${esc(p.description||'')}</p><strong>${money(p.promo_price??p.price)}</strong><p>${Number(p.stock_tracking)?'Stock: '+Number(p.stock):'Disponible'}</p></article>`).join(''):empty('Sin productos publicados','Este negocio todavía no publica productos.')}</div></div>`;
    document.getElementById('business-whatsapp')?.addEventListener('click',async()=>{await api('/businesses/'+b.id+'/whatsapp-click',{method:'POST'}).catch(()=>{});window.open('https://wa.me/'+String(b.whatsapp).replace(/\D/g,''),'_blank','noopener');});
    document.getElementById('business-favorite').onclick=async()=>{if(!window.ME)return location.hash='#/login';await api('/businesses/'+b.id+'/favorite',{method:'POST'});toast('Guardado en favoritos','ok');};
    document.getElementById('business-share').onclick=()=>navigator.share?navigator.share({title:b.name,url:location.href}):navigator.clipboard.writeText(location.href).then(()=>toast('Enlace copiado','ok'));
  }

  async function registerBusiness(){
    if(!window.ME){location.hash='#/login';return;}
    const [cats,regions]=await Promise.all([api('/business-categories'),api('/regions')]);let coords=null,draftId=null,step=1;
    view.innerHTML=`<div class="container"><button class="back" onclick="history.back()">← Volver</button><div class="card"><h1>Registrar mi negocio</h1><p id="wizard-progress">Paso 1 de 6 · El progreso se guarda como borrador.</p><form id="business-register"><section data-step="1"><label>Nombre del negocio<input name="name" required minlength="2"></label><label>Tipo<select name="business_type"><option value="physical_store">Local físico</option><option value="home_business">Vendo desde casa</option></select></label><label>Descripción<textarea name="description"></textarea></label></section><section data-step="2" hidden><label>Categoría principal<select name="main_category_id">${cats.categories.map(c=>`<option value="${c.id}">${esc(c.icon)} ${esc(c.name)}</option>`).join('')}</select></label><fieldset><legend>Categorías secundarias (máximo 3)</legend>${cats.categories.map(c=>`<label><input type="checkbox" name="secondary" value="${c.id}"> ${esc(c.name)}</label>`).join('')}</fieldset></section><section data-step="3" hidden><label>Región<select name="region_id" id="business-region">${regions.regions.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></label><label>Comuna<select name="comuna_id" id="business-comuna"></select></label><label>Dirección privada<input name="address"></label><label>Sector público aproximado<input name="sector" placeholder="Ej: centro de Doñihue"></label><label><input type="checkbox" name="show_exact_address"> Mostrar dirección exacta públicamente</label><button class="btn" type="button" id="business-gps">📍 Usar GPS</button> <span id="business-gps-state">Ubicación GPS pendiente</span></section><section data-step="4" hidden><label>WhatsApp<input name="whatsapp" inputmode="tel"></label><label>Teléfono<input name="phone" inputmode="tel"></label><label>Instagram<input name="instagram"></label><label>Sitio web<input name="website"></label></section><section data-step="5" hidden><label><input type="checkbox" name="pickup_enabled"> Permitir retiro</label><label><input type="checkbox" name="delivery_enabled"> Despacho propio</label><label>Radio de despacho (km)<input type="number" name="delivery_radius_km" min="0" max="50"></label><label>Logo (URL temporal)<input name="logo_url" type="url"></label><label>Portada (URL temporal)<input name="cover_url" type="url"></label></section><section data-step="6" hidden><h2>Vista previa</h2><div id="business-preview"></div><p>El negocio permanecerá como borrador hasta que lo envíes a revisión desde el panel.</p></section><div style="display:flex;gap:8px;margin-top:18px"><button class="btn" type="button" id="wizard-prev" hidden>Anterior</button><button class="btn primary" type="button" id="wizard-next">Continuar</button></div></form></div></div>`;
    const form=document.getElementById('business-register'),region=document.getElementById('business-region'),comuna=document.getElementById('business-comuna');
    async function loadComunas(){const d=await api('/comunas?region_id='+region.value);comuna.innerHTML=d.comunas.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');}region.onchange=loadComunas;await loadComunas();
    document.getElementById('business-gps').onclick=()=>navigator.geolocation?.getCurrentPosition(async p=>{coords={latitude:p.coords.latitude,longitude:p.coords.longitude,location_accuracy:p.coords.accuracy};const z=await api('/location/reverse?lat='+coords.latitude+'&lng='+coords.longitude);if(z.place){region.value=String(z.place.region_id);await loadComunas();comuna.value=String(z.place.id);}document.getElementById('business-gps-state').textContent=z.place?`${z.place.name}, ${z.place.region}`:'GPS guardado';},()=>toast('Puedes guardar el borrador y configurar la ubicación después.','err'),{enableHighAccuracy:true,timeout:12000});
    async function save(){const fd=new FormData(form),type=fd.get('business_type');if(!draftId){const c=await api('/businesses',{method:'POST',body:{name:fd.get('name'),business_type:type}});draftId=c.business.id;}const primary=Number(fd.get('main_category_id')),secondary=fd.getAll('secondary').map(Number).filter(x=>x!==primary).slice(0,3);await api('/businesses/'+draftId,{method:'PUT',body:{name:fd.get('name'),description:fd.get('description'),business_type:type,main_category_id:primary,category_ids:[primary,...secondary],region_id:Number(fd.get('region_id')),comuna_id:Number(fd.get('comuna_id')),address:fd.get('address'),sector:fd.get('sector'),show_exact_address:type==='home_business'?Boolean(fd.get('show_exact_address')):true,public_location_mode:type==='home_business'?(fd.get('show_exact_address')?'exact':'approximate'):'exact',whatsapp:fd.get('whatsapp'),phone:fd.get('phone'),instagram:fd.get('instagram'),website:fd.get('website'),pickup_enabled:Boolean(fd.get('pickup_enabled')),delivery_enabled:Boolean(fd.get('delivery_enabled')),delivery_radius_km:Number(fd.get('delivery_radius_km')||0),logo_url:fd.get('logo_url'),cover_url:fd.get('cover_url'),...(coords||{})}});localStorage.setItem('datoya_business_draft',String(draftId));}
    function show(){form.querySelectorAll('[data-step]').forEach(s=>s.hidden=Number(s.dataset.step)!==step);document.getElementById('wizard-progress').textContent=`Paso ${step} de 6 · El progreso se guarda como borrador.`;document.getElementById('wizard-prev').hidden=step===1;document.getElementById('wizard-next').textContent=step===6?'Ir al panel':'Guardar y continuar';if(step===6){const fd=new FormData(form);document.getElementById('business-preview').innerHTML=`<div class="card"><h3>${esc(fd.get('name'))}</h3><p>${fd.get('business_type')==='home_business'?'Emprendimiento desde casa · dirección protegida':'Local físico'}</p><p>📍 ${esc(comuna.options[comuna.selectedIndex]?.text||'Ubicación pendiente')}</p></div>`;}}
    document.getElementById('wizard-prev').onclick=()=>{step=Math.max(1,step-1);show();};document.getElementById('wizard-next').onclick=async()=>{try{if(step===1&&!form.reportValidity())return;await save();if(step===6){location.hash='#/panel-negocio/'+draftId;return;}step++;show();toast('Borrador guardado','ok');}catch(e){toast(e.message,'err');}};show();
  }

  async function businessPanel(id){
    const [d,p]=await Promise.all([api('/my/businesses/'+id+'/dashboard'),api('/my/businesses/'+id+'/products')]);
    view.innerHTML=`<div class="container"><div class="page-head"><div><h1>${esc(d.business.name)}</h1><p>Panel del negocio · ${esc(d.business.status)}</p></div>${d.business.status==='active'?`<button class="btn" onclick="location.hash='#/negocio/${esc(d.business.slug)}'">Ver como cliente</button>`:''}</div><div class="stats-grid"><div class="stat"><b>${d.metrics.visits}</b><span>Visitas</span></div><div class="stat"><b>${d.metrics.favorites}</b><span>Favoritos</span></div><div class="stat"><b>${d.metrics.whatsapp_clicks}</b><span>Clics WhatsApp</span></div><div class="stat"><b>${d.metrics.products_active}</b><span>Productos activos</span></div></div><div class="card"><h2>Productos</h2><form id="new-product"><label>Nombre<input name="name" required></label><label>Precio<input name="price" type="number" min="0" required></label><label>Stock<input name="stock" type="number" min="0" value="0"></label><label><input name="stock_tracking" type="checkbox"> Controlar stock</label><button class="btn primary">+ Agregar producto</button></form><div id="merchant-products">${p.products.length?p.products.map(x=>`<div class="card"><b>${esc(x.name)}</b> · ${money(x.price)} · Stock ${x.stock}<button class="btn" data-hide-product="${x.id}">Ocultar</button></div>`).join(''):empty('Sin productos','Agrega tu primer producto real.')}</div></div><div class="card"><h2>Administrar</h2><p>Mi negocio · Productos · Promociones · Impulso Ahora · Pedidos · Clientes · Estadísticas · Horarios · Ubicación · Fotos · Plan · Configuración</p>${d.business.status==='draft'||d.business.status==='rejected'?'<button id="submit-business" class="btn primary">Enviar a revisión</button>':''}</div></div>`;
    document.getElementById('new-product').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);await api('/businesses/'+id+'/products',{method:'POST',body:{name:fd.get('name'),price:Number(fd.get('price')),stock:Number(fd.get('stock')),stock_tracking:Boolean(fd.get('stock_tracking'))}});toast('Producto agregado','ok');businessPanel(id);};
    document.querySelectorAll('[data-hide-product]').forEach(x=>x.onclick=async()=>{await api('/businesses/'+id+'/products/'+x.dataset.hideProduct,{method:'DELETE'});toast('Producto ocultado','ok');businessPanel(id);});
    document.getElementById('submit-business')?.addEventListener('click',async()=>{try{await api('/businesses/'+id+'/submit',{method:'POST'});toast('Negocio enviado a revisión','ok');businessPanel(id);}catch(e){toast(e.message,'err');}});
  }

  if(typeof routes!=='undefined'){routes['']=realHome;routes.inicio=realHome;routes.negocio=publicBusiness;routes['registrar-negocio']=registerBusiness;routes['panel-negocio']=businessPanel;}
  if(!location.hash||location.hash==='#/'||location.hash==='#')realHome();
})();
