// DatoYa 2.0 — capa de seguridad Chile-only (sin geolocalización precisa)
const fs=require('fs'),path=require('path');
const serverFile=path.join(__dirname,'server.js'),orig=fs.readFileSync;
const injection=`
// ============ SEGURIDAD CHILE ============
try{db.exec(\`CREATE TABLE IF NOT EXISTS security_events (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, event_type TEXT NOT NULL, risk INTEGER NOT NULL DEFAULT 0, detail TEXT, ip_hint TEXT, created_at TEXT DEFAULT (datetime('now')));\`);}catch(e){console.error('[DatoYa] security_events',e.message)}
function dyClientIp(req){return String(req.headers['cf-connecting-ip']||req.headers['x-forwarded-for']||req.ip||'').split(',')[0].trim().slice(0,80)}
function dyCountry(req){return String(req.headers['cf-ipcountry']||req.headers['x-vercel-ip-country']||req.headers['x-country-code']||'').trim().toUpperCase().slice(0,2)}
function dyMaskIp(ip){return String(ip||'').replace(/(\\d+)\\.(\\d+)\\.(\\d+)\\.\\d+/,'$1.$2.$3.x').slice(0,80)}
function dyLogSecurity(req,type,risk,detail,userId){try{db.prepare('INSERT INTO security_events(user_id,event_type,risk,detail,ip_hint) VALUES(?,?,?,?,?)').run(userId||req.user?.id||null,type,risk,String(detail||'').slice(0,500),dyMaskIp(dyClientIp(req)));}catch(e){console.error('[DatoYa] security log',e.message)}}
function dyChilePhone(phone){const p=String(phone||'').replace(/[\\s()-]/g,'');return /^(?:\\+?56)?9\\d{8}$/.test(p)}
function dySessionUser(req){try{const token=req.cookies.datoya_token;if(!token)return null;return db.prepare(\`SELECT u.id,u.phone,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at > datetime('now') AND u.is_active=1\`).get(token)||null}catch(_){return null}}
function dyChileGate(req,res,next){const country=dyCountry(req);if(country&&country!=='CL'){const u=dySessionUser(req);dyLogSecurity(req,'pais_fuera_chile',90,'País informado por infraestructura: '+country,u?.id);return res.status(403).json({error:'DatoYa opera exclusivamente en Chile. Si estás en Chile y ves este mensaje, contacta a soporte.'});}next()}
function dyPhoneRisk(req,res,next){if(!['POST','PUT','PATCH'].includes(req.method))return next();const u=dySessionUser(req);if(!u)return next();if(!u.phone){dyLogSecurity(req,'telefono_faltante',45,'Intento de operación sensible sin teléfono registrado',u.id);return res.status(403).json({error:'Por seguridad, agrega un número móvil chileno a tu cuenta antes de continuar.'});}if(!dyChilePhone(u.phone)){dyLogSecurity(req,'telefono_no_chileno',70,'Formato de teléfono no corresponde a móvil chileno',u.id);return res.status(403).json({error:'DatoYa requiere un número móvil chileno válido (+56 9) para esta acción.'});}next()}
app.use('/api/requests',dyChileGate,dyPhoneRisk);
app.use('/api/quotes',dyChileGate,dyPhoneRisk);
app.use('/api/conversations/start',dyChileGate,dyPhoneRisk);
app.post('/api/security/phone',auth,(req,res)=>{const raw=String(req.body?.phone||'').trim();if(!dyChilePhone(raw))return res.status(400).json({error:'Ingresa un celular chileno válido, por ejemplo +56 9XXXXXXXX.'});let p=raw.replace(/[\\s()-]/g,'');if(p.startsWith('9'))p='+56'+p;else if(p.startsWith('569'))p='+'+p;else if(p.startsWith('56'))p='+'+p;db.prepare('UPDATE users SET phone=? WHERE id=?').run(p,req.user.id);dyLogSecurity(req,'telefono_chileno_registrado',10,'Número chileno registrado; pendiente de verificación SMS',req.user.id);res.json({ok:true,phone:p,verified:false,sms_enabled:false,message:'Número guardado. La verificación por SMS se activará cuando se conecte el proveedor.'})});
app.get('/api/security/status',auth,(req,res)=>{const u=db.prepare('SELECT phone FROM users WHERE id=?').get(req.user.id);res.json({chile_only:true,phone_present:Boolean(u?.phone),phone_chilean:dyChilePhone(u?.phone),phone_verified:false,sms_enabled:false})});
app.get('/api/admin/security-events',auth,requireRole('admin'),(req,res)=>{const events=db.prepare(\`SELECT se.*,u.name,u.email FROM security_events se LEFT JOIN users u ON u.id=se.user_id ORDER BY se.id DESC LIMIT 200\`).all();res.json({events})});
`;
fs.readFileSync=function(file,options){const v=orig.call(fs,file,options);if(path.resolve(String(file))!==path.resolve(serverFile)||typeof v!=='string')return v;if(v.includes('// ============ SEGURIDAD CHILE ============'))return v;const marker='// ============ AUTH ============';return v.includes(marker)?v.replace(marker,injection+'\n'+marker):v;};
