// DatoYa 2.0 — capa Chile-only. En beta: correo verificado + móvil chileno registrado.
const fs=require('fs'),path=require('path');
const serverFile=path.join(__dirname,'server.js'),orig=fs.readFileSync;
const injection=`
// ============ SEGURIDAD CHILE ============
try{db.exec(\`CREATE TABLE IF NOT EXISTS security_events (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, event_type TEXT NOT NULL, risk INTEGER NOT NULL DEFAULT 0, detail TEXT, ip_hint TEXT, created_at TEXT DEFAULT (datetime('now')));\`);}catch(e){console.error('[DatoYa] seguridad schema',e.message)}
function dyClientIp(req){return String(req.headers['cf-connecting-ip']||req.headers['x-forwarded-for']||req.ip||'').split(',')[0].trim().slice(0,80)}
function dyCountry(req){return String(req.headers['cf-ipcountry']||req.headers['x-vercel-ip-country']||req.headers['x-country-code']||'').trim().toUpperCase().slice(0,2)}
function dyMaskIp(ip){return String(ip||'').replace(/(\\d+)\\.(\\d+)\\.(\\d+)\\.\\d+/,'$1.$2.$3.x').slice(0,80)}
function dyLogSecurity(req,type,risk,detail,userId){try{db.prepare('INSERT INTO security_events(user_id,event_type,risk,detail,ip_hint) VALUES(?,?,?,?,?)').run(userId||req.user?.id||null,type,risk,String(detail||'').slice(0,500),dyMaskIp(dyClientIp(req)));}catch(e){console.error('[DatoYa] security log',e.message)}}
function dyNormalizePhone(phone){let p=String(phone||'').replace(/[\\s()-]/g,'');if(p.startsWith('9'))p='+56'+p;else if(p.startsWith('569'))p='+'+p;else if(p.startsWith('56'))p='+'+p;return p}
function dyChilePhone(phone){return /^\\+569\\d{8}$/.test(dyNormalizePhone(phone))}
function dySessionUser(req){try{const token=req.cookies.datoya_token;if(!token)return null;return db.prepare(\`SELECT u.id,u.phone,u.email,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at > datetime('now') AND u.is_active=1\`).get(token)||null}catch(_){return null}}
function dyEmailVerified(userId){try{return Boolean(db.prepare('SELECT id FROM auth_email_verifications WHERE user_id=? AND verified_at IS NOT NULL ORDER BY id DESC LIMIT 1').get(userId))}catch(_){return false}}
function dyChileGate(req,res,next){const country=dyCountry(req);if(country&&country!=='CL'){const u=dySessionUser(req);dyLogSecurity(req,'pais_fuera_chile',90,'País informado por infraestructura: '+country,u?.id);return res.status(403).json({error:'DatoYa opera exclusivamente en Chile. Si estás en Chile y ves este mensaje, contacta a soporte.'});}next()}
function dyBetaTrustGate(req,res,next){if(!['POST','PUT','PATCH'].includes(req.method))return next();const u=dySessionUser(req);if(!u)return next();if(!u.phone){dyLogSecurity(req,'telefono_faltante',45,'Operación sensible sin teléfono registrado',u.id);return res.status(403).json({error:'Por seguridad, agrega un número móvil chileno a tu cuenta antes de continuar.'});}if(!dyChilePhone(u.phone)){dyLogSecurity(req,'telefono_no_chileno',70,'Formato de teléfono no corresponde a móvil chileno',u.id);return res.status(403).json({error:'DatoYa requiere un número móvil chileno válido (+56 9) para esta acción.'});}if(!dyEmailVerified(u.id)){dyLogSecurity(req,'correo_no_verificado',55,'Operación sensible con correo pendiente de verificación',u.id);return res.status(403).json({error:'Por seguridad, verifica tu correo electrónico antes de continuar.'});}next()}
app.use('/api/requests',dyChileGate,dyBetaTrustGate);app.use('/api/quotes',dyChileGate,dyBetaTrustGate);app.use('/api/conversations',dyChileGate,dyBetaTrustGate);app.use('/api/jobs',dyChileGate,dyBetaTrustGate);
app.post('/api/security/phone',auth,(req,res)=>{const p=dyNormalizePhone(req.body?.phone);if(!dyChilePhone(p))return res.status(400).json({error:'Ingresa un celular chileno válido, por ejemplo +56 9XXXXXXXX.'});db.prepare('UPDATE users SET phone=? WHERE id=?').run(p,req.user.id);try{db.prepare('DELETE FROM phone_verifications WHERE user_id=?').run(req.user.id)}catch(_){}try{db.prepare('DELETE FROM auth_phone_verifications WHERE user_id=?').run(req.user.id)}catch(_){}const wp=getWorkerByUser(req.user.id);if(wp)try{db.prepare('UPDATE worker_profiles SET verified_phone=0 WHERE id=?').run(wp.id)}catch(_){}dyLogSecurity(req,'telefono_chileno_registrado',10,'Móvil chileno registrado; no se presenta como verificado',req.user.id);res.json({ok:true,phone:p,verified:false,sms_enabled:false,message:'Número chileno guardado. En esta beta la seguridad usa correo verificado + controles antifraude.'})});
app.get('/api/security/status',auth,(req,res)=>{const u=db.prepare('SELECT phone,email FROM users WHERE id=?').get(req.user.id);res.json({chile_only:true,phone:u?.phone||null,phone_present:Boolean(u?.phone),phone_chilean:dyChilePhone(u?.phone),phone_verified:false,email:u?.email||null,email_verified:dyEmailVerified(req.user.id),sms_enabled:false,beta_security:'email+chilean_phone+risk'})});
app.get('/api/admin/security-events',auth,requireRole('admin'),(req,res)=>{const events=db.prepare(\`SELECT se.*,u.name,u.email FROM security_events se LEFT JOIN users u ON u.id=se.user_id ORDER BY se.id DESC LIMIT 200\`).all();res.json({events,sms_enabled:false,beta_security:'email+chilean_phone+risk'})});
`;
fs.readFileSync=function(file,options){const v=orig.call(fs,file,options);if(path.resolve(String(file))!==path.resolve(serverFile)||typeof v!=='string')return v;if(v.includes('// ============ SEGURIDAD CHILE ============'))return v;const marker='// ============ AUTH ============';return v.includes(marker)?v.replace(marker,injection+'\n'+marker):v;};
