// DatoYa 2.0 — capa de seguridad Chile-only + verificación móvil chilena
const fs=require('fs'),path=require('path');
const serverFile=path.join(__dirname,'server.js'),orig=fs.readFileSync;
const injection=`
// ============ SEGURIDAD CHILE ============
try{db.exec(\`CREATE TABLE IF NOT EXISTS security_events (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, event_type TEXT NOT NULL, risk INTEGER NOT NULL DEFAULT 0, detail TEXT, ip_hint TEXT, created_at TEXT DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS phone_verifications (user_id INTEGER PRIMARY KEY, phone TEXT NOT NULL, verified_at TEXT, last_sent_at TEXT, send_count INTEGER NOT NULL DEFAULT 0, failed_checks INTEGER NOT NULL DEFAULT 0);\`);}catch(e){console.error('[DatoYa] seguridad schema',e.message)}
function dyClientIp(req){return String(req.headers['cf-connecting-ip']||req.headers['x-forwarded-for']||req.ip||'').split(',')[0].trim().slice(0,80)}
function dyCountry(req){return String(req.headers['cf-ipcountry']||req.headers['x-vercel-ip-country']||req.headers['x-country-code']||'').trim().toUpperCase().slice(0,2)}
function dyMaskIp(ip){return String(ip||'').replace(/(\\d+)\\.(\\d+)\\.(\\d+)\\.\\d+/,'$1.$2.$3.x').slice(0,80)}
function dyLogSecurity(req,type,risk,detail,userId){try{db.prepare('INSERT INTO security_events(user_id,event_type,risk,detail,ip_hint) VALUES(?,?,?,?,?)').run(userId||req.user?.id||null,type,risk,String(detail||'').slice(0,500),dyMaskIp(dyClientIp(req)));}catch(e){console.error('[DatoYa] security log',e.message)}}
function dyNormalizePhone(phone){let p=String(phone||'').replace(/[\\s()-]/g,'');if(p.startsWith('9'))p='+56'+p;else if(p.startsWith('569'))p='+'+p;else if(p.startsWith('56'))p='+'+p;return p}
function dyChilePhone(phone){return /^\\+569\\d{8}$/.test(dyNormalizePhone(phone))}
function dySmsEnabled(){return Boolean(process.env.TWILIO_ACCOUNT_SID&&process.env.TWILIO_AUTH_TOKEN&&process.env.TWILIO_VERIFY_SERVICE_SID)}
function dySessionUser(req){try{const token=req.cookies.datoya_token;if(!token)return null;return db.prepare(\`SELECT u.id,u.phone,u.role FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at > datetime('now') AND u.is_active=1\`).get(token)||null}catch(_){return null}}
function dyPhoneVerified(userId,phone){try{const v=db.prepare('SELECT phone,verified_at FROM phone_verifications WHERE user_id=?').get(userId);return Boolean(v?.verified_at&&dyNormalizePhone(v.phone)===dyNormalizePhone(phone))}catch(_){return false}}
function dyChileGate(req,res,next){const country=dyCountry(req);if(country&&country!=='CL'){const u=dySessionUser(req);dyLogSecurity(req,'pais_fuera_chile',90,'País informado por infraestructura: '+country,u?.id);return res.status(403).json({error:'DatoYa opera exclusivamente en Chile. Si estás en Chile y ves este mensaje, contacta a soporte.'});}next()}
function dyPhoneRisk(req,res,next){if(!['POST','PUT','PATCH'].includes(req.method))return next();const u=dySessionUser(req);if(!u)return next();if(!u.phone){dyLogSecurity(req,'telefono_faltante',45,'Intento de operación sensible sin teléfono registrado',u.id);return res.status(403).json({error:'Por seguridad, agrega un número móvil chileno a tu cuenta antes de continuar.'});}if(!dyChilePhone(u.phone)){dyLogSecurity(req,'telefono_no_chileno',70,'Formato de teléfono no corresponde a móvil chileno',u.id);return res.status(403).json({error:'DatoYa requiere un número móvil chileno válido (+56 9) para esta acción.'});}if(dySmsEnabled()&&!dyPhoneVerified(u.id,u.phone)){dyLogSecurity(req,'telefono_no_verificado',55,'Operación sensible con teléfono pendiente de verificación SMS',u.id);return res.status(403).json({error:'Verifica tu número móvil chileno por SMS antes de continuar.'});}next()}
app.use('/api/requests',dyChileGate,dyPhoneRisk);
app.use('/api/quotes',dyChileGate,dyPhoneRisk);
app.use('/api/conversations/start',dyChileGate,dyPhoneRisk);
app.post('/api/security/phone',auth,(req,res)=>{const p=dyNormalizePhone(req.body?.phone);if(!dyChilePhone(p))return res.status(400).json({error:'Ingresa un celular chileno válido, por ejemplo +56 9XXXXXXXX.'});const old=db.prepare('SELECT phone FROM users WHERE id=?').get(req.user.id);db.prepare('UPDATE users SET phone=? WHERE id=?').run(p,req.user.id);if(dyNormalizePhone(old?.phone)!==p){db.prepare('DELETE FROM phone_verifications WHERE user_id=?').run(req.user.id);}dyLogSecurity(req,'telefono_chileno_registrado',10,'Número chileno registrado'+(dySmsEnabled()?'; requiere verificación SMS':'; proveedor SMS aún no conectado'),req.user.id);res.json({ok:true,phone:p,verified:dyPhoneVerified(req.user.id,p),sms_enabled:dySmsEnabled(),message:dySmsEnabled()?'Número guardado. Ahora solicita tu código SMS.':'Número guardado. La verificación SMS quedará disponible al conectar el proveedor.'})});
app.post('/api/security/phone/start',auth,async(req,res)=>{if(!dySmsEnabled())return res.status(503).json({error:'La verificación SMS todavía no está habilitada.'});const u=db.prepare('SELECT phone FROM users WHERE id=?').get(req.user.id);if(!dyChilePhone(u?.phone))return res.status(400).json({error:'Primero agrega un número móvil chileno válido.'});const p=dyNormalizePhone(u.phone),prev=db.prepare('SELECT * FROM phone_verifications WHERE user_id=?').get(req.user.id);if(prev?.verified_at&&dyNormalizePhone(prev.phone)===p)return res.json({ok:true,verified:true,message:'Tu teléfono ya está verificado.'});if(prev?.last_sent_at){const elapsed=Date.now()-new Date(String(prev.last_sent_at).replace(' ','T')+'Z').getTime();if(Number.isFinite(elapsed)&&elapsed<60000)return res.status(429).json({error:'Espera un minuto antes de solicitar otro código.'});}
 try{const sid=process.env.TWILIO_ACCOUNT_SID,token=process.env.TWILIO_AUTH_TOKEN,service=process.env.TWILIO_VERIFY_SERVICE_SID;const body=new URLSearchParams({To:p,Channel:'sms'});const r=await fetch('https://verify.twilio.com/v2/Services/'+encodeURIComponent(service)+'/Verifications',{method:'POST',headers:{Authorization:'Basic '+Buffer.from(sid+':'+token).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body});const data=await r.json().catch(()=>({}));if(!r.ok){console.error('[DatoYa] Twilio Verify start',r.status,data);dyLogSecurity(req,'sms_envio_error',35,'Proveedor SMS rechazó el envío',req.user.id);return res.status(502).json({error:'No pudimos enviar el SMS. Intenta nuevamente en unos minutos.'});}db.prepare(\`INSERT INTO phone_verifications(user_id,phone,verified_at,last_sent_at,send_count,failed_checks) VALUES(?,?,NULL,datetime('now'),1,0) ON CONFLICT(user_id) DO UPDATE SET phone=excluded.phone,verified_at=NULL,last_sent_at=datetime('now'),send_count=phone_verifications.send_count+1,failed_checks=0\`).run(req.user.id,p);dyLogSecurity(req,'sms_codigo_enviado',10,'Código SMS enviado al número registrado',req.user.id);res.json({ok:true,message:'Te enviamos un código por SMS.'});}catch(e){console.error('[DatoYa] SMS start',e);res.status(502).json({error:'No pudimos conectar con el servicio de SMS.'})}});
app.post('/api/security/phone/check',auth,async(req,res)=>{if(!dySmsEnabled())return res.status(503).json({error:'La verificación SMS todavía no está habilitada.'});const code=String(req.body?.code||'').replace(/\\D/g,'').slice(0,10);if(code.length<4)return res.status(400).json({error:'Ingresa el código recibido por SMS.'});const u=db.prepare('SELECT phone FROM users WHERE id=?').get(req.user.id),p=dyNormalizePhone(u?.phone);const row=db.prepare('SELECT * FROM phone_verifications WHERE user_id=?').get(req.user.id);if(!row||dyNormalizePhone(row.phone)!==p)return res.status(400).json({error:'Solicita primero un código para este número.'});if(Number(row.failed_checks||0)>=5)return res.status(429).json({error:'Demasiados intentos incorrectos. Solicita un nuevo código.'});
 try{const sid=process.env.TWILIO_ACCOUNT_SID,token=process.env.TWILIO_AUTH_TOKEN,service=process.env.TWILIO_VERIFY_SERVICE_SID;const body=new URLSearchParams({To:p,Code:code});const r=await fetch('https://verify.twilio.com/v2/Services/'+encodeURIComponent(service)+'/VerificationCheck',{method:'POST',headers:{Authorization:'Basic '+Buffer.from(sid+':'+token).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},body});const data=await r.json().catch(()=>({}));if(r.ok&&data.status==='approved'){db.prepare(\`UPDATE phone_verifications SET verified_at=datetime('now'),failed_checks=0 WHERE user_id=?\`).run(req.user.id);const wp=getWorkerByUser(req.user.id);if(wp)try{db.prepare('UPDATE worker_profiles SET verified_phone=1 WHERE id=?').run(wp.id)}catch(_){}dyLogSecurity(req,'telefono_sms_verificado',5,'Número móvil chileno verificado por SMS',req.user.id);return res.json({ok:true,verified:true,message:'Teléfono verificado correctamente.'});}db.prepare('UPDATE phone_verifications SET failed_checks=failed_checks+1 WHERE user_id=?').run(req.user.id);dyLogSecurity(req,'sms_codigo_incorrecto',30,'Código SMS incorrecto',req.user.id);res.status(400).json({error:'El código no es correcto o ya venció.'});}catch(e){console.error('[DatoYa] SMS check',e);res.status(502).json({error:'No pudimos validar el código en este momento.'})}});
app.get('/api/security/status',auth,(req,res)=>{const u=db.prepare('SELECT phone FROM users WHERE id=?').get(req.user.id);res.json({chile_only:true,phone:u?.phone||null,phone_present:Boolean(u?.phone),phone_chilean:dyChilePhone(u?.phone),phone_verified:dyPhoneVerified(req.user.id,u?.phone),sms_enabled:dySmsEnabled()})});
app.get('/api/admin/security-events',auth,requireRole('admin'),(req,res)=>{const events=db.prepare(\`SELECT se.*,u.name,u.email FROM security_events se LEFT JOIN users u ON u.id=se.user_id ORDER BY se.id DESC LIMIT 200\`).all();res.json({events,sms_enabled:dySmsEnabled()})});
`;
fs.readFileSync=function(file,options){const v=orig.call(fs,file,options);if(path.resolve(String(file))!==path.resolve(serverFile)||typeof v!=='string')return v;if(v.includes('// ============ SEGURIDAD CHILE ============'))return v;const marker='// ============ AUTH ============';return v.includes(marker)?v.replace(marker,injection+'\n'+marker):v;};
