// APIs comerciales de promociones, plan Impulso e Impulso Ahora.
const fs=require('fs'),path=require('path');const serverPath=path.resolve(__dirname,'server.js'),originalRead=fs.readFileSync;
function inject(source){const marker='// ============ MISC ============';if(!source.includes(marker))throw new Error('No se encontró montaje comercial');if(source.includes('DATOYA COMMERCE GROWTH V1'))return source;const block=`
// ============ DATOYA COMMERCE GROWTH V1 ============
function commerceDate(value){const d=new Date(String(value||'').replace(' ','T')+(String(value||'').includes('Z')?'':'Z'));return Number.isNaN(d.getTime())?null:d;}
function impulseState(row,now=new Date()){
  if(row.status==='cancelled')return 'cancelled';const start=commerceDate(row.starts_at),end=commerceDate(row.ends_at);
  if(Number(row.stock_remaining)<=0)return 'sold_out';if(start&&now<start)return 'scheduled';if(end&&now>=end)return 'ended';
  const low=Number(row.stock_initial)>0&&Number(row.stock_remaining)<=Math.max(5,Math.ceil(Number(row.stock_initial)*0.2));return low?'low_stock':'active';
}
function syncImpulse(row){const status=impulseState(row);if(status!==row.status){db.prepare("UPDATE impulse_now SET status=?,updated_at=datetime('now') WHERE id=?").run(status,row.id);row.status=status;}return row;}
function businessImpulseActive(id){const row=db.prepare("SELECT id FROM business_subscriptions WHERE business_id=? AND status='active' AND (expires_at IS NULL OR expires_at>datetime('now')) ORDER BY id DESC LIMIT 1").get(id);return !!row;}
function publicImpulse(row,lat,lng){const x={...row};if(Number.isFinite(lat)&&Number.isFinite(lng)&&x.latitude!=null&&x.longitude!=null)x.distance_km=Math.round(businessDistanceKm(lat,lng,Number(x.latitude),Number(x.longitude))*10)/10;delete x.latitude;delete x.longitude;return x;}
app.get('/api/business-plans',(req,res)=>res.json({plans:{free:{code:'free',label:'DatoYa Gratis'},impulso:{code:'impulso',label:'DatoYa Impulso',slogan:'Haz que tu negocio llegue más lejos.',monthly:Number(getSetting('business_impulso_monthly_clp','9990')),annual:Number(getSetting('business_impulso_annual_clp','99900'))}}}));
app.get('/api/promotions',(req,res)=>{const lat=Number(req.query.lat),lng=Number(req.query.lng),radius=[1,3,5,10].includes(Number(req.query.radius))?Number(req.query.radius):5,hasGps=Number.isFinite(lat)&&Number.isFinite(lng),now=new Date();let rows=db.prepare("SELECT p.*,b.name AS business_name,b.slug AS business_slug,b.latitude,b.longitude FROM promotions p JOIN businesses b ON b.id=p.business_id WHERE p.active=1 AND b.status='active' ORDER BY p.created_at DESC LIMIT 100").all().filter(x=>commerceDate(x.starts_at)<=now&&commerceDate(x.ends_at)>now);rows=rows.map(x=>publicImpulse(x,lat,lng)).filter(x=>!hasGps||x.distance_km==null||x.distance_km<=radius);res.json({promotions:rows});});
app.post('/api/businesses/:id/promotions',auth,(req,res)=>{const b=ownerBusiness(req.user.id,Number(req.params.id));if(!b)return res.status(404).json({error:'Negocio no encontrado'});const x=req.body||{},title=String(x.title||'').trim(),start=commerceDate(x.starts_at),end=commerceDate(x.ends_at);if(title.length<2||!start||!end||end<=start)return res.status(400).json({error:'Título y vigencia válida son obligatorios'});db.prepare('INSERT INTO promotions(business_id,product_id,title,description,image_url,price,previous_price,starts_at,ends_at,active) VALUES(?,?,?,?,?,?,?,?,?,1)').run(b.id,x.product_id||null,title,x.description||null,x.image_url||null,x.price==null?null:Number(x.price),x.previous_price==null?null:Number(x.previous_price),x.starts_at,x.ends_at);res.status(201).json({promotion:db.prepare('SELECT * FROM promotions WHERE business_id=? ORDER BY id DESC LIMIT 1').get(b.id)});});
app.get('/api/impulse-now',(req,res)=>{const lat=Number(req.query.lat),lng=Number(req.query.lng),radius=[1,3,5,10].includes(Number(req.query.radius))?Number(req.query.radius):5,hasGps=Number.isFinite(lat)&&Number.isFinite(lng);let rows=db.prepare("SELECT i.*,b.name AS business_name,b.slug AS business_slug,b.latitude,b.longitude FROM impulse_now i JOIN businesses b ON b.id=i.business_id WHERE b.status='active' AND i.status<>'cancelled' ORDER BY i.starts_at DESC LIMIT 200").all().map(syncImpulse).filter(x=>['active','low_stock'].includes(x.status)).map(x=>publicImpulse(x,lat,lng)).filter(x=>!hasGps||x.distance_km==null||x.distance_km<=radius).sort((a,b)=>(a.distance_km??99999)-(b.distance_km??99999));res.json({impulses:rows});});
app.get('/api/my/businesses/:id/impulse-now',auth,(req,res)=>{const b=ownerBusiness(req.user.id,Number(req.params.id));if(!b)return res.status(404).json({error:'Negocio no encontrado'});res.json({eligible:businessImpulseActive(b.id),impulses:db.prepare('SELECT * FROM impulse_now WHERE business_id=? ORDER BY id DESC').all(b.id).map(syncImpulse)});});
app.post('/api/businesses/:id/impulse-now',auth,(req,res)=>{const b=ownerBusiness(req.user.id,Number(req.params.id));if(!b)return res.status(404).json({error:'Negocio no encontrado'});if(!businessImpulseActive(b.id))return res.status(403).json({error:'⚡ Impulso Ahora requiere DatoYa Impulso activo'});const x=req.body||{},title=String(x.title||'').trim(),price=Number(x.price),stock=Number(x.stock_initial),start=commerceDate(x.starts_at),end=commerceDate(x.ends_at);if(title.length<2||!Number.isInteger(price)||price<0||!Number.isInteger(stock)||stock<1||!start||!end||end<=start)return res.status(400).json({error:'Oferta, precio, stock y horario válido son obligatorios'});const status=impulseState({status:'scheduled',stock_initial:stock,stock_remaining:stock,starts_at:x.starts_at,ends_at:x.ends_at});db.prepare('INSERT INTO impulse_now(business_id,product_id,title,description,image_url,price,previous_price,stock_initial,stock_remaining,starts_at,ends_at,until_sold_out,pickup_enabled,delivery_enabled,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(b.id,x.product_id||null,title,x.description||null,x.image_url||null,price,x.previous_price==null?null:Number(x.previous_price),stock,stock,x.starts_at,x.ends_at,Number(x.until_sold_out!==false),Number(Boolean(x.pickup_enabled)),Number(Boolean(x.delivery_enabled)),status);res.status(201).json({impulse:db.prepare('SELECT * FROM impulse_now WHERE business_id=? ORDER BY id DESC LIMIT 1').get(b.id)});});
app.put('/api/businesses/:businessId/impulse-now/:id',auth,(req,res)=>{const b=ownerBusiness(req.user.id,Number(req.params.businessId));if(!b)return res.status(404).json({error:'Negocio no encontrado'});const row=db.prepare('SELECT * FROM impulse_now WHERE id=? AND business_id=?').get(Number(req.params.id),b.id);if(!row)return res.status(404).json({error:'Impulso no encontrado'});const stock=req.body?.stock_remaining==null?Number(row.stock_remaining):Number(req.body.stock_remaining);if(!Number.isInteger(stock)||stock<0||stock>Number(row.stock_initial))return res.status(400).json({error:'Stock restante inválido'});const forced=req.body?.status==='cancelled'?'cancelled':row.status;const status=impulseState({...row,stock_remaining:stock,status:forced});db.prepare("UPDATE impulse_now SET stock_remaining=?,status=?,updated_at=datetime('now') WHERE id=?").run(stock,status,row.id);res.json({impulse:{...row,stock_remaining:stock,status}});});
app.post('/api/admin/businesses/:id/impulso-grant',auth,requireRole('admin'),(req,res)=>{const b=db.prepare('SELECT * FROM businesses WHERE id=?').get(Number(req.params.id));if(!b)return res.status(404).json({error:'Negocio no encontrado'});const days=Math.min(365,Math.max(1,Number(req.body?.days)||7)),reason=String(req.body?.reason||'trial').slice(0,80),expires=new Date(Date.now()+days*86400000).toISOString().slice(0,19).replace('T',' ');db.prepare("UPDATE business_subscriptions SET status='cancelled',updated_at=datetime('now') WHERE business_id=? AND status='active'").run(b.id);db.prepare("INSERT INTO business_subscriptions(business_id,plan_code,status,source,expires_at,auto_renew,amount) VALUES(?,'impulso','active','grant',?,0,0)").run(b.id,expires);db.prepare('INSERT INTO subscription_grants(business_id,granted_by,reason,days,expires_at) VALUES(?,?,?,?,?)').run(b.id,req.user.id,reason,days,expires);db.prepare("UPDATE businesses SET plan='impulso',updated_at=datetime('now') WHERE id=?").run(b.id);res.json({ok:true,expires_at:expires,auto_renew:false});});
// ======================================================
`;return source.replace(marker,block+'\n'+marker);}
fs.readFileSync=function(file,options){const out=originalRead.call(this,file,options);if(path.resolve(file)===serverPath&&typeof out==='string')return inject(out);return out;};
