// DatoYa — mapa de viaje GPS para cliente (DEMO)
(function(){
  const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  let leafletPromise;
  function loadLeaflet(){if(leafletPromise)return leafletPromise;leafletPromise=new Promise((resolve,reject)=>{if(window.L)return resolve();const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});return leafletPromise}
  async function draw(host,travel){
    const p=travel?.latest;if(!p||p.lat==null||p.lng==null)return;
    try{await loadLeaflet();const id='gpsmap-'+Math.random().toString(36).slice(2);host.innerHTML=`<div class="gps-map-title"><b>📍 El profesional va en camino</b><span>Ubicación aproximada</span></div><div id="${id}" class="gps-leaflet"></div><div class="gps-map-meta">Última actualización: ${esc(new Date(String(p.created_at).replace(' ','T')+'Z').toLocaleTimeString('es-CL',{hour:'2-digit',minute:'2-digit',second:'2-digit'}))}${p.accuracy?` · precisión ±${Math.round(p.accuracy)} m`:''}</div>`;const map=L.map(id,{zoomControl:true,attributionControl:true}).setView([Number(p.lat),Number(p.lng)],15);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);L.marker([Number(p.lat),Number(p.lng)]).addTo(map).bindPopup('Ubicación aproximada del profesional').openPopup();setTimeout(()=>map.invalidateSize(),100)}catch(_){host.innerHTML=`<div class="gps-map-fallback">📍 El profesional va en camino<br><small>Ubicación aproximada disponible.</small></div>`}}
  async function refresh(){if(!location.hash.startsWith('#/trabajos'))return;document.querySelectorAll('[data-job-id]').forEach(async card=>{const id=card.dataset.jobId;let host=card.querySelector('.gps-client-map');if(!host){host=document.createElement('div');host.className='gps-client-map';card.appendChild(host)}try{const r=await fetch(`/api/jobs/${id}/travel`,{credentials:'same-origin'});if(!r.ok)return;const d=await r.json();if(d.tracking&&d.latest){if(host.dataset.last!==String(d.latest.id)){host.dataset.last=String(d.latest.id);draw(host,d)}}else if(d.session?.status==='LLEGADA_REGISTRADA'){host.innerHTML='<div class="gps-arrived">🏁 <b>El profesional ha llegado</b><span>El seguimiento GPS terminó automáticamente.</span></div>'}}catch(_){}})}
  const css=`<style id="gps-map-ui-css">.gps-client-map{margin-top:12px}.gps-map-title{display:flex;justify-content:space-between;gap:8px;align-items:center;font-size:13px;margin-bottom:7px}.gps-map-title span,.gps-map-meta{font-size:11px;color:#64748b}.gps-leaflet{height:230px;border-radius:13px;overflow:hidden;border:1px solid #dbe4f0}.gps-map-meta{margin-top:5px}.gps-map-fallback,.gps-arrived{padding:16px;border:1px solid #dbe4f0;border-radius:13px;background:#f8fafc}.gps-arrived{background:#ecfdf5;border-color:#a7f3d0}.gps-arrived span{display:block;font-size:12px;color:#475569;margin-top:4px}</style>`;document.head.insertAdjacentHTML('beforeend',css);
  setInterval(refresh,10000);addEventListener('hashchange',()=>setTimeout(refresh,300));setTimeout(refresh,800);
})();
