// DatoYa 2.0 — inicio y búsqueda enfocados en conversión y confianza.
(function(){
 if(typeof routes==='undefined')return;
 function specialtyLine(w){const items=Array.isArray(w.specialties)?w.specialties:[];if(items.length<2)return '';return `<div class="small muted" style="margin-top:5px">También: ${items.slice(1,4).map(s=>`${esc(s.icon||'🛠️')} ${esc(s.name)}`).join(' · ')}</div>`;}
 function cleanCard(w){const verified=w.verified_identity?'<span class="badge-v">✓ Verificado</span>':'';const pro=w.is_pro?'<span class="badge-pro">PRO</span>':'';return `<div class="wcard"><div class="wcard-top">${avatar(w.name,w.avatar_color,w.status)}<div class="wcard-info"><h3>${esc(w.name)} ${verified} ${pro}</h3><div class="oficio">${esc(w.oficio||'Profesional')}</div>${specialtyLine(w)}<div class="wmeta"><span>${estrellas(w.rating_avg||0,w.rating_count||0)}</span><span>🛠️ ${Number(w.jobs_completed||0)} trabajos</span><span>📍 ${esc(w.comuna||'')}</span></div></div></div><div class="wcard-actions"><a class="btn btn-outline btn-sm" href="#/trabajador/${w.id}">Ver perfil</a><button class="btn btn-primary btn-sm" onclick="solicitarDirecto(${w.id})">Solicitar servicio</button></div></div>`;}
 function homeCategories(categories){const preferred=['Gasfíter','Electricista','Pintura','Construcción','Jardinería','Limpieza','Cámaras y Seguridad'];const selected=preferred.map(name=>categories.find(category=>category.name===name)).filter(Boolean);return selected.concat(categories.filter(category=>!selected.some(item=>Number(item.id)===Number(category.id))).slice(0,9));}
 async function home(){const{categories}=await api('/categories');CATS=categories;const mainCategories=homeCategories(categories);let feat=(await api('/workers?featured=1')).workers;if(!feat.length)feat=(await api('/workers')).workers.slice(0,4);view.innerHTML=`<div class="hero"><div class="small" style="font-weight:800;margin-bottom:8px">🛡️ Servicios con respaldo DatoYa</div><h1>¿Qué necesitas solucionar?</h1><p>Elige un servicio y encuentra profesionales realmente vinculados a esa especialidad.</p><form class="searchbox" onsubmit="event.preventDefault();location.hash='#/buscar?q='+encodeURIComponent(this.q.value)"><input name="q" placeholder="Buscar gasfíter, electricista, cámaras…" autocomplete="off"><button class="btn btn-accent">🔍 Buscar</button></form></div><h2 class="section-title">Categorías</h2><div class="cat-grid">${mainCategories.map(c=>`<a class="cat-item" href="#/cerca?cat=${c.id}" aria-label="Buscar profesionales de ${esc(c.name)} cerca de ti"><span>${c.icon}</span>${esc(c.name)}</a>`).join('')}<a class="cat-item" href="#/buscar"><span>➕</span>Ver todas</a></div>${feat.length?`<h2 class="section-title">Profesionales</h2><div class="cards">${feat.map(cleanCard).join('')}</div>`:''}`;}
 async function search(){const q=new URLSearchParams(location.hash.split('?')[1]||''),p=new URLSearchParams();if(q.get('q'))p.set('q',q.get('q'));if(q.get('cat'))p.set('category_id',q.get('cat'));if(q.get('comuna'))p.set('comuna_id',q.get('comuna'));if(q.get('verif'))p.set('verified','1');const[{workers},{comunas}]=await Promise.all([api('/workers?'+p),api('/comunas?region_id=16')]);view.innerHTML=`<h2 class="section-title">Encontrar profesionales</h2><div class="card"><form onsubmit="event.preventDefault();const p=new URLSearchParams();if(this.q.value)p.set('q',this.q.value);if(this.comuna.value)p.set('comuna',this.comuna.value);if(this.verif.checked)p.set('verif','1');location.hash='#/buscar?'+p"><div class="field"><label>¿Qué necesitas?</label><input name="q" value="${esc(q.get('q')||'')}" placeholder="Oficio o servicio"></div><div class="field"><label>Comuna</label><select name="comuna"><option value="">Todas las comunas</option>${comunas.map(c=>`<option value="${c.id}" ${String(c.id)===String(q.get('comuna'))?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><label class="small"><input type="checkbox" name="verif" ${q.get('verif')?'checked':''}> Mostrar solo identidad verificada</label><button class="btn btn-primary btn-block" style="margin-top:12px">🔍 Buscar</button></form></div><div class="row between" style="margin:16px 2px 8px"><b>${workers.length} resultado${workers.length===1?'':'s'}</b><span class="small muted">Compara antes de solicitar</span></div><div class="cards">${workers.length?workers.map(cleanCard).join(''):'<div class="empty"><b>No encontramos profesionales con esos filtros.</b><br><span class="small">Prueba otra comuna o una búsqueda más general.</span></div>'}</div>`;}
 routes['']=home;
})();
