// DatoYa 2.0 — inicio y búsqueda enfocados en conversión, personas y confianza.
(function(){
 if(typeof routes==='undefined')return;
 function specialtyLine(w){const items=Array.isArray(w.specialties)?w.specialties:[];if(items.length<2)return '';return `<div class="small muted" style="margin-top:5px">También: ${items.slice(1,4).map(s=>`${esc(s.icon||'🛠️')} ${esc(s.name)}`).join(' · ')}</div>`;}
 function cleanCard(w){const verified=w.verified_identity?'<span class="badge-v">✓ Verificado</span>':'';const pro=w.is_pro?'<span class="badge-pro">PRO</span>':'';return `<div class="wcard"><div class="wcard-top">${avatar(w.name,w.avatar_color,w.status)}<div class="wcard-info"><h3>${esc(w.name)} ${verified} ${pro}</h3><div class="oficio">${esc(w.oficio||'Profesional')}</div>${specialtyLine(w)}<div class="wmeta"><span>${estrellas(w.rating_avg||0,w.rating_count||0)}</span><span>🛠️ ${Number(w.jobs_completed||0)} trabajos</span><span>📍 ${esc(w.comuna||'')}</span></div></div></div><div class="wcard-actions"><a class="btn btn-outline btn-sm" href="#/trabajador/${w.id}">Ver perfil</a><button class="btn btn-primary btn-sm" onclick="solicitarDirecto(${w.id})">Solicitar servicio</button></div></div>`;}
 function homeCategories(categories){const preferred=['Gasfíter','Electricista','Pintura','Construcción','Jardinería','Limpieza','Cámaras y Seguridad'];const selected=preferred.map(name=>categories.find(category=>category.name===name)).filter(Boolean);return selected.concat(categories.filter(category=>!selected.some(item=>Number(item.id)===Number(category.id))).slice(0,7));}
 async function home(){
  const{categories}=await api('/categories');CATS=categories;const mainCategories=homeCategories(categories);
  let feat=[];try{feat=(await api('/workers?featured=1')).workers||[];if(!feat.length)feat=((await api('/workers')).workers||[]).slice(0,3);}catch(_){feat=[];}
  const professionalCta=!ME?`<section class="dy-pro-cta"><div><span class="dy-eyebrow">PARA PROFESIONALES</span><h2>¿Buscas nuevas oportunidades?</h2><p>Muestra tus trabajos, construye tu reputación y encuentra clientes que necesitan lo que sabes hacer.</p></div><a class="btn btn-primary" href="#/registro">Crear perfil profesional</a></section>`:'';
  view.innerHTML=`<section class="dy-home-hero"><span class="dy-eyebrow">DATOYA CERCA DE TI</span><h1>¿Qué necesitas solucionar hoy?</h1><p>Encuentra profesionales, revisa su experiencia y mantén un registro claro de lo que contratas.</p><form class="dy-home-search" onsubmit="event.preventDefault();const q=this.q.value.trim();location.hash=q?'#/buscar?q='+encodeURIComponent(q):'#/buscar'"><span aria-hidden="true">🔍</span><input name="q" placeholder="Gasfíter, electricista, cámaras…" autocomplete="off" aria-label="¿Qué servicio necesitas?"><button type="submit">Buscar</button></form></section><section class="dy-home-section"><div class="dy-section-head"><div><span class="dy-eyebrow">SERVICIOS</span><h2>¿Qué necesitas?</h2></div><a href="#/buscar">Ver todas</a></div><div class="dy-cat-grid">${mainCategories.map(c=>`<a class="dy-cat" href="#/cerca?cat=${c.id}" aria-label="Buscar profesionales de ${esc(c.name)} cerca de ti"><span class="dy-cat-icon">${c.icon}</span><b>${esc(c.name)}</b><small>Ver profesionales</small></a>`).join('')}</div></section>${feat.length?`<section class="dy-home-section"><div class="dy-section-head"><div><span class="dy-eyebrow">PERSONAS QUE PUEDEN AYUDARTE</span><h2>Profesionales</h2></div><a href="#/buscar">Explorar</a></div><div class="cards">${feat.map(cleanCard).join('')}</div></section>`:''}<section class="dy-trust"><div class="dy-trust-icon">🛡️</div><div><b>Contrata con más claridad</b><p>Cotizaciones, cambios aceptados y antecedentes del trabajo pueden quedar registrados en DatoYa.</p></div></section>${professionalCta}<style>
.dy-home-hero{margin:14px 0 26px;padding:28px 22px;border-radius:28px;background:linear-gradient(145deg,#123da9,#245ddd);color:#fff;box-shadow:0 14px 35px rgba(20,62,160,.18);overflow:hidden}.dy-home-hero .dy-eyebrow{color:#dbe7ff}.dy-home-hero h1{font-size:clamp(32px,8vw,48px);line-height:1.02;margin:8px 0 12px;letter-spacing:-1.2px}.dy-home-hero>p{margin:0 0 20px;color:#eef4ff;line-height:1.45;max-width:560px}.dy-eyebrow{display:block;font-size:12px;font-weight:900;letter-spacing:1.3px;color:#2457bd}.dy-home-search{display:flex;align-items:center;gap:8px;background:#fff;border-radius:18px;padding:7px 7px 7px 14px;box-shadow:0 8px 20px rgba(0,0,0,.12)}.dy-home-search span{font-size:19px}.dy-home-search input{min-width:0;flex:1;border:0!important;outline:0;background:transparent;padding:11px 2px;font-size:16px;color:#172033}.dy-home-search button{border:0;border-radius:13px;background:#ff9f1c;color:#172033;font-weight:900;padding:12px 15px}.dy-home-section{margin:0 0 28px}.dy-section-head{display:flex;align-items:end;justify-content:space-between;gap:12px;margin:0 2px 13px}.dy-section-head h2{margin:3px 0 0;font-size:24px;letter-spacing:-.4px}.dy-section-head>a{font-weight:800;color:#2457bd;text-decoration:none;white-space:nowrap}.dy-cat-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.dy-cat{min-width:0;padding:16px 14px;background:#fff;border:1px solid #e7ebf2;border-radius:20px;text-decoration:none;color:#172033;box-shadow:0 5px 18px rgba(18,36,70,.06);display:flex;flex-direction:column;align-items:flex-start;gap:3px;transition:transform .15s ease,box-shadow .15s ease}.dy-cat:active{transform:scale(.98)}.dy-cat-icon{display:grid;place-items:center;width:42px;height:42px;border-radius:14px;background:#eef4ff;font-size:23px;margin-bottom:6px}.dy-cat b{font-size:15px;line-height:1.15}.dy-cat small{font-size:12px;color:#748096}.dy-trust{display:flex;gap:13px;align-items:flex-start;margin:8px 0 26px;padding:18px;background:#f1f6ff;border:1px solid #dce8ff;border-radius:21px}.dy-trust-icon{font-size:25px}.dy-trust b{font-size:16px}.dy-trust p{margin:4px 0 0;color:#5e697b;line-height:1.4;font-size:14px}.dy-pro-cta{margin:0 0 28px;padding:22px;border-radius:24px;background:#fff;border:1px solid #e5e9f1;box-shadow:0 7px 22px rgba(18,36,70,.07)}.dy-pro-cta h2{margin:5px 0 7px;font-size:23px}.dy-pro-cta p{margin:0 0 16px;color:#687386;line-height:1.45}.dy-pro-cta .btn{display:inline-flex}@media(min-width:700px){.dy-cat-grid{grid-template-columns:repeat(4,minmax(0,1fr))}.dy-home-hero{padding:38px 34px}.dy-home-search{max-width:620px}}
</style>`;
 }
 async function search(){const q=new URLSearchParams(location.hash.split('?')[1]||''),p=new URLSearchParams();if(q.get('q'))p.set('q',q.get('q'));if(q.get('cat'))p.set('category_id',q.get('cat'));if(q.get('comuna'))p.set('comuna_id',q.get('comuna'));if(q.get('verif'))p.set('verified','1');const[{workers},{comunas}]=await Promise.all([api('/workers?'+p),api('/comunas?region_id=16')]);view.innerHTML=`<h2 class="section-title">Encontrar profesionales</h2><div class="card"><form onsubmit="event.preventDefault();const p=new URLSearchParams();if(this.q.value)p.set('q',this.q.value);if(this.comuna.value)p.set('comuna',this.comuna.value);if(this.verif.checked)p.set('verif','1');location.hash='#/buscar?'+p"><div class="field"><label>¿Qué necesitas?</label><input name="q" value="${esc(q.get('q')||'')}" placeholder="Oficio o servicio"></div><div class="field"><label>Comuna</label><select name="comuna"><option value="">Todas las comunas</option>${comunas.map(c=>`<option value="${c.id}" ${String(c.id)===String(q.get('comuna'))?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><label class="small"><input type="checkbox" name="verif" ${q.get('verif')?'checked':''}> Mostrar solo identidad verificada</label><button class="btn btn-primary btn-block" style="margin-top:12px">🔍 Buscar</button></form></div><div class="row between" style="margin:16px 2px 8px"><b>${workers.length} resultado${workers.length===1?'':'s'}</b><span class="small muted">Compara antes de solicitar</span></div><div class="cards">${workers.length?workers.map(cleanCard).join(''):'<div class="empty"><b>No encontramos profesionales con esos filtros.</b><br><span class="small">Prueba otra comuna o una búsqueda más general.</span></div>'}</div>`;}
 routes['']=home;
})();
