// DatoYa 2.0 — detalle de trabajo centralizado y listado simplificado.
(function(){
 if(typeof routes==='undefined')return;
 const label=s=>({TRABAJADOR_SELECCIONADO:'Profesional seleccionado',CONFIRMADO:'Trabajo confirmado',EN_PROCESO:'Trabajo en curso',FINALIZADO:'Trabajo cerrado',CANCELADO:'Cancelado',DISPUTA:'En disputa'}[s]||String(s||'').replaceAll('_',' '));
 const step=s=>({TRABAJADOR_SELECCIONADO:1,CONFIRMADO:2,EN_PROCESO:3,DISPUTA:3,FINALIZADO:5,CANCELADO:0}[s]||1);
 function progress(s){const n=step(s),names=['Aceptado','Confirmado','En trabajo','Terminado','Cerrado'];return '<div style="display:grid;grid-template-columns:repeat(5,1fr);gap:4px;margin:16px 0">'+names.map((x,i)=>'<div style="text-align:center"><div style="height:5px;border-radius:9px;background:'+(i<n?'var(--azul)':'#e5e7eb')+'"></div><div class="small" style="margin-top:5px;font-size:10px">'+x+'</div></div>').join('')+'</div>';}
 async function jobsList(){if(!ME){location.hash='#/login';return;}const {jobs}=await api('/jobs');view.innerHTML='<h2 class="section-title">Mis trabajos</h2><p class="small muted">Todo el seguimiento y respaldo de cada servicio está dentro de su detalle.</p>'+(jobs.length?jobs.map(j=>'<div class="card"><div class="row between"><div style="min-width:0"><b>'+esc(j.title)+'</b><div class="small muted" style="margin-top:4px">👤 '+esc(j.other_name||'')+' · 💰 '+fmtCLP(j.price)+'</div></div><span class="status-tag">'+esc(label(j.status))+'</span></div><a class="btn btn-primary btn-block" style="margin-top:12px" href="#/trabajo/'+j.id+'">Ver trabajo</a></div>').join(''):'<div class="empty">Aún no tienes trabajos.</div>');}
 async function detail(id){
  if(!ME){location.hash='#/login';return;}
  const {jobs}=await api('/jobs'),j=jobs.find(x=>String(x.id)===String(id));
  if(!j){view.innerHTML='<div class="empty">Trabajo no encontrado.</div>';return;}
  let t=null,m={};try{t=(await api('/jobs/'+j.id+'/trust')).trust;}catch(_){}try{m=(await api('/jobs/'+j.id+'/meeting')).meeting||{};}catch(_){}
  const p=t?.protection||{},conf=t?.confirmations||[],mine=conf.some(x=>Number(x.user_id)===Number(ME.id)),closed=['FINALIZADO','CANCELADO'].includes(j.status);
  const meetingBlock=m.verified?'<div class="lock-note" style="margin-top:10px">✅ <b>Encuentro confirmado</b><br><span class="small">Ambas partes confirmaron el encuentro'+(m.verified_at?' · '+fmtHora(m.verified_at):'')+'.</span></div>':(!closed&&j.status!=='DISPUTA'?'<button class="btn btn-outline btn-block" onclick="openMeetingModal('+j.id+',\''+esc(j.title).replace(/'/g,'&#39;')+'\')">🤝 Verificar encuentro</button>':'');
  const completeButton=j.status==='EN_PROCESO'?'<button class="btn btn-green btn-block" '+(mine?'disabled':'onclick="confirmComplete('+j.id+')"')+'>'+(mine?'✓ Término confirmado':'✓ Confirmar término')+'</button>':'',disputeButton=!closed&&j.status!=='DISPUTA'?'<button class="btn btn-ghost btn-block" onclick="openDispute('+j.id+')">⚠️ Informar un problema</button>':'';
  const reviewButton=j.status==='FINALIZADO'&&ME.role==='cliente'?(j.my_review?'<button class="btn btn-outline btn-block" disabled>⭐ Calificación enviada</button>':'<button class="btn btn-primary btn-block" onclick="openDatoYaReview('+j.id+')">⭐ Calificar profesional</button>'):'';
  view.innerHTML='<a href="#/trabajos" class="small">← Mis trabajos</a><div class="card" style="margin-top:10px"><div class="row between"><div><div class="small muted">Servicio</div><h2 style="margin:3px 0">'+esc(j.title)+'</h2></div><span class="status-tag">'+esc(label(j.status))+'</span></div><div class="small muted">👤 '+esc(j.other_name||'')+' · 💰 '+fmtCLP(j.price)+'</div>'+progress(j.status)+'</div><div class="card"><div class="row between"><b>🛡️ Protección DatoYa</b><button class="btn btn-outline btn-sm" onclick="openTrust('+j.id+')">Ver bitácora</button></div><div class="small" style="margin-top:9px">'+(p.quote_registered?'✓':'○')+' Cotización · '+(p.meeting_verified?'✓':'○')+' Encuentro · '+(p.evidence_count?'✓':'○')+' Evidencias · '+(p.completion_confirmed?'✓':'○')+' Cierre mutuo</div>'+meetingBlock+'</div><div class="card"><h3 style="margin-top:0">Acciones del trabajo</h3><div style="display:grid;gap:8px">'+(ME.role==='trabajador'&&j.status==='TRABAJADOR_SELECCIONADO'?'<button class="btn btn-primary btn-block" onclick="jobStatus('+j.id+',\'CONFIRMADO\')">✓ Confirmar trabajo</button>':'')+(ME.role==='trabajador'&&j.status==='CONFIRMADO'?'<button class="btn btn-primary btn-block" onclick="jobStatus('+j.id+',\'EN_PROCESO\')">▶ Iniciar trabajo</button>':'')+(!closed?'<button class="btn btn-outline btn-block" onclick="openEvidence('+j.id+')">📷 Fotos antes / después</button>':'')+completeButton+reviewButton+disputeButton+'</div></div>'+(j.status==='DISPUTA'?'<div class="lock-note">⚠️ <b>Trabajo en revisión</b><br><span class="small">El cierre queda pausado mientras DatoYa revisa la disputa.</span></div>':'')+(j.status==='FINALIZADO'?'<div class="lock-note">✅ <b>Servicio realizado mediante DatoYa</b><br><span class="small">Este trabajo cuenta con registro de cierre dentro de la plataforma.</span></div>':'');
 }
 window.openDatoYaReview=function(id){openModal('<h3>⭐ Calificar profesional</h3><p class="small muted">Tu opinión ayuda a construir la reputación dentro de DatoYa.</p><div class="field"><label>Calificación</label><select id="dy-review-rating"><option value="5">★★★★★ Excelente</option><option value="4">★★★★☆ Muy bueno</option><option value="3">★★★☆☆ Bueno</option><option value="2">★★☆☆☆ Regular</option><option value="1">★☆☆☆☆ Malo</option></select></div><div class="field"><label>Comentario opcional</label><textarea id="dy-review-comment" rows="4" maxlength="600" placeholder="Cuenta brevemente cómo fue el servicio"></textarea></div><button class="btn btn-primary btn-block" onclick="sendDatoYaReview('+id+')">Publicar calificación</button>');};
 window.sendDatoYaReview=async function(id){const rating=Number(document.getElementById('dy-review-rating')?.value||0),comment=document.getElementById('dy-review-comment')?.value?.trim()||'';try{await api('/jobs/'+id+'/review',{method:'POST',body:{rating,comment}});closeModal();toast('Gracias. Tu calificación quedó registrada','ok');route();}catch(e){toast(e.message||'No se pudo guardar la calificación','err');}};
 routes.trabajos=jobsList;routes.trabajo=detail;
})();