// DatoYa 2.0 — Protección DatoYa: bitácora, fotos, cierre mutuo y disputas.
(function(){
 if(typeof routes==='undefined'||!routes.trabajos)return;
 const prev=routes.trabajos;
 const statusName=s=>({TRABAJADOR_SELECCIONADO:'Profesional seleccionado',CONFIRMADO:'Trabajo confirmado',EN_PROCESO:'Trabajo en curso',FINALIZADO:'Finalizado',CANCELADO:'Cancelado',DISPUTA:'En disputa'}[s]||String(s||'').replaceAll('_',' '));
 function fileToData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
 async function compress(file){const data=await fileToData(file),img=new Image();await new Promise((ok,no)=>{img.onload=ok;img.onerror=no;img.src=data});let w=img.width,h=img.height,max=1100;if(w>max||h>max){const k=Math.min(max/w,max/h);w=Math.round(w*k);h=Math.round(h*k);}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);return c.toDataURL('image/jpeg',.72);}
 async function enhance(){
  if(!ME||!['cliente','trabajador'].includes(ME.role))return;
  const {jobs}=await api('/jobs'); const cards=[...document.querySelectorAll('#view .card')];
  for(let i=0;i<jobs.length&&i<cards.length;i++){
   const j=jobs[i],card=cards[i]; if(card.dataset.trustDone)return; card.dataset.trustDone='1';
   const tag=card.querySelector('.status-tag');if(tag)tag.textContent=statusName(j.status);
   let t;try{t=(await api('/jobs/'+j.id+'/trust')).trust;}catch(_){continue;}
   const p=t.protection||{}, box=document.createElement('div');box.style.marginTop='12px';box.style.borderTop='1px solid #e5e7eb';box.style.paddingTop='12px';
   box.innerHTML='<div class="lock-note"><b>🛡️ Protección DatoYa</b><div class="small" style="margin-top:6px">'+(p.quote_registered?'✓':'○')+' Cotización registrada · '+(p.meeting_verified?'✓':'○')+' Encuentro verificado · '+(p.history_recorded?'✓':'○')+' Bitácora activa · '+(p.evidence_count?'✓':'○')+' Evidencias ('+(p.evidence_count||0)+') · '+(p.completion_confirmed?'✓':'○')+' Cierre mutuo</div></div>'+
    '<div class="row" style="gap:7px;flex-wrap:wrap;margin-top:9px"><button class="btn btn-outline btn-sm" onclick="openTrust('+j.id+')">📋 Bitácora</button>'+(!['FINALIZADO','CANCELADO'].includes(j.status)?'<button class="btn btn-outline btn-sm" onclick="openEvidence('+j.id+')">📷 Fotos</button><button class="btn btn-green btn-sm" onclick="confirmComplete('+j.id+')">✓ Confirmar término</button>':'')+(!['FINALIZADO','CANCELADO','DISPUTA'].includes(j.status)?'<button class="btn btn-ghost btn-sm" onclick="openDispute('+j.id+')">⚠️ Problema</button>':'')+'</div>';
   card.appendChild(box);
  }
 }
 routes.trabajos=async function(){const r=await prev.apply(this,arguments);setTimeout(enhance,20);return r;};
 window.openTrust=async id=>{try{const t=(await api('/jobs/'+id+'/trust')).trust,h=t.history||[],e=t.evidence||[],c=t.confirmations||[];openModal('<h3>🛡️ Bitácora del trabajo</h3><p class="small muted">Registro de seguridad asociado a este servicio.</p><div class="lock-note">'+(t.meeting?'✅ Encuentro verificado · '+fmtHora(t.meeting.verified_at):'○ Encuentro aún no verificado')+'<br>📷 '+e.length+' evidencia(s)<br>✓ '+c.length+'/2 confirmaciones de término'+(t.dispute?'<br>⚠️ Disputa: '+esc(t.dispute.status):'')+'</div><h4>Historial</h4>'+h.map(x=>'<div class="small" style="padding:7px 0;border-bottom:1px solid #eee"><b>'+esc(statusName(x.status))+'</b> · '+fmtHora(x.created_at)+'</div>').join('')+(e.length?'<h4>Fotos de respaldo</h4>'+e.map(x=>'<button class="btn btn-outline btn-sm" style="margin:3px" onclick="showEvidence('+id+','+x.id+')">📷 '+(x.phase==='antes'?'Antes':'Después')+'</button>').join(''):'') );}catch(e){toast(e.message,'err');}};
 window.showEvidence=async(id,eid)=>{try{const x=(await api('/jobs/'+id+'/evidence/'+eid)).evidence;openModal('<h3>📷 Evidencia · '+(x.phase==='antes'?'Antes':'Después')+'</h3><img src="'+x.image_data+'" alt="Evidencia" style="width:100%;border-radius:12px"><p>'+esc(x.note||'Sin nota')+'</p><div class="small muted">'+fmtHora(x.created_at)+'</div>');}catch(e){toast(e.message,'err');}};
 window.openEvidence=id=>openModal('<h3>📷 Fotos antes y después</h3><p class="small muted">Estas fotos quedan asociadas al trabajo como respaldo.</p><div class="field"><label>Momento</label><select id="ev-phase"><option value="antes">Antes del trabajo</option><option value="despues">Después del trabajo</option></select></div><div class="field"><label>Foto</label><input id="ev-file" type="file" accept="image/*"></div><div class="field"><label>Nota opcional</label><input id="ev-note" maxlength="500" placeholder="Ej: estado inicial del lavaplatos"></div><button class="btn btn-primary btn-block" onclick="sendEvidence('+id+')">Guardar como respaldo</button>');
 window.sendEvidence=async id=>{const f=document.getElementById('ev-file')?.files?.[0];if(!f)return toast('Selecciona una foto','err');try{toast('Preparando foto...');const image_data=await compress(f);await api('/jobs/'+id+'/evidence',{method:'POST',body:{phase:document.getElementById('ev-phase').value,note:document.getElementById('ev-note').value,image_data}});closeModal();toast('Foto guardada como respaldo','ok');route();}catch(e){toast(e.message||'No se pudo guardar','err');}};
 window.confirmComplete=async id=>{if(!confirm('¿Confirmas que el trabajo está terminado? El cierre oficial ocurre cuando ambas partes confirman.'))return;try{const r=await api('/jobs/'+id+'/complete-confirm',{method:'POST',body:{}});toast(r.finalized?'Trabajo finalizado por ambas partes':'Confirmación guardada; falta la otra persona','ok');route();}catch(e){toast(e.message,'err');}};
 window.openDispute=id=>openModal('<h3>⚠️ Informar un problema</h3><p class="small muted">El trabajo quedará en disputa para revisión de DatoYa.</p><div class="field"><label>Motivo</label><select id="dp-reason"><option>Trabajo no realizado</option><option>Trabajo incompleto o defectuoso</option><option>Problema con el pago</option><option>Incumplimiento del acuerdo</option><option>Otro problema</option></select></div><div class="field"><label>Detalles</label><textarea id="dp-details" rows="4" maxlength="1200"></textarea></div><button class="btn btn-primary btn-block" onclick="sendDispute('+id+')">Abrir disputa</button>');
 window.sendDispute=async id=>{if(!confirm('¿Abrir una disputa sobre este trabajo?'))return;try{await api('/jobs/'+id+'/dispute',{method:'POST',body:{reason:document.getElementById('dp-reason').value,details:document.getElementById('dp-details').value}});closeModal();toast('Disputa registrada para revisión','ok');route();}catch(e){toast(e.message,'err');}};
})();
