// DatoYa — textos legales públicos para Chile.
(() => {
 const legalCard=(title,body)=>`<div class="card" style="max-width:820px;margin:0 auto;line-height:1.62"><h2>${title}</h2><p class="small muted">Versión vigente: 15 de septiembre de 2026 · Chile</p>${body}</div>`;
 routes.terminos=async function(){view.innerHTML=legalCard('Términos y Condiciones de Uso de DatoYa',`
 <p>DatoYa es un marketplace de servicios que conecta a personas que necesitan un trabajo o servicio con maestros, técnicos y profesionales independientes que buscan nuevas oportunidades. Para el Profesional, DatoYa permite construir un perfil, portafolio e historial de trabajos. Para el Cliente, permite mantener registro de la contratación y utilizar herramientas de soporte y reclamo.</p>
 <h3>1. Naturaleza de la plataforma</h3><p>DatoYa facilita búsqueda, contacto, cotización, contratación y registro de trabajos entre Clientes y Profesionales independientes. DatoYa no ejecuta por sí mismo el servicio ofrecido por el Profesional ni constituye por ese solo hecho una relación laboral, sociedad, mandato o representación. Las responsabilidades que correspondan a DatoYa conforme a la legislación chilena no se excluyen por esta definición.</p>
 <h3>2. Información y derechos del consumidor</h3><p>DatoYa procura presentar de forma clara precios, cargos y condiciones relevantes antes de confirmar operaciones. Cuando corresponda la Ley N° 19.496 sobre Protección de los Derechos de los Consumidores, estos Términos respetan los derechos irrenunciables reconocidos por esa normativa. Ninguna cláusula pretende excluir derechos o responsabilidades que legalmente no puedan excluirse.</p>
 <h3>3. Perfiles, portafolio y reputación</h3><p>Los Profesionales pueden publicar especialidades, zonas de atención, experiencia, fotografías y antecedentes de trabajos. Deben proporcionar información verdadera y contar con derechos o autorización para publicar el contenido. Un trabajo o evaluación identificados como verificados significan que la contratación o etapa correspondiente quedó registrada mediante DatoYa; no significan una certificación técnica ni garantía de calidad emitida por DatoYa.</p>
 <h3>4. Solicitudes y cotizaciones</h3><p>El Cliente debe describir razonablemente el trabajo y aportar información relevante. El Profesional debe indicar alcance, precio o estimación, disponibilidad y condiciones conocidas. Una estimación basada en fotografías o información remota puede requerir confirmación presencial cuando existan circunstancias que no podían determinarse razonablemente a distancia.</p>
 <h3>5. Trabajos adicionales, cambios y materiales</h3><p>Si durante la ejecución aparecen trabajos adicionales, materiales no contemplados o circunstancias que alteren el alcance, el Profesional debe informar el cambio y proponer el nuevo importe o condición mediante las herramientas disponibles. El precio registrado no debe modificarse unilateralmente. Cuando la plataforma habilite aceptación de cambios, el nuevo importe será aplicable una vez aceptado por el Cliente. Los materiales deben identificarse como incluidos, no incluidos o por determinar cuando corresponda.</p>
 <h3>6. Ejecución del servicio</h3><p>El Profesional es responsable de ejecutar el trabajo conforme a lo acordado y a la normativa aplicable a su actividad, incluidas habilitaciones o certificaciones cuando correspondan. El Cliente debe facilitar condiciones razonables y seguras para la prestación.</p>
 <h3>7. Registro y Respaldo DatoYa</h3><p>DatoYa puede mantener registros de solicitudes, cotizaciones, acuerdos, modificaciones, mensajes, evidencias, estados, pagos y evaluaciones generados mediante la plataforma. Este respaldo ayuda a documentar lo ocurrido y puede utilizarse para soporte y gestión de reclamos. “Respaldo DatoYa” no constituye seguro, garantía de resultado, garantía financiera ni custodia de fondos.</p>
 <h3>8. DatoYa PRO, comisión de servicio y pagos</h3><p>DatoYa PRO es una suscripción opcional cuyas características, precio y periodicidad se informan antes de contratar. DatoYa podrá cobrar una comisión de servicio por trabajos contratados o pagados mediante la plataforma; el porcentaje, base de cálculo y cargos aplicables deberán mostrarse antes de la operación correspondiente. Los pagos electrónicos podrán ser procesados por proveedores externos, como Mercado Pago cuando esté habilitado, sujetos además a sus propias condiciones. DatoYa no se presenta como banco, aseguradora ni custodio de fondos.</p>
 <h3>9. Contrataciones y pagos fuera de DatoYa</h3><p>Las herramientas de respaldo, historial verificado, soporte de la operación y gestión de reclamos de DatoYa se aplican según la información y etapas efectivamente registradas dentro de la plataforma. DatoYa no puede verificar ni administrar como contratación realizada mediante la plataforma pagos, acuerdos o modificaciones efectuados exclusivamente por fuera. Se podrán aplicar medidas razonables contra el uso abusivo de DatoYa destinado sistemáticamente a eludir cargos o reglas de la plataforma, conforme a condiciones previamente informadas y respetando la legislación aplicable.</p>
 <h3>10. Finalización, problemas y reclamos</h3><p>Antes de finalizar un trabajo, las partes podrán registrar su conformidad o informar un problema. El Cliente podrá aportar una descripción y evidencias; el Profesional podrá responder, proponer una corrección u otra solución. Si no existe acuerdo, DatoYa podrá revisar los antecedentes registrados para facilitar o administrar el reclamo según las funciones disponibles. Este procedimiento no sustituye los derechos, acciones ni autoridades competentes establecidos por la legislación chilena.</p>
 <h3>11. Reseñas</h3><p>Las reseñas deben corresponder a experiencias reales y publicarse de buena fe. DatoYa podrá moderar contenido fraudulento, ofensivo, irrelevante o que revele indebidamente datos personales, procurando no alterar una opinión legítima.</p>
 <h3>12. Conductas prohibidas</h3><p>No se permite suplantar identidades, manipular reputaciones, crear operaciones ficticias, acosar o amenazar, intentar vulnerar sistemas, acceder sin autorización, introducir código malicioso, usar automatizaciones abusivas ni utilizar DatoYa para actividades ilícitas.</p>
 <h3>13. Privacidad y datos personales</h3><p>El tratamiento de datos se rige por la Política de Privacidad y la normativa chilena aplicable, incluida la Ley N° 19.628 y su modernización mediante la Ley N° 21.719 conforme a su vigencia legal. Las personas deben evitar publicar datos personales innecesarios de terceros.</p>
 <h3>14. Documentos y comunicaciones electrónicas</h3><p>DatoYa puede utilizar registros, consentimientos y comunicaciones electrónicas para operar sus funciones, respetando la Ley N° 19.799 cuando resulte aplicable. Los registros de plataforma no reemplazan solemnidades o documentos que la ley exija por otra vía.</p>
 <h3>15. Disponibilidad y responsabilidad</h3><p>DatoYa puede efectuar mantenciones y actualizaciones y no garantiza disponibilidad ininterrumpida ante fallas técnicas, proveedores externos o fuerza mayor. Cada Cliente y Profesional responde por sus propios actos y por el servicio contratado o prestado. DatoYa responderá cuando corresponda conforme a la legislación aplicable y estos Términos no limitan responsabilidades que legalmente no puedan limitarse.</p>
 <h3>16. Suspensión, cierre y conservación</h3><p>DatoYa podrá restringir funciones o suspender cuentas por incumplimientos, abuso, riesgos de seguridad o requerimientos legales. El cierre de una cuenta no impide conservar información necesaria para obligaciones legales, seguridad, prevención de fraude o gestión de controversias.</p>
 <h3>17. Ley aplicable, cambios y contacto</h3><p>Estos Términos se rigen por las leyes de la República de Chile. Los cambios relevantes se informarán por medios razonables y, cuando corresponda, requerirán nueva aceptación. Las consultas legales, de privacidad, seguridad o soporte podrán realizarse por los canales oficiales publicados dentro de DatoYa.</p>`);};
 routes.privacidad=async function(){view.innerHTML=legalCard('Política de Privacidad de DatoYa',`
 <p>Esta Política explica el tratamiento de datos personales necesario para operar DatoYa como marketplace de servicios y mantener los registros asociados a perfiles, contrataciones y soporte. Se aplicará la normativa chilena vigente, incluida la Ley N° 19.628 y, desde su entrada en vigencia, las modificaciones de la Ley N° 21.719.</p>
 <h3>1. Datos tratados</h3><p>Podemos tratar datos de cuenta y contacto; comuna y perfil; especialidades y portafolio; solicitudes, cotizaciones, trabajos y modificaciones; mensajes; fotografías y evidencias; reseñas, favoritos, reportes y reclamos; consentimientos; eventos de seguridad e información técnica necesaria para funcionamiento y seguridad.</p>
 <h3>2. Finalidades</h3><p>Los datos se utilizan para administrar cuentas, mostrar perfiles profesionales, conectar usuarios, gestionar contrataciones y trabajos, mantener historial y trazabilidad, habilitar comunicaciones, pagos cuando correspondan, soporte, reclamos, seguridad, prevención de fraude y cumplimiento legal.</p>
 <h3>3. Ubicación y dirección del servicio</h3><p>La ubicación se utiliza cuando una función la requiere y existe el permiso o fundamento correspondiente. DatoYa procura limitar la exposición pública de ubicaciones precisas y entregar la información necesaria únicamente a participantes y funciones autorizadas.</p>
 <h3>4. Fotografías, portafolio y evidencias</h3><p>Las fotografías pueden contener información personal. Quien las publique debe contar con autorización o fundamento suficiente y evitar datos de terceros que no sean necesarios. Las evidencias vinculadas a un trabajo podrán conservarse durante el período necesario para soporte, seguridad, trazabilidad y controversias.</p>
 <h3>5. Pagos y proveedores</h3><p>Cuando existan pagos electrónicos, proveedores especializados podrán tratar los datos necesarios para procesarlos y prevenir fraude. DatoYa procura no almacenar datos completos de tarjetas cuando el proveedor permita mantenerlos fuera de su infraestructura.</p>
 <h3>6. Comunicación, seguridad y conservación</h3><p>DatoYa podrá comunicar información necesaria a proveedores tecnológicos, participantes de una contratación cuando el servicio lo requiera y autoridades ante una obligación legal válida. DatoYa no vende datos personales. Se aplican controles de acceso, sesiones, validaciones y registros de seguridad. Los datos se conservan durante el tiempo necesario según su finalidad y obligaciones aplicables.</p>
 <h3>7. Derechos y cambios</h3><p>Las personas podrán ejercer los derechos reconocidos por la legislación chilena vigente mediante los canales oficiales de DatoYa. Esta política podrá actualizarse por cambios legales, técnicos u operativos y los cambios relevantes se informarán por medios razonables.</p><p><a href="#/terminos">← Ver Términos y Condiciones</a></p>`);};
})();
