// DatoYa — textos legales públicos para Chile.
(() => {
  const legalCard=(title,body)=>`<div class="card" style="max-width:820px;margin:0 auto;line-height:1.62"><h2>${title}</h2><p class="small muted">Versión vigente: 15 de septiembre de 2026 · Chile</p>${body}</div>`;
  routes.terminos=async function(){view.innerHTML=legalCard('Términos y Condiciones de Uso de DatoYa',`
   <p>Estos Términos regulan el acceso y uso de DatoYa en Chile. Al crear una cuenta y utilizar funciones que impliquen contratación, publicación, cotización o aceptación, la persona usuaria declara haber leído y aceptado estos Términos y la Política de Privacidad.</p>
   <h3>1. Naturaleza de la plataforma</h3><p>DatoYa facilita el contacto entre Clientes y Profesionales independientes. Salvo que una función lo indique expresamente, DatoYa no ejecuta el servicio ofrecido por el Profesional ni constituye por ese solo hecho una relación laboral, sociedad, mandato o representación entre DatoYa y el Profesional.</p>
   <h3>2. Información, contratación y derechos del consumidor</h3><p>DatoYa procura presentar de forma clara la información relevante disponible sobre precios, cargos y condiciones antes de confirmar operaciones. Cuando una relación quede comprendida en la Ley N° 19.496 sobre Protección de los Derechos de los Consumidores, estos Términos se interpretarán respetando los derechos irrenunciables que esa ley reconoce, incluidos los derechos a información veraz y oportuna, libre elección y seguridad en el consumo. Ninguna cláusula pretende excluir derechos que legalmente no puedan renunciarse.</p>
   <h3>3. Cuentas y seguridad</h3><p>Las personas usuarias deben entregar información verdadera y actualizada, proteger sus credenciales y responder por el uso de su cuenta. DatoYa podrá aplicar verificaciones de correo, teléfono, identidad y controles razonables de seguridad y prevención de fraude, y podrá restringir funciones o cuentas cuando existan antecedentes de abuso, suplantación, acceso no autorizado, fraude o incumplimiento.</p>
   <h3>4. Solicitudes, perfiles y contenido</h3><p>Clientes y Profesionales responden por la información, fotografías y descripciones que publiquen y deben contar con los derechos necesarios sobre ese contenido. Se prohíbe contenido ilícito, engañoso, discriminatorio, amenazante, invasivo de la privacidad o que vulnere derechos de terceros.</p>
   <h3>5. Cotizaciones y trabajos</h3><p>El Profesional debe informar correctamente alcance, precio, materiales, disponibilidad y demás condiciones relevantes. El Cliente debe revisarlas antes de aceptar. Las partes deben utilizar los estados, mensajes y evidencias disponibles para mantener trazabilidad de modificaciones relevantes.</p>
   <h3>6. Ejecución del servicio</h3><p>El Profesional es responsable de ejecutar el trabajo de forma diligente y conforme a la normativa aplicable a su actividad, incluidas habilitaciones o certificaciones que correspondan. El Cliente debe facilitar condiciones razonables y seguras para la prestación.</p>
   <h3>7. DatoYa PRO, precios, comisiones y pagos</h3><p>Las características, precio y periodicidad de DatoYa PRO se informarán antes de contratarlo. Los cobros electrónicos que se habiliten podrán ser procesados por proveedores externos y estarán sujetos además a las condiciones aplicables de esos proveedores. DatoYa no se presenta como banco ni como custodio de fondos. Cualquier función de protección de pago se describirá únicamente según las capacidades efectivamente habilitadas.</p>
   <h3>8. Finalización, evidencias y disputas</h3><p>DatoYa podrá solicitar confirmaciones de las partes y permitir antecedentes vinculados al trabajo. En una controversia podrá revisar la información necesaria de la operación para administrar la plataforma. Este procedimiento interno no reemplaza los derechos, acciones ni autoridades competentes establecidos por la legislación chilena.</p>
   <h3>9. Reseñas</h3><p>Las reseñas deben corresponder a experiencias reales y publicarse de buena fe. DatoYa podrá moderar contenido fraudulento, ofensivo, irrelevante o que revele indebidamente datos personales, procurando no alterar una opinión legítima.</p>
   <h3>10. Conductas prohibidas</h3><p>No se permite suplantar identidades, manipular reputaciones, crear operaciones ficticias, acosar o amenazar, intentar vulnerar sistemas, acceder sin autorización, introducir código malicioso, usar automatizaciones abusivas ni utilizar DatoYa para actividades ilícitas.</p>
   <h3>11. Privacidad y datos personales</h3><p>El tratamiento de datos se rige por la Política de Privacidad y por la normativa chilena aplicable. DatoYa considera la Ley N° 19.628 y su modernización mediante la Ley N° 21.719, incluida la protección de datos desde el diseño y por defecto conforme a su vigencia legal. Las personas deben evitar publicar datos personales innecesarios de terceros.</p>
   <h3>12. Documentos y comunicaciones electrónicas</h3><p>DatoYa puede utilizar registros, consentimientos y comunicaciones electrónicas para operar sus funciones, respetando la Ley N° 19.799 sobre documentos electrónicos y firma electrónica cuando resulte aplicable. Ello no reemplaza solemnidades legales que deban cumplirse por otra vía.</p>
   <h3>13. Propiedad intelectual</h3><p>La marca, software, interfaz, diseño y contenidos propios de DatoYa están protegidos por la legislación aplicable. El contenido aportado por usuarios continúa perteneciendo a sus titulares; su publicación autoriza a DatoYa a alojarlo, procesarlo y mostrarlo en la medida necesaria para prestar, proteger y mejorar las funciones solicitadas.</p>
   <h3>14. Disponibilidad y responsabilidad</h3><p>DatoYa puede efectuar mantenciones y actualizaciones y no garantiza disponibilidad ininterrumpida ante fallas técnicas, proveedores externos o fuerza mayor. Cada Cliente y Profesional responde por sus actos y por el servicio contratado o prestado. DatoYa responderá en los casos establecidos por la legislación aplicable y estos Términos no limitan responsabilidades que legalmente no puedan limitarse.</p>
   <h3>15. Suspensión y cierre</h3><p>DatoYa podrá restringir funciones o suspender cuentas por incumplimientos, riesgos de seguridad o requerimientos legales. El cierre de cuenta no impide conservar información que deba mantenerse por obligaciones legales, seguridad, prevención de fraude o gestión de controversias.</p>
   <h3>16. Ley aplicable y modificaciones</h3><p>Estos Términos se rigen por las leyes de la República de Chile. DatoYa podrá actualizarlos por cambios legales, técnicos, operativos o de seguridad. Cuando el cambio sea relevante se informará por medios razonables y, cuando corresponda, se solicitará una nueva aceptación.</p>
   <h3>17. Contacto</h3><p>Las consultas legales, de privacidad, seguridad o soporte podrán realizarse por los canales oficiales publicados dentro de DatoYa.</p>
  `);};
  routes.privacidad=async function(){view.innerHTML=legalCard('Política de Privacidad de DatoYa',`
   <p>Esta Política explica el tratamiento de datos personales realizado para operar y proteger DatoYa en Chile. El tratamiento se realizará conforme a la normativa chilena aplicable, incluida la Ley N° 19.628 y, desde su entrada en vigencia, las modificaciones introducidas por la Ley N° 21.719.</p>
   <h3>1. Datos tratados</h3><p>Podemos tratar datos de cuenta y contacto; comuna y perfil; especialidades; solicitudes, cotizaciones y trabajos; mensajes; fotografías y evidencias; reseñas, favoritos, reportes y disputas; consentimientos; eventos de seguridad e información técnica de sesión, dispositivo y conexión necesaria para seguridad y funcionamiento.</p>
   <h3>2. Finalidades</h3><p>Los datos se utilizan para administrar cuentas, conectar usuarios, gestionar solicitudes y trabajos, habilitar comunicaciones, seguridad y prevención de fraude, soporte y controversias, cumplimiento legal, registro de consentimientos y funcionamiento de la plataforma.</p>
   <h3>3. Proporcionalidad y privacidad desde el diseño</h3><p>DatoYa procura tratar solo los datos necesarios para cada finalidad y limitar su exposición. En preparación para el régimen de la Ley N° 21.719 se aplican principios de protección desde el diseño y por defecto, considerando naturaleza, contexto, finalidad y riesgos del tratamiento.</p>
   <h3>4. Ubicación</h3><p>La ubicación se utiliza únicamente cuando una función la requiere y existe el permiso correspondiente. Se procura limitar la exposición pública de ubicaciones precisas y reservar los datos necesarios a participantes y funciones autorizadas.</p>
   <h3>5. Fotografías y contenido profesional</h3><p>Las fotografías de portafolio, solicitudes o evidencias pueden contener información personal. La persona que las sube debe contar con autorización o fundamento suficiente para hacerlo y evitar incluir datos personales de terceros que no sean necesarios.</p>
   <h3>6. Pagos y proveedores</h3><p>Cuando existan pagos electrónicos, proveedores especializados podrán tratar los datos estrictamente necesarios para procesarlos y prevenir fraude. DatoYa procura no almacenar datos completos de tarjetas cuando el proveedor permita mantenerlos fuera de su infraestructura.</p>
   <h3>7. Comunicación de datos</h3><p>DatoYa podrá comunicar información necesaria a proveedores tecnológicos que apoyen alojamiento, seguridad, comunicaciones o pagos; a participantes de una operación cuando el servicio lo requiera; y a autoridades ante una obligación o requerimiento legal válido. DatoYa no vende datos personales.</p>
   <h3>8. Seguridad</h3><p>Se aplican medidas técnicas y organizativas destinadas a proteger cuentas e información, incluidos controles de acceso, sesiones, validaciones, registros de seguridad y restricciones de visibilidad. Las medidas se revisan según los riesgos y ningún sistema puede garantizar riesgo cero.</p>
   <h3>9. Conservación</h3><p>Los datos se conservan durante el tiempo necesario para prestar el servicio, mantener seguridad y trazabilidad, gestionar controversias y cumplir obligaciones legales. El plazo depende del tipo de información y de su finalidad.</p>
   <h3>10. Derechos de las personas</h3><p>Las personas podrán ejercer los derechos reconocidos por la legislación chilena vigente respecto de sus datos personales mediante los canales oficiales de DatoYa. Podrá requerirse verificar identidad antes de atender una solicitud que afecte información de una cuenta.</p>
   <h3>11. Menores de edad</h3><p>DatoYa está destinado a personas con capacidad legal suficiente para las contrataciones realizadas mediante la plataforma. No debe utilizarse una cuenta para eludir requisitos legales de edad o capacidad.</p>
   <h3>12. Cambios y contacto</h3><p>Esta política podrá actualizarse por cambios legales, técnicos u operativos. Los cambios relevantes se informarán por medios razonables y, cuando corresponda, requerirán nueva aceptación. Las solicitudes de privacidad podrán realizarse mediante los canales oficiales publicados en DatoYa.</p><p><a href="#/terminos">← Ver Términos y Condiciones</a></p>
  `);};
})();
