// DatoYa — textos legales públicos, versión final de producto.
(() => {
  const legalCard=(title,body)=>`<div class="card" style="max-width:820px;margin:0 auto;line-height:1.62"><h2>${title}</h2><p class="small muted">Versión vigente: 15 de septiembre de 2026 · Chile</p>${body}</div>`;

  routes.terminos=async function(){
    view.innerHTML=legalCard('Términos y Condiciones de Uso de DatoYa',`
      <p>Estos Términos y Condiciones regulan el acceso y uso de DatoYa. Al crear una cuenta, publicar o cotizar un servicio, aceptar una cotización o utilizar las funciones de la plataforma, la persona usuaria declara haber leído y aceptado estos términos y la Política de Privacidad.</p>
      <h3>1. Objeto y naturaleza de DatoYa</h3><p>DatoYa es una plataforma tecnológica que facilita el contacto entre personas que requieren servicios (Clientes) y personas independientes que los ofrecen (Profesionales). Salvo que una función indique expresamente lo contrario, DatoYa no presta directamente los servicios publicados ni actúa como empleador, mandatario, socio o representante del Profesional.</p>
      <h3>2. Requisitos y cuentas</h3><p>Las personas usuarias deben proporcionar información verdadera, actualizada y suficiente, mantener la confidencialidad de sus credenciales y responder por la actividad realizada desde su cuenta. DatoYa puede aplicar verificaciones de correo, teléfono, identidad, seguridad y prevención de fraude, y restringir o suspender cuentas cuando existan antecedentes razonables de abuso, fraude, suplantación, incumplimiento o riesgo para otras personas.</p>
      <h3>3. Publicación de solicitudes y perfiles</h3><p>Clientes y Profesionales son responsables de la información, fotografías, descripciones y demás contenido que incorporen. Está prohibido publicar información ilícita, engañosa, discriminatoria, amenazante, invasiva de la privacidad, que vulnere derechos de terceros o que busque eludir indebidamente los mecanismos de seguridad de DatoYa.</p>
      <h3>4. Cotizaciones y contratación</h3><p>El Profesional es responsable de definir correctamente su cotización, alcance, precio, materiales, disponibilidad y condiciones. El Cliente debe revisar esos antecedentes antes de aceptar. La aceptación genera un trabajo dentro de DatoYa entre Cliente y Profesional. Cualquier modificación relevante debe quedar registrada en la plataforma cuando la función esté disponible.</p>
      <h3>5. Ejecución y seguridad del trabajo</h3><p>El Profesional debe realizar el servicio de manera diligente, segura y conforme a la normativa aplicable a su actividad, incluyendo permisos, certificaciones o habilitaciones que correspondan. El Cliente debe proporcionar condiciones razonables y seguras para la ejecución. DatoYa puede habilitar confirmación de encuentro, estados del trabajo, mensajería y evidencias para mejorar la trazabilidad.</p>
      <h3>6. Precios, comisiones y pagos</h3><p>Antes de confirmar una operación sujeta a cobro, DatoYa informará los montos y cargos aplicables. Cuando se habiliten pagos electrónicos, estos podrán ser procesados por proveedores externos autorizados y quedarán además sujetos a sus propias condiciones. DatoYa no se presenta como banco, institución financiera ni custodio de fondos y solo describirá una protección de pago en los términos que permita efectivamente el proveedor utilizado.</p>
      <h3>7. Finalización, evidencias y disputas</h3><p>DatoYa puede solicitar confirmaciones de ambas partes para finalizar un trabajo. Ante una controversia, las partes podrán aportar antecedentes y DatoYa podrá revisar la información relacionada con la operación, como cotizaciones, mensajes, estados, confirmaciones y evidencias. Las decisiones administrativas de la plataforma buscan gestionar su funcionamiento y no sustituyen los derechos que la legislación reconoce a las personas.</p>
      <h3>8. Reseñas</h3><p>Las reseñas deben corresponder a experiencias reales y expresarse de buena fe. DatoYa podrá moderar contenido fraudulento, ofensivo, irrelevante, que revele datos personales de terceros o infrinja estos términos, procurando no alterar legítimamente la opinión del usuario.</p>
      <h3>9. Conductas prohibidas</h3><p>No se permite suplantar identidades, manipular reputaciones, crear operaciones ficticias, acosar o amenazar, intentar vulnerar la seguridad, acceder sin autorización a cuentas o información, usar automatizaciones abusivas, introducir código malicioso, utilizar DatoYa para actividades ilícitas ni infringir derechos de propiedad intelectual o privacidad.</p>
      <h3>10. Disponibilidad y cambios del servicio</h3><p>DatoYa procura mantener el servicio disponible y seguro, pero puede realizar mantenciones, actualizaciones o cambios necesarios. No se garantiza disponibilidad ininterrumpida frente a fallas técnicas, proveedores externos, fuerza mayor u otras circunstancias fuera de control razonable.</p>
      <h3>11. Responsabilidad</h3><p>Cada Cliente y Profesional responde por sus actos, acuerdos y por el servicio contratado o prestado. Nada en estos términos pretende excluir o limitar responsabilidades o derechos que legalmente no puedan excluirse o limitarse. DatoYa responderá en los casos y dentro de los límites establecidos por la legislación aplicable.</p>
      <h3>12. Propiedad intelectual</h3><p>La marca, interfaz, software, diseño y contenidos propios de DatoYa están protegidos por las normas aplicables. El contenido aportado por usuarios continúa perteneciendo a sus titulares; al publicarlo, autorizan su tratamiento y visualización en la medida necesaria para operar, proteger y mejorar las funciones solicitadas.</p>
      <h3>13. Privacidad</h3><p>El tratamiento de datos personales se rige por la <a href="#/privacidad">Política de Privacidad</a>, que forma parte de estas condiciones. Las personas usuarias deben evitar compartir datos personales innecesarios de terceros.</p>
      <h3>14. Suspensión y cierre de cuenta</h3><p>DatoYa puede restringir funciones o suspender cuentas por incumplimientos, riesgos de seguridad o requerimientos legales. Cuando corresponda, la persona podrá solicitar el cierre de su cuenta, sin perjuicio de conservar información que deba mantenerse por obligaciones legales, prevención de fraude, seguridad o gestión de controversias.</p>
      <h3>15. Legislación aplicable</h3><p>Estos términos se rigen por las leyes de la República de Chile. Se respetan los derechos irrenunciables que correspondan conforme a la normativa chilena, incluidos los mecanismos de protección al consumidor cuando resulten aplicables.</p>
      <h3>16. Modificaciones</h3><p>DatoYa podrá actualizar estos términos por cambios legales, operativos, técnicos o de seguridad. Cuando una modificación sea relevante, se informará por medios razonables y podrá solicitarse una nueva aceptación antes de continuar utilizando determinadas funciones.</p>
      <h3>17. Contacto</h3><p>Las consultas legales, de privacidad, seguridad o soporte podrán realizarse mediante los canales de contacto oficiales que DatoYa publique dentro de la aplicación.</p>
      <p class="small muted">Este documento debe mantenerse coherente con las funciones efectivamente disponibles en DatoYa y con la normativa chilena vigente.</p>
    `);
  };

  routes.privacidad=async function(){
    view.innerHTML=legalCard('Política de Privacidad de DatoYa',`
      <p>Esta Política explica cómo DatoYa trata datos personales para operar y proteger la plataforma, conectar Clientes con Profesionales y cumplir obligaciones aplicables.</p>
      <h3>1. Datos que podemos tratar</h3><p>Datos de cuenta y contacto; comuna y datos de perfil; especialidades y antecedentes profesionales; solicitudes, cotizaciones y trabajos; mensajes; fotografías y evidencias; reseñas, favoritos, reportes y disputas; consentimientos; eventos de seguridad; información técnica de sesión, dispositivo y conexión necesaria para seguridad y funcionamiento.</p>
      <h3>2. Finalidades</h3><p>Usamos los datos para crear y administrar cuentas, conectar usuarios, gestionar solicitudes y trabajos, habilitar comunicaciones, verificar seguridad, prevenir fraude y abuso, atender soporte y controversias, cumplir obligaciones legales, mantener registros de consentimiento y mejorar la estabilidad y experiencia del servicio.</p>
      <h3>3. Ubicación</h3><p>La ubicación se utiliza únicamente cuando una función la requiere y existe el permiso correspondiente. DatoYa procura limitar la exposición pública de ubicaciones precisas y reservar los datos necesarios para los participantes autorizados y funciones operativas pertinentes.</p>
      <h3>4. Pagos y proveedores</h3><p>Cuando existan pagos electrónicos, proveedores especializados podrán tratar los datos necesarios para procesarlos y prevenir fraude. DatoYa no debe almacenar datos completos de tarjetas cuando el proveedor de pagos permita mantenerlos fuera de la infraestructura de la plataforma.</p>
      <h3>5. Comunicación de datos</h3><p>DatoYa puede comunicar la información estrictamente necesaria a proveedores tecnológicos que apoyen el funcionamiento, seguridad, comunicaciones, alojamiento o pagos; a los participantes de una operación según lo requiera el servicio; y a autoridades cuando exista una obligación o requerimiento legal válido. DatoYa no vende datos personales.</p>
      <h3>6. Seguridad</h3><p>Se aplican medidas técnicas y organizativas destinadas a proteger cuentas e información, incluyendo controles de acceso, sesiones, validaciones, registros de seguridad y restricciones de visibilidad. Ningún sistema es absolutamente infalible, por lo que las medidas se revisan y actualizan según los riesgos.</p>
      <h3>7. Conservación</h3><p>Los datos se conservan durante el tiempo necesario para prestar el servicio, mantener seguridad y trazabilidad, gestionar controversias y cumplir obligaciones legales. Los plazos pueden variar según la naturaleza del dato y la finalidad de su tratamiento.</p>
      <h3>8. Derechos y solicitudes</h3><p>Las personas podrán ejercer los derechos que les reconozca la legislación chilena respecto de sus datos personales a través de los canales oficiales de DatoYa. Podrá requerirse verificación de identidad antes de atender solicitudes que afecten información de una cuenta.</p>
      <h3>9. Menores de edad</h3><p>DatoYa está destinado a personas con capacidad legal suficiente para contratar los servicios ofrecidos en la plataforma. No debe utilizarse una cuenta para eludir requisitos legales de edad o capacidad aplicables a una contratación.</p>
      <h3>10. Cambios de esta política</h3><p>Podremos actualizar esta política por cambios legales, técnicos u operativos. Si los cambios son relevantes, se informarán por medios razonables y, cuando corresponda, se solicitará una nueva aceptación.</p>
      <h3>11. Contacto</h3><p>Las solicitudes relacionadas con privacidad podrán enviarse mediante los canales oficiales de soporte o privacidad publicados dentro de DatoYa.</p>
      <p><a href="#/terminos">← Ver Términos y Condiciones</a></p>
    `);
  };

  const oldSecurity=routes.seguridad;
  if(oldSecurity) routes.seguridad=async function(){await oldSecurity(); const box=[...document.querySelectorAll('.small.muted')].find(x=>x.textContent.includes('Versiones vigentes de la beta')); if(box)box.textContent='Versiones legales vigentes';};
})();
