/* DatoYa — Home real de Impulso Ahora, con ejemplos DEMO cuando aún no hay publicaciones reales. */
(() => {
  if(typeof api!=='function')return;
  const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>'$'+Number(n||0).toLocaleString('es-CL');
  const isHome=()=>!location.hash||location.hash==='#'||location.hash==='#/';
  const remainText=end=>{const ms=new Date(end).getTime()-Date.now();if(ms<=0)return'Finalizando';const m=Math.ceil(ms/60000);if(m<60)return m+' min';const hr=Math.floor(m/60),min=m%60;return hr+' h'+(min?' '+min+' min':'')};
  const demoItems=[
    {title:'6 empanadas de horno',business_name:'Panadería Buen Día',comuna:'Ejemplo local',price:10000,old_price:15000,stock_remaining:8,icon:'🥟',mode:'🔥 ÚLTIMAS UNIDADES',slug:'panaderia-buen-dia-demo'},
    {title:'Berlines recién hechos',business_name:'Dulce Hogar',comuna:'Ejemplo local',price:1000,old_price:1500,stock_remaining:15,icon:'🍩',mode:'VENTA ACTIVA',slug:'dulce-hogar-demo'},
    {title:'Sándwich + café',business_name:'Café Central',comuna:'Ejemplo local',price:4990,old_price:6490,stock_remaining:12,icon:'☕',mode:'VENTA ACTIVA',slug:'cafe-central-demo'}
  ];
  function renderDemo(section){
    section.innerHTML=`<div class="dy-section-head"><div><h2>⚡ Ahora cerca de ti</h2><p>Así funciona Impulso Ahora: ventas por horario y stock.</p></div><a class="dy-see-all" href="#/conoce">¿Cómo funciona? →</a></div><div class="dy-live-grid">${demoItems.map(i=>`<article class="dy-live-card dy-real-product dy-impulse-live dy-demo-live-card"><div class="dy-live-image dy-real-product-photo"><div class="dy-real-placeholder">${h(i.icon)}</div><span class="dy-live-badge">⚡ IMPULSO AHORA</span><span class="dy-demo-demo-tag">DEMO</span><span class="dy-stock-badge">${h(i.mode)} · quedan ${Number(i.stock_remaining)}</span></div><div class="dy-live-body"><small>EJEMPLO ILUSTRATIVO</small><h3>${h(i.title)}</h3><p>${h(i.business_name)} · 📍 ${h(i.comuna)}</p><div class="dy-live-price-row"><div class="dy-live-price"><strong>${money(i.price)}</strong><span class="dy-old-price">${money(i.old_price)}</span></div><span class="dy-time">⏳ Ejemplo</span></div><div class="dy-impulse-buttons"><a class="btn btn-outline btn-sm" href="#/demo-negocio/${encodeURIComponent(i.slug)}">Ver ejemplo</a></div></div></article>`).join('')}</div><p class="dy-demo-trust-note" style="margin-top:10px!important"><span>ℹ️</span><span>Estos Impulsos son <b>DEMO</b>: muestran la experiencia visual y no generan pedidos ni pagos reales.</span></p>`;
  }
  async function render(){if(!isHome())return;const section=document.getElementById('impulso-ahora');if(!section)return;const comunaId=Number(localStorage.getItem('datoya_comuna_id')||0);try{const r=await api('/market/impulses'+(comunaId?'?comuna_id='+comunaId:'')),items=r.impulses||[];window.__dyImpulseCache=items;if(!items.length){renderDemo(section);return;}section.innerHTML=`<div class="dy-section-head"><div><h2>⚡ Ahora cerca de ti</h2><p>Lo que se está vendiendo cerca de ti, justo ahora.</p></div></div><div class="dy-live-grid">${items.map(i=>`<article class="dy-live-card dy-real-product dy-impulse-live"><div class="dy-live-image dy-real-product-photo">${i.product_image?`<img src="${i.product_image}" alt="${h(i.title)}" loading="lazy">`:'<div class="dy-real-placeholder">⚡</div>'}<span class="dy-live-badge">⚡ IMPULSO AHORA</span><span class="dy-stock-badge">${i.status==='low_stock'||i.sale_mode==='last_units'?'🔥 ':''}Quedan ${Number(i.stock_remaining)}</span></div><div class="dy-live-body"><small>${i.sale_mode==='liquidation'?'LIQUIDACIÓN':i.sale_mode==='last_units'?'ÚLTIMAS UNIDADES':'VENTA ACTIVA'}</small><h3>${h(i.title)}</h3><p>${h(i.business_name)} · 📍 ${h(i.comuna||'')}</p><div class="dy-live-price-row"><div class="dy-live-price"><strong>${money(i.price)}</strong>${i.old_price&&Number(i.old_price)>Number(i.price)?`<span class="dy-old-price">${money(i.old_price)}</span>`:''}</div><span class="dy-time">⏳ ${h(remainText(i.ends_at))}</span></div><div class="dy-impulse-buttons"><a class="btn btn-outline btn-sm" href="#/negocio/${Number(i.business_id)}">Ver negocio</a><button class="btn btn-primary btn-sm" onclick="dyCartAddImpulse(${Number(i.id)})">🛒 Agregar</button></div></div></article>`).join('')}</div>`;}catch(_){section.innerHTML=`<div class="dy-section-head"><div><h2>⚡ Ahora cerca de ti</h2></div></div><div class="dy-real-empty"><span>⚡</span><b>No pudimos cargar Impulso Ahora</b><p>Intenta nuevamente en unos segundos.</p></div>`;}}
  function boot(){let n=0,t=setInterval(()=>{if(document.getElementById('impulso-ahora')){clearInterval(t);render()}else if(++n>50)clearInterval(t)},100)}
  addEventListener('datoya:market-home-rendered',()=>setTimeout(render,30));
  addEventListener('datoya:location-changed',()=>setTimeout(render,80));
  addEventListener('hashchange',()=>setTimeout(boot,80));
  setInterval(()=>{if(isHome()&&document.querySelector('.dy-impulse-live:not(.dy-demo-live-card)'))render()},60000);
  boot();
})();
