// DatoYa — Impulso de la semana: solicitudes, regalos, revision, diseno y publicacion.
// Se ejecuta despues del dominio de negocios y antes de iniciar server.js.
const fs=require('fs');
const path=require('path');
const {db}=require('./db');

db.exec(`
CREATE TABLE IF NOT EXISTS weekly_impulses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  business_id INTEGER NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
  title TEXT,
  description TEXT,
  regular_price INTEGER,
  offer_price INTEGER,
  stock INTEGER,
  original_image_data TEXT,
  designed_image_data TEXT,
  placement_type TEXT NOT NULL DEFAULT 'requested',
  status TEXT NOT NULL DEFAULT 'pending_review',
  starts_at TEXT,
  ends_at TEXT,
  rejection_reason TEXT,
  created_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  approved_by_user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);
`);

const serverPath=path.join(__dirname,'server.js');
let source=fs.readFileSync(serverPath,'utf8');
if(!source.includes('DATOYA WEEKLY IMPULSE V1')){
  const injection=[
    '// ============ DATOYA WEEKLY IMPULSE V1 ============',
    'function __weeklyNow(){ return new Date().toISOString(); }',
    'function __weeklyRefreshStates(){',
    '  const now=__weeklyNow();',
    "  try{ db.prepare(\"UPDATE weekly_impulses SET status='active',updated_at=? WHERE status='scheduled' AND starts_at IS NOT NULL AND starts_at<=? AND (ends_at IS NULL OR ends_at>?)\").run(now,now,now); }catch(_){}",
    "  try{ db.prepare(\"UPDATE weekly_impulses SET status='ended',updated_at=? WHERE status IN ('scheduled','active','approved') AND ends_at IS NOT NULL AND ends_at<=?\").run(now,now); }catch(_){}",
    '}',
    'function __weeklyRow(row){',
    '  if(!row) return row;',
    '  row.regular_price=row.regular_price==null?null:Number(row.regular_price);',
    '  row.offer_price=row.offer_price==null?null:Number(row.offer_price);',
    '  row.stock=row.stock==null?null:Number(row.stock);',
    '  return row;',
    '}',
    'function __weeklyImage(value){',
    "  const s=String(value||'');",
    "  if(!s.startsWith('data:image/')) return null;",
    "  if(s.length>1800000) return null;",
    '  return s;',
    '}',
    "app.get('/api/weekly-impulses/mine',auth,(req,res)=>{",
    '  __weeklyRefreshStates();',
    "  const rows=db.prepare('SELECT wi.*,b.name AS business_name,b.status AS business_status,c.name AS comuna FROM weekly_impulses wi JOIN businesses b ON b.id=wi.business_id LEFT JOIN comunas c ON c.id=b.comuna_id WHERE b.owner_user_id=? ORDER BY wi.created_at DESC').all(req.user.id).map(__weeklyRow);",
    '  res.json({impulses:rows});',
    '});',
    "app.post('/api/weekly-impulses',auth,(req,res)=>{",
    '  const body=req.body||{};',
    '  const businessId=Number(body.business_id||0);',
    "  const business=db.prepare('SELECT * FROM businesses WHERE id=? AND owner_user_id=?').get(businessId,req.user.id);",
    "  if(!business) return res.status(404).json({error:'Negocio no encontrado'});",
    "  if(business.status!=='active') return res.status(400).json({error:'Tu negocio debe estar aprobado y activo para solicitar un Impulso de la semana'});",
    "  const title=String(body.title||'').trim().slice(0,120);",
    "  const description=String(body.description||'').trim().slice(0,500);",
    '  const regular=Number(body.regular_price||0),offer=Number(body.offer_price||0),stock=Number(body.stock||0);',
    '  const image=__weeklyImage(body.original_image_data);',
    "  if(title.length<3) return res.status(400).json({error:'Escribe el nombre de la oferta'});",
    "  if(!offer||offer<1) return res.status(400).json({error:'Ingresa un precio de oferta valido'});",
    "  if(regular>0&&offer>regular) return res.status(400).json({error:'El precio de oferta no puede ser mayor al precio normal'});",
    "  if(!image) return res.status(400).json({error:'Sube una foto valida de la oferta'});",
    '  const now=__weeklyNow();',
    "  const result=db.prepare('INSERT INTO weekly_impulses(business_id,title,description,regular_price,offer_price,stock,original_image_data,placement_type,status,created_by_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(businessId,title,description,regular||null,offer,stock>=0?stock:null,image,'requested','pending_review',req.user.id,now,now);",
    '  const id=Number(result.lastInsertRowid);',
    "  const admins=db.prepare(\"SELECT id FROM users WHERE role='admin' AND is_active=1\").all();",
    "  for(const a of admins) notify(a.id,'impulso_semanal','Nueva solicitud de Impulso de la semana: '+business.name,'#/admin/impulso-semanal');",
    "  res.json({ok:true,id,message:'Tu oferta fue enviada a revision'});",
    '});',
    "app.put('/api/weekly-impulses/:id/submit',auth,(req,res)=>{",
    '  const id=Number(req.params.id);',
    "  const row=db.prepare('SELECT wi.*,b.owner_user_id,b.name AS business_name,b.status AS business_status FROM weekly_impulses wi JOIN businesses b ON b.id=wi.business_id WHERE wi.id=?').get(id);",
    "  if(!row||Number(row.owner_user_id)!==Number(req.user.id)) return res.status(404).json({error:'Invitacion no encontrada'});",
    "  if(!['invited','draft','rejected'].includes(String(row.status))) return res.status(400).json({error:'Esta solicitud ya no se puede editar'});",
    "  if(row.business_status!=='active') return res.status(400).json({error:'Tu negocio debe estar activo'});",
    '  const body=req.body||{};',
    "  const title=String(body.title||'').trim().slice(0,120);",
    "  const description=String(body.description||'').trim().slice(0,500);",
    '  const regular=Number(body.regular_price||0),offer=Number(body.offer_price||0),stock=Number(body.stock||0);',
    '  const image=__weeklyImage(body.original_image_data);',
    "  if(title.length<3||!offer||!image) return res.status(400).json({error:'Completa oferta, precio y foto antes de enviar'});",
    "  if(regular>0&&offer>regular) return res.status(400).json({error:'El precio de oferta no puede ser mayor al precio normal'});",
    '  const now=__weeklyNow();',
    "  db.prepare(\"UPDATE weekly_impulses SET title=?,description=?,regular_price=?,offer_price=?,stock=?,original_image_data=?,designed_image_data=NULL,status='pending_review',rejection_reason=NULL,updated_at=? WHERE id=?\").run(title,description,regular||null,offer,stock>=0?stock:null,image,now,id);",
    "  const admins=db.prepare(\"SELECT id FROM users WHERE role='admin' AND is_active=1\").all();",
    "  for(const a of admins) notify(a.id,'impulso_semanal','Oferta semanal lista para revision: '+row.business_name,'#/admin/impulso-semanal');",
    "  res.json({ok:true,message:'Oferta enviada a revision'});",
    '});',
    "app.get('/api/weekly-impulses/active',(req,res)=>{",
    '  __weeklyRefreshStates();',
    '  const comunaId=Number(req.query.comuna_id||0);',
    "  let sql=\"SELECT wi.*,b.name AS business_name,b.slug AS business_slug,b.business_type,c.name AS comuna FROM weekly_impulses wi JOIN businesses b ON b.id=wi.business_id LEFT JOIN comunas c ON c.id=b.comuna_id WHERE wi.status='active' AND b.status='active'\";",
    '  const params=[];',
    "  if(comunaId){ sql+=' AND b.comuna_id=?'; params.push(comunaId); }",
    "  sql+=' ORDER BY wi.updated_at DESC LIMIT 8';",
    '  res.json({impulses:db.prepare(sql).all(...params).map(__weeklyRow)});',
    '});',
    "app.get('/api/admin/marketplace/summary',auth,requireRole('admin'),(req,res)=>{",
    '  __weeklyRefreshStates();',
    "  const businesses=db.prepare(\"SELECT COUNT(*) c FROM businesses\").get().c;",
    "  const pendingBusinesses=db.prepare(\"SELECT COUNT(*) c FROM businesses WHERE status='pending_review'\").get().c;",
    "  const activeBusinesses=db.prepare(\"SELECT COUNT(*) c FROM businesses WHERE status='active'\").get().c;",
    "  const pendingWeekly=db.prepare(\"SELECT COUNT(*) c FROM weekly_impulses WHERE status='pending_review'\").get().c;",
    "  const activeWeekly=db.prepare(\"SELECT COUNT(*) c FROM weekly_impulses WHERE status='active'\").get().c;",
    '  res.json({businesses:Number(businesses||0),pending_businesses:Number(pendingBusinesses||0),active_businesses:Number(activeBusinesses||0),pending_weekly:Number(pendingWeekly||0),active_weekly:Number(activeWeekly||0)});',
    '});',
    "app.get('/api/admin/marketplace/businesses',auth,requireRole('admin'),(req,res)=>{",
    "  const rows=db.prepare('SELECT b.*,u.name AS owner_name,u.email AS owner_email,c.name AS comuna,r.name AS region FROM businesses b JOIN users u ON u.id=b.owner_user_id LEFT JOIN comunas c ON c.id=b.comuna_id LEFT JOIN regions r ON r.id=c.region_id ORDER BY b.created_at DESC').all();",
    '  for(const b of rows) b.categories=db.prepare(\"SELECT mc.name,mc.icon,bcl.is_primary FROM business_category_links bcl JOIN market_categories mc ON mc.id=bcl.category_id WHERE bcl.business_id=? ORDER BY bcl.is_primary DESC,mc.sort_order\").all(b.id);',
    '  res.json({businesses:rows});',
    '});',
    "app.put('/api/admin/marketplace/businesses/:id/status',auth,requireRole('admin'),(req,res)=>{",
    '  const id=Number(req.params.id);',
    "  const allowed=['pending_review','active','paused','rejected','suspended'];",
    "  const status=String(req.body?.status||'');",
    "  if(!allowed.includes(status)) return res.status(400).json({error:'Estado invalido'});",
    "  const b=db.prepare('SELECT * FROM businesses WHERE id=?').get(id);",
    "  if(!b) return res.status(404).json({error:'Negocio no encontrado'});",
    "  db.prepare('UPDATE businesses SET status=?,updated_at=? WHERE id=?').run(status,__weeklyNow(),id);",
    "  const text=status==='active'?'Tu negocio '+b.name+' fue aprobado y ya puede publicarse en DatoYa.':'El estado de '+b.name+' cambio a '+status+'.';",
    "  notify(b.owner_user_id,'negocio',text,'#/perfil');",
    '  res.json({ok:true});',
    '});',
    "app.get('/api/admin/weekly-impulses',auth,requireRole('admin'),(req,res)=>{",
    '  __weeklyRefreshStates();',
    "  const rows=db.prepare('SELECT wi.*,b.name AS business_name,b.slug AS business_slug,b.status AS business_status,c.name AS comuna,u.name AS owner_name,u.email AS owner_email FROM weekly_impulses wi JOIN businesses b ON b.id=wi.business_id JOIN users u ON u.id=b.owner_user_id LEFT JOIN comunas c ON c.id=b.comuna_id ORDER BY wi.created_at DESC').all().map(__weeklyRow);",
    '  res.json({impulses:rows});',
    '});',
    "app.post('/api/admin/weekly-impulses/gift',auth,requireRole('admin'),(req,res)=>{",
    '  const businessId=Number(req.body?.business_id||0);',
    "  const b=db.prepare(\"SELECT * FROM businesses WHERE id=? AND status='active'\").get(businessId);",
    "  if(!b) return res.status(404).json({error:'Selecciona un negocio activo'});",
    "  const existing=db.prepare(\"SELECT id FROM weekly_impulses WHERE business_id=? AND status IN ('invited','pending_review','scheduled','active') ORDER BY id DESC LIMIT 1\").get(businessId);",
    "  if(existing) return res.status(409).json({error:'Este negocio ya tiene una invitacion u oferta semanal en curso'});",
    '  const now=__weeklyNow();',
    "  const result=db.prepare('INSERT INTO weekly_impulses(business_id,placement_type,status,created_by_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(businessId,'gifted','invited',req.user.id,now,now);",
    '  const id=Number(result.lastInsertRowid);',
    "  notify(b.owner_user_id,'impulso_semanal','DatoYa te regalo un Impulso de la semana. Prepara tu oferta y enviala a revision.','#/impulso-semanal-nuevo/'+businessId+'/'+id);",
    '  res.json({ok:true,id});',
    '});',
    "app.put('/api/admin/weekly-impulses/:id/design',auth,requireRole('admin'),(req,res)=>{",
    '  const id=Number(req.params.id),image=__weeklyImage(req.body?.designed_image_data);',
    "  if(!image) return res.status(400).json({error:'La pieza grafica no es valida'});",
    "  const row=db.prepare('SELECT id FROM weekly_impulses WHERE id=?').get(id);",
    "  if(!row) return res.status(404).json({error:'Oferta no encontrada'});",
    "  db.prepare('UPDATE weekly_impulses SET designed_image_data=?,updated_at=? WHERE id=?').run(image,__weeklyNow(),id);",
    '  res.json({ok:true});',
    '});',
    "app.post('/api/admin/weekly-impulses/:id/approve',auth,requireRole('admin'),(req,res)=>{",
    '  const id=Number(req.params.id);',
    "  const row=db.prepare('SELECT wi.*,b.owner_user_id,b.name AS business_name FROM weekly_impulses wi JOIN businesses b ON b.id=wi.business_id WHERE wi.id=?').get(id);",
    "  if(!row) return res.status(404).json({error:'Oferta no encontrada'});",
    "  if(row.status!=='pending_review') return res.status(400).json({error:'La oferta no esta pendiente de revision'});",
    "  if(!row.original_image_data) return res.status(400).json({error:'La oferta no tiene foto original'});",
    "  const type=['paid','gifted','launch'].includes(String(req.body?.placement_type))?String(req.body.placement_type):(row.placement_type==='gifted'?'gifted':'paid');",
    '  const start=req.body?.starts_at?new Date(req.body.starts_at):new Date();',
    '  if(Number.isNaN(start.getTime())) return res.status(400).json({error:"Fecha de inicio invalida"});',
    '  const end=req.body?.ends_at?new Date(req.body.ends_at):new Date(start.getTime()+7*24*60*60*1000);',
    '  if(Number.isNaN(end.getTime())||end<=start) return res.status(400).json({error:"La fecha de termino debe ser posterior al inicio"});',
    '  const startIso=start.toISOString(),endIso=end.toISOString(),now=__weeklyNow();',
    "  const status=startIso>now?'scheduled':'active';",
    '  const design=row.designed_image_data||(req.body?.use_original?row.original_image_data:null);',
    "  if(!design) return res.status(400).json({error:'Primero crea la version grafica DatoYa o elige usar la foto original'});",
    "  db.prepare('UPDATE weekly_impulses SET designed_image_data=?,placement_type=?,status=?,starts_at=?,ends_at=?,approved_by_user_id=?,rejection_reason=NULL,updated_at=? WHERE id=?').run(design,type,status,startIso,endIso,req.user.id,now,id);",
    "  notify(row.owner_user_id,'impulso_semanal','Tu Impulso de la semana fue aprobado. Estara visible hasta '+end.toLocaleDateString('es-CL')+'.','#/perfil');",
    '  res.json({ok:true,status,starts_at:startIso,ends_at:endIso});',
    '});',
    "app.post('/api/admin/weekly-impulses/:id/reject',auth,requireRole('admin'),(req,res)=>{",
    '  const id=Number(req.params.id);',
    "  const reason=String(req.body?.reason||'Necesitamos que ajustes la oferta antes de publicarla.').trim().slice(0,500);",
    "  const row=db.prepare('SELECT wi.*,b.owner_user_id FROM weekly_impulses wi JOIN businesses b ON b.id=wi.business_id WHERE wi.id=?').get(id);",
    "  if(!row) return res.status(404).json({error:'Oferta no encontrada'});",
    "  db.prepare(\"UPDATE weekly_impulses SET status='rejected',rejection_reason=?,updated_at=? WHERE id=?\").run(reason,__weeklyNow(),id);",
    "  notify(row.owner_user_id,'impulso_semanal','Tu oferta semanal necesita cambios: '+reason,'#/perfil');",
    '  res.json({ok:true});',
    '});',
    '// ============ FIN DATOYA WEEKLY IMPULSE V1 ============',
    ''
  ].join('\n');
  source=source.replace('// ============ CATÁLOGOS ============',injection+'\n// ============ CATÁLOGOS ============');
  fs.writeFileSync(serverPath,source);
}
console.log('[DatoYa] Flujo de Impulso de la semana preparado.');
