/* DatoYa — Mercado Pago comercial: conexión del negocio + pago del pedido. */
(() => {
  if(typeof routes==='undefined'||typeof view==='undefined'||typeof api!=='function')return;
  const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

  routes['mi-negocio-pagos']=async function(id){
    if(!ME){location.hash='#/login';return;}
    const businessId=Number(String(id||'').split('?')[0]||0);if(!businessId){location.hash='#/perfil';return;}
    const [{business},status]=await Promise.all([api('/businesses/'+businessId+'/manage'),api('/businesses/'+businessId+'/mercadopago/status').catch(e=>({error:e.message,connected:false,integration:{}}))]);
    const integration=status.integration||{};const mode=status.payment_mode||'disconnected';const testMode=mode==='test';const liveBlocked=mode==='live_blocked';
    view.innerHTML=`<div class="dy-commerce-page"><a href="#/mi-negocio/${businessId}" class="dy-public-back">← ${h(business.name)}</a><div class="dy-commerce-head"><span>PAGOS</span><h1>Mercado Pago</h1><p>Conecta la cuenta del negocio para recibir pagos online con split automático de la comisión DatoYa.</p></div>${testMode?`<div class="dy-mp-test-banner"><b>🧪 MODO TEST ACTIVO</b><span>Esta cuenta Mercado Pago es de prueba. DatoYa usará checkout sandbox y no dinero real.</span></div>`:liveBlocked?`<div class="dy-mp-live-blocked"><b>🔒 PAGOS REALES BLOQUEADOS</b><span>La cuenta conectada es live, pero DatoYa no permitirá cobros reales hasta terminar la validación sandbox.</span></div>`:''}<section class="dy-commerce-card">${status.error?`<div class="dy-commerce-note"><b>No pudimos consultar Mercado Pago</b><p>${h(status.error)}</p></div>`:status.connected?`<div class="dy-payment-connected"><span>✓</span><div><h2>Cuenta conectada</h2><p>${status.account?.nickname?h(status.account.nickname):'Mercado Pago autorizado'}${status.account?.email?' · '+h(status.account.email):''}</p><small>${testMode?'🧪 Modo TEST':liveBlocked?'🔒 Modo real bloqueado':'Modo real'} · Comisión DatoYa configurada: ${Number(status.commission_pct||0)}%</small></div></div><div class="dy-commerce-note"><b>Cómo funciona</b><p>Cuando un cliente paga un pedido, Mercado Pago procesa el cobro con la cuenta de este negocio y DatoYa descuenta su comisión mediante marketplace split.</p></div>`:!integration.marketplace_oauth?`<div class="dy-commerce-note"><b>Integración técnica pendiente</b><p>Falta completar las credenciales OAuth de Mercado Pago en Render antes de conectar comercios.</p></div>`:`<div class="dy-payment-connect"><span>💳</span><h2>Conecta Mercado Pago</h2><p>Autoriza a DatoYa para generar cobros de tus pedidos. DatoYa no guarda tu contraseña de Mercado Pago.</p><button class="btn btn-primary" id="dy-connect-mp">Conectar Mercado Pago</button></div>`}</section><section class="dy-commerce-card dy-mp-test-guide"><span class="dy-mp-test-kicker">PRUEBA SEGURA MERCADO PAGO</span><h2>Usa tus cuentas demo así</h2><div class="dy-mp-test-steps"><div><b>1</b><span>Conecta aquí la cuenta <strong>vendedor TEST</strong> de Mercado Pago.</span></div><div><b>2</b><span>Desde otra cuenta DatoYa crea un pedido de prueba.</span></div><div><b>3</b><span>Paga usando la cuenta <strong>comprador TEST</strong>.</span></div><div><b>4</b><span>Vuelve a DatoYa y confirma pago, comisión, webhook y estado del pedido.</span></div></div><p class="dy-mp-test-warning">⚠️ No uses cuentas ni tarjetas reales durante esta validación.</p></section><section class="dy-commerce-card"><h2>Estado de la integración</h2><div class="dy-payment-checks"><span>${integration.marketplace_oauth?'✅':'○'} OAuth para negocios</span><span>${integration.webhooks?'✅':'○'} Webhooks de pago</span><span>${integration.ready_for_test?'✅':'○'} Preparada para pruebas</span></div></section></div>`;
    document.getElementById('dy-connect-mp')?.addEventListener('click',async e=>{const btn=e.currentTarget;btn.disabled=true;btn.textContent='Abriendo Mercado Pago…';try{const r=await api('/businesses/'+businessId+'/mercadopago/connect');if(!r.url)throw new Error('No recibimos la URL de autorización');location.href=r.url;}catch(err){btn.disabled=false;btn.textContent='Conectar Mercado Pago';toast?.(err.message,'err')}});
  };

  const prevBusiness=routes['mi-negocio'];
  if(prevBusiness)routes['mi-negocio']=async function(id){await prevBusiness.apply(this,arguments);const businessId=Number(String(id||'').split('?')[0]||0),tools=document.querySelector('.dy-business-tools');if(tools&&businessId&&!tools.querySelector('[data-payment-tool]'))tools.insertAdjacentHTML('beforeend',`<a data-payment-tool href="#/mi-negocio-pagos/${businessId}"><span>💳</span><b>Mercado Pago</b><small>Conecta pagos online para tus pedidos.</small></a>`);};

  const prevOrders=routes.pedidos;
  if(prevOrders)routes.pedidos=async function(){await prevOrders.apply(this,arguments);if(!ME)return;try{const {orders=[]}=await api('/orders/mine'),cards=[...document.querySelectorAll('.dy-order-card')];await Promise.all(orders.map(async(o,index)=>{if(o.payment_status==='paid'||o.status==='cancelled'||o.status==='completed')return;const card=cards[index];if(!card)return;const s=await api('/orders/'+o.id+'/mercadopago/status').catch(()=>null);if(!s)return;if(s.payment_mode==='live_blocked'){const card=cards[index];if(card&&!card.querySelector('.dy-mp-block-note'))card.insertAdjacentHTML('beforeend','<div class="dy-commerce-note dy-mp-block-note"><b>🔒 Mercado Pago real bloqueado</b><p>Esta beta solo permite pagos TEST hasta terminar la validación sandbox.</p></div>');return;}if(!s.available)return;const area=card.querySelector('.dy-order-actions')||card;const btn=document.createElement('button');btn.className='btn btn-primary btn-sm';btn.type='button';btn.textContent=s.payment_mode==='test'?'🧪 Pagar TEST con Mercado Pago':'💳 Pagar con Mercado Pago';btn.onclick=()=>dyPayOrder(o.id,btn);area.appendChild(btn);}));}catch(_){}};

  window.dyPayOrder=async function(id,button){const btn=button||null;if(btn){btn.disabled=true;btn.textContent='Preparando pago TEST…';}try{const r=await api('/orders/'+id+'/mercadopago/checkout',{method:'POST'});if(!r.checkout_url)throw new Error('Mercado Pago no devolvió un enlace de pago');location.href=r.checkout_url;}catch(err){if(btn){btn.disabled=false;btn.textContent='🧪 Pagar TEST con Mercado Pago';}toast?.(err.message,'err')}};
})();
