// DatoYa — DatoYa PRO y pagos profesionales separados.
(function(){
  const money=n=>'$'+Math.round(Number(n||0)).toLocaleString('es-CL');
  const safe=s=>typeof esc==='function'?esc(s):String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let MPCFG=null;
  async function loadCfg(){if(!MPCFG)MPCFG=await api('/mercadopago/config');return MPCFG;}
  function css(){return `<style>.pro-hero,.earn-hero{background:linear-gradient(135deg,#071d49,#0d47a1);color:#fff;border-radius:24px;padding:28px 22px;margin-bottom:18px}.pro-hero h1,.earn-hero h1{margin:0 0 8px;font-size:30px}.pro-grid,.earn-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.pro-plan,.mp-box,.earn-card{border:1px solid #e5e7eb;border-radius:18px;background:#fff;padding:18px}.pro-plan.recommended{border:2px solid #ff9800}.pro-chip{display:inline-block;background:#fff3e0;color:#b45309;font-weight:800;padding:5px 9px;border-radius:999px;font-size:12px}.pro-price{font-size:32px;font-weight:900;margin:10px 0}.pro-price small{font-size:14px;color:#64748b}.pro-benefits{list-style:none;padding:0}.pro-benefits li{padding:7px 0}.earn-value{font-size:27px;font-weight:900;margin-top:5px}.mp-ok{color:#087f5b;font-weight:800}.mp-payment-box{margin-top:12px;padding-top:12px;border-top:1px dashed #d6d9df}.mp-pill{display:inline-block;border-radius:999px;background:#eef2ff;padding:4px 8px;font-size:12px;font-weight:800}@media(max-width:640px){.pro-grid,.earn-grid{grid-template-columns:1fr}.pro-hero h1,.earn-hero h1{font-size:26px}}</style>`;}
  window.mpSubscribe=async plan=>{try{const r=await api('/pro/subscribe',{method:'POST',body:{plan}});if(!r.checkout_url)return toast('Mercado Pago no devolvió checkout','err');location.href=r.checkout_url;}catch(e){toast(e.message,'err')}};
  window.mpConnect=async()=>{try{const r=await api('/mercadopago/connect');if(!r.url)return toast('No se pudo iniciar conexión','err');location.href=r.url;}catch(e){toast(e.message,'err')}};
  window.mpManage=()=>{window.open('https://www.mercadopago.cl/','_blank','noopener,noreferrer')};
  window.mpCancelPro=async()=>{if(!confirm('¿Cancelar la renovación de DatoYa PRO?'))return;try{await api('/pro/cancel',{method:'POST'});MPCFG=null;toast('Suscripción cancelada','ok');route();}catch(e){toast(e.message,'err')}};
  window.mpPayJob=async jobId=>{try{const r=await api('/jobs/'+jobId+'/payment/preference',{method:'POST'});if(!r.checkout_url)return toast('No se recibió URL de pago','err');location.href=r.checkout_url;}catch(e){toast(e.message,'err')}};

  async function renderPro(){const cfg=await loadCfg();let status=null;if(ME)status=await api('/pro/status').catch(()=>null);const annualEq=Math.round(cfg.pro.annual/12),isWorker=ME?.role==='trabajador',active=!!status?.is_pro,sub=status?.subscription;const button=plan=>!ME?'<a class="btn btn-primary btn-block" href="#/registro">Crear cuenta profesional</a>':!isWorker?'<button class="btn btn-ghost btn-block" disabled>Disponible para profesionales</button>':active?'<button class="btn btn-green btn-block" disabled>✓ PRO activo</button>':`<button class="btn btn-primary btn-block" onclick="mpSubscribe('${plan}')">Suscribirme con Mercado Pago</button>`;view.innerHTML=css()+`<div class="pro-hero"><span class="pro-chip">DATOYA PRO</span><h1>Más visibilidad. Más oportunidades.</h1><p>PRO es solo tu suscripción de beneficios profesionales. Tus cobros de trabajos están separados en Mis ganancias.</p></div><div class="pro-grid"><div class="pro-plan"><h2>Mensual</h2><div class="pro-price">${money(cfg.pro.monthly)} <small>/ mes</small></div><ul class="pro-benefits"><li>✓ Insignia PRO</li><li>✓ Mejor posición entre resultados relevantes</li><li>✓ Más espacio de portafolio</li><li>✓ Estadísticas y actividad</li><li>✓ Soporte prioritario</li></ul>${button('monthly')}</div><div class="pro-plan recommended"><span class="pro-chip">MEJOR VALOR</span><h2>Anual</h2><div class="pro-price">${money(cfg.pro.annual)} <small>/ año</small></div><p class="muted">Equivale a ${money(annualEq)}/mes · ahorro ${money(cfg.pro.annual_saving)}.</p><ul class="pro-benefits"><li>✓ Todo lo del plan mensual</li><li>✓ 12 meses de PRO</li><li>✓ Un solo precio anual</li></ul>${button('annual')}</div></div>${active?`<div class="mp-box" style="margin-top:16px"><h3>⭐ Tu DatoYa PRO está activo</h3><p>Plan: <b>${safe(sub?.plan_code||'PRO')}</b> · Estado: <b>${safe(sub?.status||'activo')}</b></p><button class="btn btn-outline" onclick="mpCancelPro()">Cancelar renovación</button></div>`:''}`;}

  async function renderGanancias(){if(!ME){location.hash='#/login';return}if(ME.role!=='trabajador'){view.innerHTML='<div class="empty">Mis ganancias está disponible para profesionales.</div>';return}const cfg=await loadCfg();const [conn,jobsData]=await Promise.all([api('/mercadopago/connection').catch(()=>({connected:false,reason:'unavailable'})),api('/jobs').catch(()=>({jobs:[]}))]);const jobs=jobsData.jobs||[];const rows=[];for(const j of jobs){let state=null;try{state=await api('/jobs/'+j.id+'/payment')}catch(_){}const b=state?.breakdown||{};const amount=Number(b.seller_net_estimate ?? j.worker_amount ?? 0);const providerStatus=String(state?.payment?.status||'').toLowerCase(),paid=['approved','paid','test_paid_after_approval'].includes(providerStatus);rows.push({id:j.id,title:j.title||j.request_title||('Trabajo #'+j.id),amount,status:paid?'Pago registrado':(j.status==='FINALIZADO'?'Trabajo finalizado · pago no confirmado':'Pendiente'),paid});}const total=rows.filter(x=>x.paid).reduce((a,x)=>a+x.amount,0),pending=rows.filter(x=>!x.paid).reduce((a,x)=>a+x.amount,0);const mpPanel=conn.connected?`<p class="mp-ok">✓ Mercado Pago conectado</p><p class="small muted">Conexión OAuth validada con Mercado Pago. La disponibilidad del dinero y las transferencias bancarias se administran en Mercado Pago.</p><button class="btn btn-outline btn-block" onclick="mpManage()">Administrar conexión</button>`:`<p><b>Mercado Pago · No conectado</b></p><p class="small muted">DatoYa no solicita cuentas bancarias ni credenciales. La vinculación se realiza en el sitio oficial de Mercado Pago.</p>${cfg.integration.marketplace_oauth?'<button class="btn btn-primary btn-block" onclick="mpConnect()">Conectar Mercado Pago</button>':'<button class="btn btn-primary btn-block" disabled>Conexión temporalmente no disponible</button>'}`;view.innerHTML=css()+`<div class="earn-hero"><h1>💰 Mis ganancias</h1><p>Consulta pagos registrados de tus trabajos. DatoYa no funciona como billetera.</p></div><div class="earn-grid"><div class="earn-card"><div class="small muted">Pagos confirmados</div><div class="earn-value">${money(total)}</div></div><div class="earn-card"><div class="small muted">Sin pago confirmado</div><div class="earn-value">${money(pending)}</div></div></div><div class="mp-box" style="margin-top:14px"><h3>Mercado Pago</h3>${mpPanel}</div><div class="card" style="margin-top:14px"><h3>Movimientos</h3>${rows.length?rows.map(x=>`<div class="row between" style="padding:11px 0;border-bottom:1px solid var(--borde)"><div><b>${safe(x.title)}</b><div class="small muted">Trabajo #${x.id} · ${safe(x.status)}</div></div><b>${money(x.amount)}</b></div>`).join(''):'<div class="empty">Todavía no tienes movimientos.</div>'}</div>`;}

  async function appendPaymentControls(){if(!ME)return;let data;try{data=await api('/jobs')}catch(_){return}const jobs=data.jobs||[],cards=[...document.querySelectorAll('#view .card')];for(let i=0;i<Math.min(jobs.length,cards.length);i++){const j=jobs[i],card=cards[i];if(card.querySelector('.mp-payment-box'))continue;let state;try{state=await api('/jobs/'+j.id+'/payment')}catch(_){continue}const status=String(state.payment?.status||'sin_pago'),box=document.createElement('div');box.className='mp-payment-box';let html=`<div class="small">Pago: <span class="mp-pill">${safe(status)}</span></div>`;if(ME.role==='cliente'&&!['approved','FINALIZADO','CANCELADO','DISPUTA'].includes(status)&&['TRABAJADOR_SELECCIONADO','CONFIRMADO','EN_PROCESO'].includes(j.status))html+=state.worker_connected?`<button class="btn btn-primary btn-sm" style="margin-top:8px" onclick="mpPayJob(${j.id})">Pagar con Mercado Pago</button>`:'<div class="small muted">El profesional debe conectar Mercado Pago antes del pago.</div>';if(ME.role==='trabajador'&&!state.worker_connected)html+='<div class="small muted">Configura tus cobros en <a href="#/ganancias">Mis ganancias</a>.</div>';if(state.breakdown&&ME.role==='trabajador')html+=`<div class="small muted">Comisión DatoYa: ${money(state.breakdown.datoya_fee)} · Recibes estimado: ${money(state.breakdown.seller_net_estimate)}</div>`;box.innerHTML=html;card.appendChild(box);}}

  function addProfileLinks(){if(!ME||ME.role!=='trabajador')return;if(document.querySelector('[data-dy-money-links]'))return;const editor=document.querySelector('#worker-profile-editor')||document.querySelector('#view .profile-head');if(!editor)return;const box=document.createElement('div');box.className='card';box.dataset.dyMoneyLinks='1';box.style.marginTop='12px';box.innerHTML='<h3 style="margin-top:0">Cuenta profesional</h3><a href="#/ganancias" class="row between" style="padding:12px 0;border-bottom:1px solid var(--borde);color:var(--txt)"><span>💰 Mis ganancias</span><span>→</span></a><a href="#/pro" class="row between" style="padding:12px 0;color:var(--txt)"><span>⭐ DatoYa PRO</span><span>→</span></a>';editor.insertAdjacentElement('afterend',box);}
  function install(){if(typeof routes==='undefined')return setTimeout(install,50);routes.pro=renderPro;routes.ganancias=renderGanancias;const baseProfile=routes.perfil;if(baseProfile&&!baseProfile.__moneyWrapped){const wrapped=async function(){const r=await baseProfile.apply(this,arguments);addProfileLinks();return r};wrapped.__moneyWrapped=true;routes.perfil=wrapped}const baseJobs=routes.trabajos;if(baseJobs&&!baseJobs.__mpWrapped){const wrapped=async function(){await baseJobs.apply(this,arguments);await appendPaymentControls()};wrapped.__mpWrapped=true;routes.trabajos=wrapped}}install();
})();
