// DatoYa 2.0 — flujo principal: especialidad -> GPS -> profesionales cercanos
(function(){
  'use strict';
  const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
  const stars=(r,c)=>`<span class="stars">★</span> <b>${Number(r||0).toFixed(1)}</b> <span class="muted small">(${Number(c||0)})</span>`;
  const avatar=(name,color)=>`<div class="avatar" style="background:${color||'#1D4ED8'}">${esc((name||'?')[0].toUpperCase())}</div>`;
  let cats=[],allComunas=[],regions=[],active=false,navigationEpoch=0;
  async function api2(url){const r=await fetch('/api'+url,{headers:{Accept:'application/json'}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'No fue posible cargar los datos');return d;}
  function getView(){return document.querySelector('#view');}
  function isHome(){return location.hash==='#/'||location.hash===''||location.hash==='#';}
  function renderRealHome(){
    const homeRoute=typeof routes!=='undefined'&&typeof routes['']==='function'?routes['']:null;
    if(homeRoute){Promise.resolve(homeRoute()).catch(()=>{if(typeof route==='function')route();});return;}
    if(typeof route==='function'){route();return;}
    if(typeof window.__datoyaNearbyHome==='function')window.__datoyaNearbyHome();
  }
  function goHome(){
    active=false;
    navigationEpoch++;
    if(isHome()){
      // La vista de cercanía puede seguir montada aunque el hash ya sea #/.
      // En ese caso un enlace normal no dispara hashchange: forzamos la ruta real de Inicio.
      renderRealHome();
      return;
    }
    location.hash='#/';
  }
  function renderShell(){const view=getView();if(!view)return;view.innerHTML=`<div class="nearby-hero"><span class="nearby-kicker">DATOYA CERCA DE USTED</span><h1>¿Qué profesional necesita?</h1><p>Elija la especialidad y le mostraremos profesionales ordenados por cercanía usando su ubicación.</p></div><div id="nearby-content"></div>`;}
  function categoryGrid(){const box=document.querySelector('#nearby-content');if(!box)return;box.innerHTML=`<h2 class="section-title">Elija una especialidad</h2><div class="cat-grid nearby-cat-grid">${cats.map(c=>`<button class="cat-item" data-cat="${c.id}"><span>${c.icon||'🛠️'}</span>${esc(c.name)}</button>`).join('')}</div><div class="nearby-note">📍 Primero elegimos la especialidad y después usamos su GPS. La ubicación exacta del cliente no se muestra a otros usuarios.</div>`;box.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>chooseCategory(Number(b.dataset.cat))));}
  async function loadCats(){if(!cats.length)cats=(await api2('/categories')).categories||[];}
  async function chooseCategory(id){active=true;const cat=cats.find(c=>Number(c.id)===id);const box=document.querySelector('#nearby-content');if(!box)return;box.innerHTML=`<div class="card nearby-location-card"><h2>${cat?.icon||'🛠️'} ${esc(cat?.name||'Profesionales')}</h2><p>Usaremos su ubicación para ordenar los profesionales por distancia.</p><button id="nearby-gps" class="btn btn-primary btn-block">📍 Usar mi ubicación GPS</button><button id="nearby-manual" class="btn btn-outline btn-block">Elegir comuna manualmente</button><button id="nearby-back" class="btn btn-ghost btn-block">← Cambiar especialidad</button><button id="nearby-home" class="btn btn-ghost btn-block">⌂ Volver al inicio</button></div>`;document.querySelector('#nearby-gps').onclick=()=>locate(id);document.querySelector('#nearby-manual').onclick=()=>manualLocation(id);document.querySelector('#nearby-back').onclick=()=>{active=false;categoryGrid();};document.querySelector('#nearby-home').onclick=goHome;}
  function locate(categoryId){const epoch=navigationEpoch;if(!navigator.geolocation)return manualLocation(categoryId,'Este dispositivo no ofrece GPS.');const box=document.querySelector('#nearby-content');box.innerHTML='<div class="card"><h2>📍 Buscando profesionales cerca de usted…</h2><p>Su navegador pedirá permiso para usar el GPS. La ubicación del cliente se utiliza para calcular resultados y no se publica.</p></div>';navigator.geolocation.getCurrentPosition(p=>{if(epoch===navigationEpoch&&location.hash.startsWith('#/cerca'))showNearby(categoryId,Number(p.coords.latitude),Number(p.coords.longitude),'GPS',epoch);},()=>{if(epoch===navigationEpoch&&location.hash.startsWith('#/cerca'))manualLocation(categoryId,'No se pudo obtener el GPS. Puede elegir su comuna.');},{enableHighAccuracy:true,timeout:12000,maximumAge:120000});}
  async function manualLocation(categoryId,message){try{if(!allComunas.length)allComunas=(await api2('/comunas')).comunas||[];if(!regions.length)regions=(await api2('/regions')).regions||[];}catch(e){return showError(e.message);}const box=document.querySelector('#nearby-content');box.innerHTML=`<div class="card nearby-location-card"><h2>📍 ¿Dónde necesitas el servicio?</h2>${message?`<p class="muted">${esc(message)}</p>`:''}<div class="field"><label>Región</label><select id="nearby-region"><option value="">Selecciona tu región</option>${regions.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join('')}</select></div><div class="field"><label>Comuna</label><select id="nearby-comuna" disabled><option value="">Primero selecciona la región</option></select></div><button id="nearby-show" class="btn btn-primary btn-block" disabled>Ver profesionales que atienden aquí</button><button id="nearby-back2" class="btn btn-ghost btn-block">← Volver</button><button id="nearby-home2" class="btn btn-ghost btn-block">⌂ Volver al inicio</button></div>`;const region=document.querySelector('#nearby-region'),comuna=document.querySelector('#nearby-comuna'),show=document.querySelector('#nearby-show');region.onchange=()=>{const filtered=allComunas.filter(c=>String(c.region_id)===String(region.value));comuna.disabled=!filtered.length;comuna.innerHTML='<option value="">Selecciona tu comuna</option>'+filtered.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('');show.disabled=true;};comuna.onchange=()=>{show.disabled=!comuna.value;};show.onclick=()=>showByComuna(categoryId,Number(comuna.value));document.querySelector('#nearby-back2').onclick=()=>chooseCategory(categoryId);document.querySelector('#nearby-home2').onclick=goHome;}
  function emptyActions(categoryId){return `<div class="nearby-empty-actions"><button class="btn btn-outline" data-nearby-change>🔄 Cambiar especialidad</button><a class="btn btn-primary" href="#/solicitar">📋 Publicar una solicitud</a><button class="btn btn-ghost" data-nearby-home>⌂ Volver al inicio</button></div>`;}
  function bindResultActions(categoryId){document.querySelector('#nearby-change')?.addEventListener('click',()=>chooseCategory(categoryId));document.querySelectorAll('[data-nearby-change]').forEach(b=>b.addEventListener('click',()=>chooseCategory(categoryId)));document.querySelectorAll('[data-nearby-home]').forEach(b=>b.addEventListener('click',goHome));}
  async function showByComuna(categoryId,comunaId){const box=document.querySelector('#nearby-content'),selected=allComunas.find(c=>Number(c.id)===comunaId);if(!selected)return;box.innerHTML='<div class="card"><h2>🔎 Buscando…</h2></div>';try{const r=await api2(`/workers/nearby?category_id=${categoryId}&comuna_id=${comunaId}`),workers=r.workers||[],cat=cats.find(c=>Number(c.id)===categoryId);box.innerHTML=`<div class="nearby-results-head"><div><h2>${cat?.icon||'🛠️'} ${esc(cat?.name||'Profesionales')}</h2><p class="muted">📍 Profesionales que atienden en ${esc(selected.name)}</p></div><button id="nearby-change" class="btn btn-outline btn-sm">Cambiar</button></div><div class="cards">${workers.length?workers.map(workerCard).join(''):`<div class="empty">Todavía no hay profesionales de esta especialidad que hayan registrado atención en esta comuna.${emptyActions(categoryId)}</div>`}</div>`;bindResultActions(categoryId);}catch(e){showError(e.message);}}
  async function showNearby(categoryId,lat,lng,source,epoch=navigationEpoch){if(epoch!==navigationEpoch||!location.hash.startsWith('#/cerca'))return;const box=document.querySelector('#nearby-content');if(!box)return;box.innerHTML='<div class="card"><h2>🔎 Buscando…</h2><p>Ordenando profesionales por distancia, especialidad y reputación.</p></div>';let workers=[],used=10;for(const radius of [10,25,40,60]){try{const r=await api2(`/workers/nearby?category_id=${categoryId}&lat=${encodeURIComponent(lat)}&lng=${encodeURIComponent(lng)}&radius_km=${radius}`);if(epoch!==navigationEpoch||!location.hash.startsWith('#/cerca'))return;workers=r.workers||[];used=radius;if(workers.length>=5||radius===60)break;}catch(e){if(epoch===navigationEpoch&&location.hash.startsWith('#/cerca'))showError(e.message);return;}}if(epoch!==navigationEpoch||!box.isConnected)return;const cat=cats.find(c=>Number(c.id)===categoryId);box.innerHTML=`<div class="nearby-results-head"><div><h2>${cat?.icon||'🛠️'} ${esc(cat?.name||'Profesionales')} cerca de usted</h2><p class="muted">📍 ${source==='GPS'?'GPS del cliente':'Comuna seleccionada'} · radio hasta ${used} km</p></div><button id="nearby-change" class="btn btn-outline btn-sm">Cambiar</button></div><div class="cards">${workers.length?workers.map(workerCard).join(''):`<div class="empty">No encontramos profesionales de esta especialidad en el radio disponible.${emptyActions(categoryId)}</div>`}</div><div class="nearby-note">ℹ️ Los resultados se ordenan por distancia. Cuando el profesional tiene GPS habilitado, se usa su ubicación GPS aproximada; si todavía no la registra, DatoYa usa su comuna como referencia.</div>`;bindResultActions(categoryId);}
  function workerCard(w){const verified=w.verified_identity?'<span class="badge-v">✓ Verificado</span>':'';const gps=w.location_source==='GPS'?'<span>📡 GPS</span>':'';return `<div class="wcard"><div class="wcard-top">${avatar(w.name,w.avatar_color)}<div class="wcard-info"><h3>${esc(w.name)}</h3><div class="oficio">${esc(w.oficio||'Profesional')}</div><div class="badges">${verified}</div><div class="wmeta"><span>${stars(w.rating_avg,w.rating_count)}</span><span>🛠️ ${Number(w.jobs_completed||0)} trabajos</span><span>📍 ${esc(w.distance_label||'Cerca de usted')}</span>${gps}</div></div></div><div class="wcard-actions"><a class="btn btn-outline btn-sm" href="#/trabajador/${w.id}">Ver perfil</a><button class="btn btn-primary btn-sm" onclick="solicitarDirecto(${w.id})">Solicitar</button></div></div>`;}
  function showError(msg){const box=document.querySelector('#nearby-content');if(box){box.innerHTML=`<div class="empty"><b>😕</b>${esc(msg)}<button class="btn btn-outline" data-nearby-home>Volver al inicio</button></div>`;box.querySelector('[data-nearby-home]')?.addEventListener('click',goHome);}}
  async function mount(){if(!isHome())return;const view=getView();if(!view)return;try{await loadCats();renderShell();categoryGrid();}catch(e){showError(e.message);}}
  async function mountCategory(){const q=new URLSearchParams(location.hash.split('?')[1]||''),id=Number(q.get('cat'));try{await loadCats();renderShell();if(!cats.some(c=>Number(c.id)===id)){categoryGrid();return;}chooseCategory(id);}catch(e){showError(e.message);}}
  if(typeof routes!=='undefined')routes.cerca=mountCategory;
  window.__datoyaNearbyHome=mount;
  window.__datoyaGoHome=goHome;
  window.addEventListener('hashchange',()=>{active=false;navigationEpoch++;});
  // Delegación en captura: funciona aunque la cabecera sea reemplazada por otro módulo UI.
  document.addEventListener('click',e=>{
    const logo=e.target.closest?.('a.logo');
    if(!logo)return;
    e.preventDefault();
    goHome();
  },true);
  const style=document.createElement('style');style.textContent=`.nearby-hero{padding:26px 4px 18px}.nearby-hero h1{margin:6px 0 8px}.nearby-hero p{color:#64748b;max-width:680px}.nearby-kicker{font-size:12px;font-weight:800;letter-spacing:.08em;color:var(--azul,#1d4ed8)}.nearby-location-card{max-width:620px;margin:0 auto}.nearby-cat-grid{margin-bottom:14px}.nearby-note{padding:12px 14px;border-radius:12px;background:#f1f5f9;color:#475569;font-size:13px;margin:14px 0}.nearby-results-head{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:8px 0 16px}.nearby-results-head h2{margin:0}.nearby-results-head p{margin:5px 0 0}.nearby-results-head .btn{flex:none}.nearby-location-card .btn{margin-top:10px}.nearby-empty-actions{display:flex;flex-direction:column;gap:9px;margin-top:18px}.nearby-empty-actions .btn{width:100%;justify-content:center}@media(max-width:560px){.nearby-results-head{align-items:flex-start}.nearby-results-head h2{font-size:20px}}`;document.head.appendChild(style);
})();