// DatoYa 2.0 — arranque real. DEMO ya no es un modo de ejecución.
const Module=require('module'),path=require('path');
const usePostgres=String(process.env.DB_DRIVER||'').toLowerCase()==='postgres',originalLoad=Module._load,dbFile=path.resolve(__dirname,'db.js'),blocked=new Set([path.resolve(__dirname,'demo_admin_seed.js'),path.resolve(__dirname,'demo_runtime_seed.js'),path.resolve(__dirname,'demo_compat_fix.js'),path.resolve(__dirname,'worker_category_repair.js')]);let pgModule=null;
Module._load=function(request,parent,isMain){try{const resolved=Module._resolveFilename(request,parent,isMain),absolute=path.resolve(resolved);if(blocked.has(absolute))return{};if(usePostgres&&absolute===dbFile){if(!pgModule)pgModule=originalLoad.call(this,path.resolve(__dirname,'db_pg.js'),parent,isMain);return pgModule;}}catch(_){}return originalLoad.apply(this,arguments);};
if(process.env.DATOYA_MIGRATION_TARGET_URL){
  const {execFileSync}=require('child_process');
  execFileSync(process.execPath,[path.join(__dirname,'scripts','migrate_render_to_neon.js')],{stdio:'inherit',env:process.env});
}
try{require('./production_mode_bootstrap');console.log(usePostgres?'[DatoYa] Inicio con PostgreSQL.':'[DatoYa] Inicio con SQLite temporal (pruebas locales).');
 require('./job_record_bootstrap');
 require('./mercadopago_source_bootstrap');require('./mercadopago_fee_policy_bootstrap');require('./hybrid_payment_bootstrap');require('./account_security_bootstrap');require('./marketplace_legal_version_fix');require('./security_events_schema_fix');require('./database_integrity_bootstrap');require('./account_security_delivery_fix');require('./account_security_route_fix');require('./account_security_delivery_guard');require('./session_cookie_fix');require('./session_account_guard');require('./admin_pro_gift_bootstrap');require('./meeting_verification_bootstrap');require('./job_trust_center_bootstrap');require('./dispute_resolution_atomic_guard');require('./job_trust_accounting_fix');require('./accounting_uniqueness_bootstrap');require('./job_mutual_completion_guard');require('./job_flow_guard');require('./accepted_job_chat_guard');require('./chat_security_guard');require('./quote_acceptance_atomic_guard');require('./job_uniqueness_bootstrap');require('./worker_specialties_bootstrap');require('./worker_onboarding_fix');require('./worker_portfolio_bootstrap');require('./worker_search_bootstrap');require('./worker_specialties_discovery_bootstrap');require('./worker_discovery_quality');require('./worker_public_review_fix');require('./worker_profile_validation');require('./review_validation');require('./quote_validation');require('./request_validation');require('./request_photo_validation');require('./request_access_guard');require('./chile_security_bootstrap');require('./production_legacy_guard');require('./marketplace_account_bootstrap_v2');require('./marketplace_weekly_bootstrap');require('./marketplace_products_bootstrap');require('./marketplace_products_route_fix');require('./marketplace_location_privacy_bootstrap');require('./marketplace_commerce_bootstrap');require('./marketplace_commerce_route_fix');require('./marketplace_delivery_bootstrap');require('./email_verification_enforcement_bootstrap');require('./marketplace_account_separation_bootstrap');require('./marketplace_growth_bootstrap');require('./marketplace_promo_analytics_bootstrap');require('./marketplace_integrations_bootstrap');require('./support_center_bootstrap');require('./push_notifications_bootstrap');require('./marketplace_admin_v2_bootstrap');require('./marketplace_hours_bootstrap');require('./beta_private_features_bootstrap');require('./current_legal_consent_enforcement_bootstrap');require('./marketplace_beta_smoketest');require('./territory_start');
 require('./mercadopago_assets');require('./account_security_assets');require('./admin_pro_gift_assets');require('./meeting_verification_assets');require('./job_trust_center_assets');require('./job_detail_assets');require('./job_flow_ui_assets');require('./admin_command_center_assets');require('./admin_revenue_assets');require('./worker_profile_polish_assets');require('./home_search_polish_assets');require('./onboarding_flow_assets');require('./admin_disputes_assets');require('./admin_navigation_polish_assets');require('./worker_specialties_assets');require('./admin_security_assets');require('./phone_security_assets');require('./worker_portfolio_assets');require('./free_beta_security_assets');require('./legal_final_assets');require('./worker_onboarding_assets');require('./professional_account_hub_assets');require('./platform_concept_assets');
 require('./job_record_assets');require('./phase_a_assets');require('./local_market_home_assets');require('./marketplace_account_assets');require('./marketplace_weekly_assets');require('./marketplace_business_assets');require('./marketplace_growth_assets');require('./marketplace_commerce_assets');require('./marketplace_demo_showcase_assets');require('./marketplace_about_assets');require('./marketplace_public_shell_assets');require('./marketplace_hours_assets');require('./marketplace_guided_demo_assets');require('./marketplace_delivery_assets');require('./marketplace_promo_analytics_assets');require('./marketplace_integrations_assets');require('./support_center_assets');require('./admin_support_cases_assets');require('./marketplace_admin_v2_assets');require('./business_impulse_plan_assets');require('./business_hub_assets');require('./beta_private_assets');require('./push_notifications_assets');
}finally{Module._load=originalLoad;}
