// DatoYa — panel permanente de cuenta profesional: portafolio + DatoYa PRO.
(function(){
 if(typeof routes==='undefined'||!routes.perfil)return;
 const old=routes.perfil, safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function load(){const [portfolio,pro]=await Promise.all([api('/worker/portfolio').catch(()=>null),api('/pro/status').catch(()=>null)]);return {portfolio,pro};}
 function cards(d){const p=d.portfolio,pro=d.pro;if(!p&&!pro)return '';
  let html='';
  if(p){const items=p.items||[],limit=Number(p.limit||4);html+=`<section class="card" data-prof-hub-portfolio><div class="row between"><div><h3 style="margin:0">📸 Fotos de mis trabajos</h3><div class="small muted">${items.length} de ${limit} fotos · ${(p.is_pro?'DatoYa PRO':'Plan gratuito')}</div></div></div><p class="small muted">Muestra trabajos reales para que los clientes conozcan tu experiencia.</p>${items.length?`<div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px">${items.map(x=>`<div><img src="${safe(x.data||'')}" alt="${safe(x.caption||'Trabajo realizado')}" style="width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:12px"><div class="small">${safe(x.caption||'')}</div><button class="btn btn-ghost btn-sm" onclick="deleteDatoYaPortfolio(${Number(x.id)})">Eliminar</button></div>`).join('')}</div>`:'<div class="lock-note">Aún no tienes fotos en tu portafolio.</div>'}${items.length<limit?'<button class="btn btn-primary btn-block" style="margin-top:12px" onclick="openDatoYaPortfolioUploader()">📷 Subir foto de un trabajo</button>':''}</section>`;}
  if(pro){const c=pro.config?.pro||{},sub=pro.subscription;html+=`<section class="card" data-prof-hub-pro><div class="row between"><div><h3 style="margin:0">⭐ DatoYa PRO</h3><div class="small muted">${pro.is_pro?'Tu cuenta tiene PRO activo':'Mejora tu perfil profesional'}</div></div>${pro.is_pro?'<span class="pill" style="background:#dcfce7;color:#166534">Activo ✓</span>':''}</div>${pro.is_pro&&sub?`<p class="small">Plan: <b>${safe(sub.plan_code||'PRO')}</b> · Estado: ${safe(sub.status||'activo')}</p>`:`<p class="small muted">PRO permite hasta 12 fotos de trabajos y las funciones PRO que DatoYa tenga habilitadas.</p><div style="display:grid;grid-template-columns:1fr 1fr;gap:9px"><a class="btn btn-outline" href="#/pro">Mensual ${c.monthly?'$'+Number(c.monthly).toLocaleString('es-CL'):''}</a><a class="btn btn-primary" href="#/pro">Anual ${c.annual?'$'+Number(c.annual).toLocaleString('es-CL'):''}</a></div><a href="#/pro" class="small" style="display:block;text-align:center;margin-top:10px">Ver planes y condiciones</a>`}</section>`;}
  return html;
 }
 routes.perfil=async function(){const r=await old.apply(this,arguments);if(!ME||ME.role!=='trabajador')return r;const d=await load();if(!document.querySelector('[data-prof-hub-portfolio]')&&!document.querySelector('[data-prof-hub-pro]'))view.insertAdjacentHTML('beforeend',cards(d));return r;};
})();
