// DatoYa — panel permanente de cuenta profesional: portafolio + DatoYa PRO.
(function(){
 if(typeof routes==='undefined'||!routes.perfil)return;
 const old=routes.perfil, safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function load(){const [portfolio,pro]=await Promise.all([api('/worker/portfolio').catch(()=>null),api('/pro/status').catch(()=>null)]);return {portfolio,pro};}
 function cards(d){const p=d.portfolio,pro=d.pro;if(!p&&!pro)return '';
  let html='<style>.professional-dashboard-title{margin:18px 2px 8px}.professional-setting{padding:0!important;overflow:hidden}.professional-setting summary{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:18px;cursor:pointer;font-weight:750;list-style:none}.professional-setting summary::-webkit-details-marker{display:none}.professional-setting summary:after{content:"›";font-size:24px;color:var(--muted);transform:rotate(90deg)}.professional-setting[open] summary:after{transform:rotate(-90deg)}.professional-setting-body{padding:0 18px 18px;border-top:1px solid var(--borde)}.professional-setting-body>p:first-child{margin-top:14px}.professional-profile-grid{display:grid;gap:12px}.professional-profile-grid .card{margin:0}</style><h2 class="section-title professional-dashboard-title">Mi cuenta profesional</h2><div class="professional-profile-grid">';
  if(pro){const c=pro.config?.pro||{},sub=pro.subscription;html+=`<section class="card" data-prof-hub-pro><div class="row between"><div><h3 style="margin:0">⭐ DatoYa PRO</h3><div class="small muted">${pro.is_pro?'Beneficios profesionales habilitados':'Plan opcional'}</div></div>${pro.is_pro?'<span class="pill" style="background:#dcfce7;color:#166534">Activo ✓</span>':'<a class="btn btn-accent btn-sm" href="#/pro">Ver planes</a>'}</div>${pro.is_pro?`<p class="small muted" style="margin-bottom:0">${sub?'Plan '+safe(sub.plan_code||'PRO')+' · ':''}Tu estado PRO se consulta desde una única fuente.</p>`:''}</section>`;}
  if(p){const items=p.items||[],limit=Number((pro?.is_pro?12:4));html+=`<section class="card" data-prof-hub-portfolio><div class="row between"><div><h3 style="margin:0">📸 Portafolio</h3><div class="small muted">${items.length} de ${limit} fotos · ${(pro?.is_pro?'DatoYa PRO':'Plan gratuito')}</div></div></div><p class="small muted">Muestra trabajos reales para que los clientes conozcan tu experiencia.</p>${items.length?`<div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px">${items.map(x=>`<div><img src="${safe(x.data||'')}" alt="${safe(x.caption||'Trabajo realizado')}" style="width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:12px"><div class="small">${safe(x.caption||'')}</div><button class="btn btn-ghost btn-sm" onclick="deleteDatoYaPortfolio(${Number(x.id)})">Eliminar</button></div>`).join('')}</div>`:'<div class="lock-note">Aún no tienes fotos en tu portafolio.</div>'}${items.length<limit?'<button class="btn btn-primary btn-block" style="margin-top:12px" onclick="openDatoYaPortfolioUploader()">📷 Agregar trabajo</button>':''}</section>`;}
  html+='</div><h3 class="professional-dashboard-title">Configuración opcional</h3>';
  return html;
 }
 routes.perfil=async function(){const r=await old.apply(this,arguments);if(!ME||ME.role!=='trabajador')return r;const d=await load();view.querySelectorAll('[data-worker-portfolio]').forEach(x=>x.remove());if(!document.querySelector('[data-prof-hub-portfolio]')&&!document.querySelector('[data-prof-hub-pro]')){const firstSetting=view.querySelector('[data-prof-gps]');if(firstSetting)firstSetting.insertAdjacentHTML('beforebegin',cards(d));else view.insertAdjacentHTML('beforeend',cards(d));}return r;};
})();
