// DatoYa — Protección DatoYa (runtime DEMO)
// Se monta antes de demo_bootstrap y reutiliza el backend existente.
const fs = require('fs');
const path = require('path');
const originalReadFileSync = fs.readFileSync;
const serverFile = path.join(__dirname, 'server.js');

function injectProtection(source) {
  const marker = '// ============ AUTH ============';
  if (!source.includes(marker)) throw new Error('No se encontró el punto de inyección de Protección DatoYa');
  if (source.includes('DAT0YA_PROTECTION_RUNTIME')) return source;
  const block = `
// ============ PROTECCIÓN DATOYA ============
// DAT0YA_PROTECTION_RUNTIME
function protectionConfig(){return {pct:Number(getSetting('protection_pct','5')),reviewHours:Number(getSetting('protection_review_hours','24')),enabled:String(getSetting('protection_enabled','1'))==='1'};}
function protectionForJob(jobId){return db.prepare('SELECT * FROM payment_protections WHERE job_id=?').get(jobId);}
function addProtectionEvent(id,type,actor,metadata){db.prepare('INSERT INTO payment_protection_events(protection_id,event_type,actor_user_id,metadata) VALUES(?,?,?,?)').run(id,type,actor||null,metadata?JSON.stringify(metadata):null);}
function createProtectionForJob(job){const cfg=protectionConfig(),old=protectionForJob(job.id);if(old)return old;const fee=Math.round(job.price*cfg.pct/100),id=db.prepare('INSERT INTO payment_protections(job_id,service_amount,commission_pct,commission_amount,protection_pct,protection_amount,client_total,worker_net,status) VALUES(?,?,?,?,?,?,?,?,?)').run(job.id,job.price,job.commission_pct,job.commission_amount,cfg.pct,fee,job.price+fee,job.worker_amount,'HELD').lastInsertRowid;addProtectionEvent(id,'payment_held_demo',job.client_id,{demo:true,protection_pct:cfg.pct});return protectionForJob(job.id);}
function insertDemoRelease(job){if(!db.prepare('SELECT id FROM payments WHERE job_id=?').get(job.id)){db.prepare("INSERT INTO payments(job_id,amount,commission,worker_amount,method,provider,status) VALUES(?,?,?,?,'tarjeta','DEMO','demo_liberado_protegido')").run(job.id,job.price,job.commission_amount,job.worker_amount);db.prepare('INSERT INTO commissions(job_id,pct,amount) VALUES(?,?,?)').run(job.id,job.commission_pct,job.commission_amount);}return db.prepare('SELECT id FROM payments WHERE job_id=? ORDER BY id DESC LIMIT 1').get(job.id);}
function finalizeProtectedJob(job,actorId){const protection=createProtectionForJob(job);db.prepare("UPDATE jobs SET status='FINALIZADO',updated_at=datetime('now') WHERE id=?").run(job.id);db.prepare('INSERT INTO job_status_history(job_id,status,changed_by) VALUES(?,?,?)').run(job.id,'FINALIZADO',actorId);if(job.status!=='FINALIZADO')db.prepare('UPDATE worker_profiles SET jobs_completed=jobs_completed+1 WHERE id=?').run(job.worker_id);insertDemoRelease(job);db.prepare("UPDATE payment_protections SET status='RELEASED',released_at=datetime('now'),updated_at=datetime('now') WHERE job_id=?").run(job.id);addProtectionEvent(protection.id,'payment_released',actorId,{demo:true});return protectionForJob(job.id);}
app.use('/api/quotes/:id/accept',auth,(req,res,next)=>{res.on('finish',()=>{if(res.statusCode>=200&&res.statusCode<300){try{const job=db.prepare('SELECT * FROM jobs WHERE quote_id=?').get(req.params.id);if(job)createProtectionForJob(job);}catch(_){}}});next();});
app.post('/api/jobs/:id/complete-request',auth,(req,res)=>{const job=db.prepare('SELECT * FROM jobs WHERE id=?').get(req.params.id);if(!job)return res.status(404).json({error:'Trabajo no encontrado'});const wp=db.prepare('SELECT * FROM worker_profiles WHERE id=?').get(job.worker_id);if(!wp||wp.user_id!==req.user.id)return res.status(403).json({error:'Solo el profesional asociado puede indicar que terminó'});if(!['CONFIRMADO','EN_PROCESO'].includes(job.status))return res.status(409).json({error:'El trabajo no está en una etapa válida para terminarlo'});const p=createProtectionForJob(job),cfg=protectionConfig(),deadline=cfg.reviewHours>0?new Date(Date.now()+cfg.reviewHours*3600000).toISOString().slice(0,19).replace('T',' '):null;db.prepare("UPDATE payment_protections SET status='AWAITING_CONFIRMATION',review_deadline=?,updated_at=datetime('now') WHERE job_id=?").run(deadline,job.id);addProtectionEvent(p.id,'awaiting_client_confirmation',req.user.id,{review_deadline:deadline});res.json({ok:true,status:'AWAITING_CONFIRMATION',review_deadline:deadline,demo:true});});
app.use('/api/jobs/:id/status',auth,(req,res,next)=>{const requested=String((req.body||{}).status||'');if(!['FINALIZADO','DISPUTA'].includes(requested))return next();const job=db.prepare('SELECT * FROM jobs WHERE id=?').get(req.params.id);if(!job)return res.status(404).json({error:'Trabajo no encontrado'});const wp=db.prepare('SELECT * FROM worker_profiles WHERE id=?').get(job.worker_id),isClient=job.client_id===req.user.id,isWorker=!!wp&&wp.user_id===req.user.id,isAdmin=req.user.role==='admin';if(!isClient&&!isWorker&&!isAdmin)return res.status(403).json({error:'Sin acceso'});if(requested==='FINALIZADO'){if(!isClient&&!isAdmin)return res.status(403).json({error:'Solo el cliente puede confirmar el trabajo terminado'});if(['FINALIZADO','CANCELADO'].includes(job.status))return res.status(409).json({error:'El trabajo ya no admite confirmación'});return res.json({ok:true,status:'FINALIZADO',protection:finalizeProtectedJob(job,req.user.id),demo:true});}if(!['TRABAJADOR_SELECCIONADO','CONFIRMADO','EN_PROCESO','DISPUTA'].includes(job.status))return res.status(409).json({error:'No se puede abrir una disputa desde este estado'});const reason=String((req.body||{}).reason||'').trim().slice(0,2000);if(!reason)return res.status(400).json({error:'Debes indicar el motivo de la disputa'});const p=createProtectionForJob(job);db.prepare("UPDATE jobs SET status='DISPUTA',updated_at=datetime('now') WHERE id=?").run(job.id);db.prepare("UPDATE payment_protections SET status='DISPUTED',dispute_reason=?,updated_at=datetime('now') WHERE job_id=?").run(reason,job.id);addProtectionEvent(p.id,'dispute_opened',req.user.id,{reason});res.json({ok:true,status:'DISPUTA',protection:protectionForJob(job.id),demo:true});});
app.get('/api/jobs/:id/protection',auth,(req,res)=>{const job=db.prepare('SELECT * FROM jobs WHERE id=?').get(req.params.id);if(!job)return res.status(404).json({error:'Trabajo no encontrado'});const wp=db.prepare('SELECT * FROM worker_profiles WHERE id=?').get(job.worker_id);if(req.user.role!=='admin'&&job.client_id!==req.user.id&&(!wp||wp.user_id!==req.user.id))return res.status(403).json({error:'Sin acceso'});const protection=protectionForJob(job.id),events=protection?db.prepare('SELECT * FROM payment_protection_events WHERE protection_id=? ORDER BY id').all(protection.id):[];res.json({protection,events,demo:true});});
`;
  return source.replace(marker, block+'\n'+marker);
}

fs.readFileSync=function(file,options){const value=originalReadFileSync.call(fs,file,options);if(path.resolve(String(file))===path.resolve(serverFile)&&typeof value==='string')return injectProtection(value);return value;};
try{require('./demo_bootstrap');}finally{fs.readFileSync=originalReadFileSync;}
