// DatoYa — jerarquía territorial de Chile
// Fuente estructural de referencia: DPA/INE. Los códigos DPA de comuna se
// incorporarán en una etapa separada; este archivo contiene la jerarquía completa.
module.exports = [
  {code:'01',name:'Tarapacá',provinces:{'Iquique':['Iquique','Alto Hospicio'],'Tamarugal':['Pozo Almonte','Camiña','Colchane','Huara','Pica']}},
  {code:'02',name:'Antofagasta',provinces:{'Antofagasta':['Antofagasta','Mejillones','Sierra Gorda','Taltal'],'El Loa':['Calama','Ollagüe','San Pedro de Atacama'],'Tocopilla':['Tocopilla','María Elena']}},
  {code:'03',name:'Atacama',provinces:{'Copiapó':['Copiapó','Caldera','Tierra Amarilla'],'Chañaral':['Chañaral','Diego de Almagro'],'Huasco':['Vallenar','Alto del Carmen','Freirina','Huasco']}},
  {code:'04',name:'Coquimbo',provinces:{'Elqui':['La Serena','Coquimbo','Andacollo','La Higuera','Paihuano','Vicuña'],'Choapa':['Illapel','Canela','Los Vilos','Salamanca'],'Limarí':['Ovalle','Combarbalá','Monte Patria','Punitaqui','Río Hurtado']}},
  {code:'05',name:'Valparaíso',provinces:{'Valparaíso':['Valparaíso','Casablanca','Concón','Juan Fernández','Puchuncaví','Quintero','Viña del Mar'],'Isla de Pascua':['Isla de Pascua'],'Los Andes':['Los Andes','Calle Larga','Rinconada','San Esteban'],'Petorca':['La Ligua','Cabildo','Papudo','Petorca','Zapallar'],'Quillota':['Quillota','La Calera','Hijuelas','La Cruz','Nogales'],'San Antonio':['San Antonio','Algarrobo','Cartagena','El Quisco','El Tabo','Santo Domingo'],'San Felipe de Aconcagua':['San Felipe','Catemu','Llay-Llay','Panquehue','Putaendo','Santa María'],'Marga Marga':['Quilpué','Limache','Olmué','Villa Alemana']}},
  {code:'06',name:"Libertador General Bernardo O'Higgins",provinces:{'Cachapoal':['Rancagua','Codegua','Coinco','Coltauco','Doñihue','Graneros','Las Cabras','Machalí','Malloa','Mostazal','Olivar','Peumo','Pichidegua','Quinta de Tilcoco','Rengo','Requínoa','San Vicente'],'Cardenal Caro':['Pichilemu','La Estrella','Litueche','Marchihue','Navidad','Paredones'],'Colchagua':['San Fernando','Chépica','Chimbarongo','Lolol','Nancagua','Palmilla','Peralillo','Placilla','Pumanque','Santa Cruz']}},
  {code:'07',name:'Maule',provinces:{'Talca':['Talca','Constitución','Curepto','Empedrado','Maule','Pelarco','Pencahue','Río Claro','San Clemente','San Rafael'],'Curicó':['Curicó','Hualañé','Licantén','Molina','Rauco','Romeral','Sagrada Familia','Teno','Vichuquén'],'Linares':['Linares','Colbún','Longaví','Parral','Retiro','San Javier','Villa Alegre','Yerbas Buenas'],'Cauquenes':['Cauquenes','Chanco','Pelluhue']}},
  {code:'08',name:'Biobío',provinces:{'Concepción':['Concepción','Coronel','Chiguayante','Florida','Hualqui','Lota','Penco','San Pedro de La Paz','Santa Juana','Talcahuano','Tomé','Hualpén'],'Arauco':['Lebu','Arauco','Cañete','Contulmo','Curanilahue','Los Álamos','Tirúa'],'Biobío':['Los Ángeles','Antuco','Cabrero','Laja','Mulchén','Nacimiento','Negrete','Quilaco','Quilleco','San Rosendo','Santa Bárbara','Tucapel','Yumbel','Alto Biobío']}},
  {code:'09',name:'La Araucanía',provinces:{'Malleco':['Angol','Collipulli','Curacautín','Ercilla','Lonquimay','Los Sauces','Lumaco','Purén','Renaico','Traiguén','Victoria'],'Cautín':['Temuco','Carahue','Cholchol','Cunco','Curarrehue','Freire','Galvarino','Gorbea','Lautaro','Loncoche','Melipeuco','Nueva Imperial','Padre Las Casas','Perquenco','Pitrufquén','Pucón','Saavedra','Teodoro Schmidt','Toltén','Vilcún','Villarrica']}},
  {code:'10',name:'Los Lagos',provinces:{'Osorno':['Osorno','Puerto Octay','Purranque','Puyehue','Río Negro','San Juan de la Costa','San Pablo'],'Llanquihue':['Puerto Montt','Calbuco','Cochamó','Fresia','Frutillar','Llanquihue','Los Muermos','Maullín','Puerto Varas'],'Chiloé':['Castro','Ancud','Chonchi','Curaco de Vélez','Dalcahue','Puqueldón','Queilén','Quellón','Quemchi','Quinchao'],'Palena':['Chaitén','Futaleufú','Hualaihué','Palena']}},
  {code:'11',name:'Aysén del General Carlos Ibáñez del Campo',provinces:{'Coihaique':['Coihaique','Lago Verde'],'Aysén':['Puerto Aysén','Cisnes','Guaitecas'],'General Carrera':['Chile Chico','Río Ibáñez'],'Capitán Prat':['Cochrane',"O'Higgins",'Tortel']}},
  {code:'12',name:'Magallanes y de la Antártica Chilena',provinces:{'Última Esperanza':['Natales','Torres del Paine'],'Magallanes':['Punta Arenas','Laguna Blanca','Río Verde','San Gregorio'],'Tierra del Fuego':['Porvenir','Primavera','Timaukel'],'Antártica Chilena':['Antártica','Cabo de Hornos']}},
  {code:'13',name:'Metropolitana de Santiago',provinces:{'Santiago':['Santiago','Cerrillos','Cerro Navia','Conchalí','El Bosque','Estación Central','Huechuraba','Independencia','La Cisterna','La Florida','La Granja','La Pintana','La Reina','Las Condes','Lo Barnechea','Lo Espejo','Lo Prado','Macul','Maipú','Pedro Aguirre Cerda','Peñalolén','Providencia','Pudahuel','Quilicura','Quinta Normal','Recoleta','Renca','San Joaquín','San Miguel','San Ramón','Vitacura','Ñuñoa'],'Cordillera':['Puente Alto','Pirque','San José de Maipo'],'Chacabuco':['Colina','Lampa','Tiltil'],'Maipo':['San Bernardo','Buin','Calera de Tango','Paine'],'Melipilla':['Melipilla','Alhué','Curacaví','María Pinto','San Pedro'],'Talagante':['Talagante','El Monte','Isla de Maipo','Padre Hurtado','Peñaflor']}},
  {code:'14',name:'Los Ríos',provinces:{'Valdivia':['Valdivia','Corral','Lanco','Los Lagos','Mariquina','Máfil','Paillaco','Panguipulli'],'Ranco':['La Unión','Futrono','Lago Ranco','Río Bueno']}},
  {code:'15',name:'Arica y Parinacota',provinces:{'Arica':['Arica','Camarones'],'Parinacota':['Putre','General Lagos']}},
  {code:'16',name:'Ñuble',provinces:{'Diguillín':['Bulnes','Chillán Viejo','Chillán','El Carmen','Pemuco','Pinto','Quillón','San Ignacio','Yungay'],'Itata':['Cobquecura','Coelemu','Ninhue','Portezuelo','Quirihue','Ránquil','Trehuaco'],'Punilla':['San Carlos','Coihueco','San Fabián','San Nicolás','Ñiquén']}}
];
