'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),Database=require('better-sqlite3'),fs=require('node:fs');
const k=require('./khipu_integrator');
async function main(){
  const vm=require('node:vm'),sqlCalls=[];
  const bootstrap=fs.readFileSync('khipu_business_onboarding_bootstrap.js','utf8');
  vm.runInNewContext(bootstrap,{__dirname:process.cwd(),require:name=>name==='./db'?{db:{exec:sql=>sqlCalls.push(sql)}}:name==='fs'?{readFileSync:path=>String(path).endsWith('.sql')?fs.readFileSync(path,'utf8'):'// ============ CATÁLOGOS ============',writeFileSync(){}}:require(name),console:{log(){}}});
  const pg=fs.readFileSync('db_pg.js','utf8'),parser=pg.slice(pg.indexOf('function splitStatements('),pg.indexOf('function pragmaInfo(')),pgContext={};
  vm.runInNewContext(parser,pgContext);
  for(const sql of pgContext.splitStatements(sqlCalls[1]))assert.match(sql,/^CREATE TABLE/i);
  const db=new Database(':memory:');db.pragma('foreign_keys=ON');
  db.exec('CREATE TABLE businesses(id INTEGER PRIMARY KEY);INSERT INTO businesses VALUES(7),(8);CREATE TABLE business_khipu_onboarding(business_id INTEGER PRIMARY KEY,status TEXT,receiver_id TEXT,provider_note TEXT,updated_at TEXT);INSERT INTO business_khipu_onboarding(business_id,status) VALUES(7,\'pending_integrator\'),(8,\'pending_integrator\');');
  db.exec(fs.readFileSync('postgres/015_khipu_integrator_credentials.sql','utf8'));
  const key=crypto.randomBytes(32),credentials={receiver_id:'child-7',secret:'only-test-secret',api_key:'only-test-child-key'};
  assert.throws(()=>k.encryptionKey({}));
  k.saveReceiver(db,7,credentials,key);k.saveReceiver(db,7,credentials,key);
  const stored=db.prepare('SELECT * FROM business_khipu_credentials').get();
  assert.doesNotMatch(stored.encrypted_credentials,/only-test/);
  assert.throws(()=>k.unseal(stored.encrypted_credentials,8,key));
  assert.throws(()=>k.unseal(stored.encrypted_credentials,7,crypto.randomBytes(32)));
  const tampered=JSON.parse(stored.encrypted_credentials);tampered.data=Buffer.from('tampered').toString('base64');assert.throws(()=>k.unseal(JSON.stringify(tampered),7,key));
  assert.throws(()=>k.saveReceiver(db,7,{...credentials,receiver_id:'other'},key));
  assert.throws(()=>k.saveReceiver(db,8,{receiver_id:'missing-key'},key));
  assert.equal(db.prepare('SELECT COUNT(*) n FROM business_khipu_credentials').get().n,1);
  const order={business_id:7,total:10000,datoya_commission_estimate:590,reference:'QA',transaction_id:'test-unique'};
  let loaded=k.loadReceiver(db,7,key);assert.throws(()=>k.paymentRequest(order,loaded.account,loaded.credentials,100));
  assert.equal(k.recordActivation(db,7,{id:'child-7',disabled:false,can_collect:false}),'pending_khipu_activation');
  assert.throws(()=>k.recordActivation(db,7,{id:'other',disabled:false,can_collect:true}));
  assert.throws(()=>k.recordActivation(db,7,{id:'child-7',disabled:'false',can_collect:'true'}));
  assert.equal(k.recordActivation(db,7,{id:'child-7',disabled:false,can_collect:true}),'active');
  loaded=k.loadReceiver(db,7,key);const request=k.paymentRequest(order,loaded.account,loaded.credentials,100);
  assert.equal(request.path,'/v3/payments');assert.equal(request.headers['x-api-key'],credentials.api_key);assert.equal(request.body.integrator_fee,'590');
  assert.equal(k.paymentRequest({...order,datoya_commission_estimate:0},loaded.account,loaded.credentials,100).body.integrator_fee,'0');
  assert.throws(()=>k.paymentRequest({...order,business_id:8},loaded.account,loaded.credentials,100));
  assert.throws(()=>k.paymentRequest({...order,datoya_commission_estimate:9950},loaded.account,loaded.credentials,100));
  assert.equal(k.recordActivation(db,7,{id:'child-7',disabled:true,can_collect:true}),'pending_khipu_activation');
  assert.equal(k.publicState({status:'ready_for_integrator'}).status,'pending_integrator');
  assert.equal(k.publicState({status:'active'}).status,'pending_khipu_activation');
  assert.equal(k.publicState({...stored,status:'active'}).live_payments_allowed,false);
  assert.doesNotMatch(JSON.stringify(k.publicState({...stored,...credentials,status:'active'})),/secret|api_key|only-test/);
  const fields={owner_first_name:'Test',owner_last_name:'Owner',owner_email:'qa@example.invalid',country_code:'CL',billing_identifier:'QA-123456',business_activity:'Prueba aislada',billing_name:'QA',billing_phone:'+56900000000',billing_address:'Dirección local',billing_city:'Ciudad local',billing_region:'Región local',contact_name:'Test Owner',contact_role:'Dueño',contact_email:'qa@example.invalid',contact_phone:'+56900000000'};
  const receiver=k.receiverRequest(fields,'only-test-parent-key');assert.equal(receiver.path,'/v3/receivers');assert.equal(receiver.body.admin_first_name,'Test');assert.equal(receiver.headers['x-api-key'],'only-test-parent-key');assert.equal(Object.keys(receiver.body).length,15);
  assert.equal(k.activationRequest('only-test-parent-key').path,'/v3/receivers/children');
  process.env.KHIPU_INTEGRATOR_ENABLED='true';process.env.DATOYA_KHIPU_LIVE_PAYMENTS='true';
  await assert.rejects(k.createReceiver(receiver),{code:'KHIPU_INTEGRATOR_BLOCKED'});await assert.rejects(k.createChildPayment(request),{code:'KHIPU_INTEGRATOR_BLOCKED'});
  assert.equal(k.RELEASE_NETWORK_ENABLED,false);db.close();console.log('Khipu V3: encrypted tenant credentials, activation, commission and hard network gate OK');
}
main().catch(()=>{console.error('Khipu integrator regression failed');process.exitCode=1});
