// DatoYa 2.0 — helpers de especialidades para profesionales.
// El perfil completo es la única pantalla de edición; este archivo ya no reemplaza routes.perfil.
(function(){
 if(typeof routes==='undefined')return;
 const e=s=>typeof esc==='function'?esc(s):String(s??'');
 window.updateDatoYaSpecialtyCount=function(){const n=document.querySelectorAll('input[name="specialty"]:checked').length;const el=document.getElementById('specialty-count');if(el)el.textContent=n+' de 4 especialidades seleccionadas';};
 window.limitDatoYaSpecialties=function(input){const checked=[...document.querySelectorAll('input[name="specialty"]:checked')];if(checked.length>4){input.checked=false;toast('Puedes elegir hasta 4 especialidades','err');}if(!input.checked){const r=document.querySelector('input[name="primary_specialty"][value="'+input.value+'"]');if(r&&r.checked)r.checked=false;}updateDatoYaSpecialtyCount();};
 window.chooseDatoYaPrimary=function(id){const cb=document.querySelector('input[name="specialty"][value="'+id+'"]');if(cb&&!cb.checked){const current=document.querySelectorAll('input[name="specialty"]:checked').length;if(current>=4){toast('Primero desmarca una especialidad','err');const r=document.querySelector('input[name="primary_specialty"][value="'+id+'"]');if(r)r.checked=false;return;}cb.checked=true;updateDatoYaSpecialtyCount();}};
 window.saveDatoYaSpecialties=async function(ev){ev.preventDefault();const ids=[...document.querySelectorAll('input[name="specialty"]:checked')].map(x=>Number(x.value));const radio=document.querySelector('input[name="primary_specialty"]:checked');if(!ids.length)return toast('Elige al menos una especialidad','err');if(!radio)return toast('Marca una especialidad principal','err');const primary=Number(radio.value);if(!ids.includes(primary))return toast('La especialidad principal debe estar seleccionada','err');try{await api('/worker/specialties',{method:'POST',body:{category_ids:ids,primary_category_id:primary}});await refreshMe();toast('Especialidades guardadas','ok');if(location.hash!=='#/perfil')location.hash='#/perfil';else route();}catch(err){toast(err.message||'No se pudo guardar','err');}};
})();
