// One-time PostgreSQL -> PostgreSQL migration for DatoYa.
// Source: DATABASE_URL (current Render Postgres)
// Target: DATOYA_MIGRATION_TARGET_URL (new Neon Postgres)
// Refuses to overwrite a non-empty target and records a migration marker.
const {Client}=require('pg');

const sourceUrl=process.env.DATABASE_URL;
const targetUrl=process.env.DATOYA_MIGRATION_TARGET_URL;
const migrationId=process.env.DATOYA_MIGRATION_ID||'render-to-neon-20260920';

if(!sourceUrl) throw new Error('Missing DATABASE_URL source');
if(!targetUrl) throw new Error('Missing DATOYA_MIGRATION_TARGET_URL');
if(sourceUrl===targetUrl) throw new Error('Source and target database URLs are identical');

const ssl={rejectUnauthorized:false};
const src=new Client({connectionString:sourceUrl,ssl});
const dst=new Client({connectionString:targetUrl,ssl});

const qi=s=>'"'+String(s).replace(/"/g,'""')+'"';
const qn=(schema,name)=>qi(schema)+'.'+qi(name);

async function rows(client,sql,params=[]){ return (await client.query(sql,params)).rows; }

async function main(){
  await src.connect();
  await dst.connect();
  try{
    await dst.query(`CREATE TABLE IF NOT EXISTS public.datoya_migration_audit(
      migration_id text PRIMARY KEY,
      source text NOT NULL,
      completed_at timestamptz NOT NULL DEFAULT now(),
      table_count integer NOT NULL,
      row_count bigint NOT NULL
    )`);
    const done=await rows(dst,'SELECT migration_id FROM public.datoya_migration_audit WHERE migration_id=$1',[migrationId]);
    if(done.length){
      console.log('[DatoYa][DB Migration] already completed:',migrationId);
      return;
    }

    const targetTables=await rows(dst,`
      SELECT table_name FROM information_schema.tables
      WHERE table_schema='public' AND table_type='BASE TABLE'
        AND table_name<>'datoya_migration_audit'
    `);
    if(targetTables.length) throw new Error('Target database is not empty; refusing to overwrite');

    const tables=await rows(src,`
      SELECT c.relname AS table_name
      FROM pg_class c
      JOIN pg_namespace n ON n.oid=c.relnamespace
      WHERE n.nspname='public' AND c.relkind='r'
      ORDER BY c.relname
    `);
    if(!tables.length) throw new Error('Source database has no public tables');

    const seqs=await rows(src,`
      SELECT ns.nspname AS sequence_schema, s.relname AS sequence_name,
             tn.nspname AS table_schema, t.relname AS table_name, a.attname AS column_name
      FROM pg_class s
      JOIN pg_namespace ns ON ns.oid=s.relnamespace
      LEFT JOIN pg_depend d ON d.objid=s.oid AND d.deptype='a'
      LEFT JOIN pg_class t ON t.oid=d.refobjid
      LEFT JOIN pg_namespace tn ON tn.oid=t.relnamespace
      LEFT JOIN pg_attribute a ON a.attrelid=t.oid AND a.attnum=d.refobjsubid
      WHERE s.relkind='S' AND ns.nspname='public'
      ORDER BY s.relname
    `);
    for(const s of seqs){
      await dst.query(`CREATE SEQUENCE ${qn(s.sequence_schema,s.sequence_name)}`);
    }

    for(const t of tables){
      const cols=await rows(src,`
        SELECT a.attname AS column_name,
               format_type(a.atttypid,a.atttypmod) AS data_type,
               a.attnotnull AS not_null,
               pg_get_expr(ad.adbin,ad.adrelid) AS column_default,
               a.attidentity AS identity_kind,
               a.attgenerated AS generated_kind
        FROM pg_attribute a
        JOIN pg_class c ON c.oid=a.attrelid
        JOIN pg_namespace n ON n.oid=c.relnamespace
        LEFT JOIN pg_attrdef ad ON ad.adrelid=a.attrelid AND ad.adnum=a.attnum
        WHERE n.nspname='public' AND c.relname=$1
          AND a.attnum>0 AND NOT a.attisdropped
        ORDER BY a.attnum
      `,[t.table_name]);
      const defs=cols.map(c=>{
        if(c.generated_kind) throw new Error('Generated columns are not supported by migration: '+t.table_name+'.'+c.column_name);
        let d=qi(c.column_name)+' '+c.data_type;
        if(c.identity_kind==='a') d+=' GENERATED ALWAYS AS IDENTITY';
        else if(c.identity_kind==='d') d+=' GENERATED BY DEFAULT AS IDENTITY';
        else if(c.column_default) d+=' DEFAULT '+c.column_default;
        if(c.not_null) d+=' NOT NULL';
        return d;
      });
      await dst.query(`CREATE TABLE ${qn('public',t.table_name)} (${defs.join(', ')})`);
    }

    // Copy data before constraints/FKs so ordering cannot block inserts.
    let totalRows=0;
    for(const t of tables){
      const data=await rows(src,`SELECT * FROM ${qn('public',t.table_name)}`);
      if(!data.length) continue;
      const columns=Object.keys(data[0]);
      const colSql=columns.map(qi).join(',');
      const chunkSize=200;
      for(let i=0;i<data.length;i+=chunkSize){
        const chunk=data.slice(i,i+chunkSize);
        const values=[];
        const tuples=chunk.map((r,ri)=>{
          const ps=columns.map((c,ci)=>{
            values.push(r[c]);
            return '$'+(ri*columns.length+ci+1);
          });
          return '('+ps.join(',')+')';
        });
        await dst.query(`INSERT INTO ${qn('public',t.table_name)} (${colSql}) VALUES ${tuples.join(',')}`,values);
      }
      totalRows+=data.length;
      console.log('[DatoYa][DB Migration] copied',t.table_name,data.length);
    }

    const constraints=await rows(src,`
      SELECT con.conname, c.relname AS table_name, con.contype,
             pg_get_constraintdef(con.oid,true) AS def
      FROM pg_constraint con
      JOIN pg_class c ON c.oid=con.conrelid
      JOIN pg_namespace n ON n.oid=c.relnamespace
      WHERE n.nspname='public' AND con.contype IN ('p','u','c','f')
      ORDER BY CASE con.contype WHEN 'p' THEN 1 WHEN 'u' THEN 2 WHEN 'c' THEN 3 WHEN 'f' THEN 4 ELSE 9 END,
               c.relname, con.conname
    `);
    for(const c of constraints){
      await dst.query(`ALTER TABLE ${qn('public',c.table_name)} ADD CONSTRAINT ${qi(c.conname)} ${c.def}`);
    }

    const indexes=await rows(src,`
      SELECT indexname,indexdef
      FROM pg_indexes
      WHERE schemaname='public'
        AND indexname NOT IN (
          SELECT con.conname FROM pg_constraint con
          JOIN pg_namespace n ON n.oid=con.connamespace
          WHERE n.nspname='public' AND con.contype IN ('p','u')
        )
      ORDER BY indexname
    `);
    for(const idx of indexes){
      await dst.query(idx.indexdef);
    }

    for(const s of seqs){
      const current=await rows(src,`SELECT last_value,is_called FROM ${qn(s.sequence_schema,s.sequence_name)}`);
      if(current[0]){
        await dst.query('SELECT setval($1::regclass,$2,$3)',[
          s.sequence_schema+'.'+s.sequence_name,
          String(current[0].last_value),
          !!current[0].is_called
        ]);
      }
      if(s.table_name&&s.column_name){
        await dst.query(`ALTER SEQUENCE ${qn(s.sequence_schema,s.sequence_name)} OWNED BY ${qn(s.table_schema,s.table_name)}.${qi(s.column_name)}`);
      }
    }

    // Verify exact row counts for every source table.
    for(const t of tables){
      const a=await rows(src,`SELECT COUNT(*)::bigint AS n FROM ${qn('public',t.table_name)}`);
      const b=await rows(dst,`SELECT COUNT(*)::bigint AS n FROM ${qn('public',t.table_name)}`);
      if(String(a[0].n)!==String(b[0].n)) throw new Error('Count mismatch for '+t.table_name+': '+a[0].n+' vs '+b[0].n);
    }

    await dst.query(
      'INSERT INTO public.datoya_migration_audit(migration_id,source,table_count,row_count) VALUES($1,$2,$3,$4)',
      [migrationId,'render-postgres',tables.length,totalRows]
    );
    console.log('[DatoYa][DB Migration] COMPLETE',JSON.stringify({migrationId,tables:tables.length,rows:totalRows}));
  } finally {
    await Promise.allSettled([src.end(),dst.end()]);
  }
}
main().catch(err=>{console.error('[DatoYa][DB Migration] FAILED',err.message);process.exit(1);});
